---
title: "Linear Mixed Effects Models for Kin & Speed Predictors for EEG"
author: "Jacob Salminen"
date: \`r format(Sys.Date(),"%d-%m-%Y")`\
output:
  html_document:
    theme: flatly
    toc: true
    toc_depth: 6
    toc_float:
      collapsed: true
      smooth_scroll: true
    df_print: paged
---

```{r setup, include=FALSE}
# ERROR. png() device not found bug try: dev.off()
# ERROR. png() device not found fixed by changing cell names to a simple "windows friendlY" format so that knitr could save files.
knitr::opts_chunk$set(echo = TRUE)
```

# Packages & Setup
```{r}
# install.packages(c("tidyverse","purrr","R.matlab","readxl","dplyr"))
library(readxl);
library(purrr);
library(tidyverse);
library(tibble);
library(knitr);
library(gtsummary);
library(kableExtra);
library(lme4);
library(MuMIn);
# library(effects);
library(sjPlot);
# library(plotly);
# library(webshot)
# library(reshape2);
library(htmltools)
library(Polychrome);
# library(htmlwidgets);
# library(shiny)
# library(webshot)
library(scatterplot3d)
library(RColorBrewer)
```

## GTSUMMARY THEME
``` {r}
# my_theme <-
#   list(
#     "tbl_summary-str:default_con_type" = "continuous2",
#     "tbl_summary-str:continuous_stat" = c(
#       "{median} ({p25} - {p75})",
#       "{mean} ({sd})",
#       "{min} - {max}"
#     ),
#     "tbl_summary-str:categorical_stat" = "{n} / {N} ({p}%)",
#     "style_number-arg:big.mark" = "",
#     "tbl_summary-fn:percent_fun" = function(x) style_percent(x, digits = 3)
#   )
# my_theme <-
#   list()
# gtsummary::set_gtsummary_theme(my_theme)
gtsummary::set_gtsummary_theme(theme_gtsummary_journal("jama"))
# reset_gtsummary_theme()
```

# load table 
```{r} 
# excel_dir <-"M:/jsalminen/GitHub/par_EEGProcessing/src/_data/MIM_dataset/_studies/04162024_MIM_YAOAN89_antsnormalize_iccREMG0p4_powpow0p3_skull0p01/cluster/icrej_5/12/spec_data/group_spec/psd_calcs/fooof_kinematics_table.xlsx";
# excel_dir <-"M:/jsalminen/GitHub/par_EEGProcessing/src/_data/MIM_dataset/_studies/04232024_MIM_YAOAN89_antsnorm_dipfix_iccREMG0p4_powpow0p3_skull0p01_15mmrej/cluster/icrej_5/11/spec_data/group_spec/psd_calcs/fooof_kinematics_table_nans.xlsx";
excel_dir <-"M:/jsalminen/GitHub/par_EEGProcessing/src/_data/MIM_dataset/_studies/04232024_MIM_YAOAN89_antsnorm_dipfix_iccREMG0p4_powpow0p3_skull0p01_15mmrej/iclabel_cluster_kmeansalt_rb3/icrej_5/11/psd_calcs/group_spec/kin_tests/fooof_kinematics_table.xlsx";
orig_eegt <- read_excel(excel_dir,sheet="Sheet1") 
```

## get unique entries 
```{r} 

#%% KIN PARAMS
# kin_measures = c('mean_APexc_COV','mean_APexc_mean','mean_MLexc_COV','mean_MLexc_mean','mean_StepDur','mean_StepDur_cov','mean_UDexc_COV','mean_UDexc_mean','mean_StanceDur','mean_GaitCycleDur','mean_PeakUpDownVel_mean');
# kin_title_chars = c("AP Exc. COV","AP Exc. Mean","ML Exc. COV","ML Exc. Mean","Step Dur.","Step Dur. COV","UD Exc. COV","UD Exc Mean","Stance Dur.","Gait Cycle Dur.","Peak UD Vel. Mean")
kin_measures = c('mean_APexc_COV','mean_MLexc_COV','mean_StepDur_cov','mean_StanceDur');
kin_title_chars = c("AP Exc. COV","ML Exc. COV","Step Dur. COV","Stance Dur.")
# kin_measures = c('mean_APexc_COV');
# kin_title_chars = c("AP Exc. COV")
kin_inds_plot = c(1:length(kin_measures));
# kin_inds_plot = c(1,3,6,5,7);
#%% EEG PARAMS
clusters = unique(orig_eegt$cluster_id);
subjects = unique(orig_eegt$subj_char);
groups = unique(orig_eegt$group_char);
# eeg_measures = c('theta_avg_power','alpha_avg_power','beta_avg_power','beta_div_theta','theta_div_beta','log_beta_div_theta','log_theta_div_beta','aperiodic_exp','aperiodic_offset');
# eeg_title_chars = c("**THETA**","**ALPHA**","**BETA**","**BETA/THETA**","**THETA/BETA**","**log10(BETA/THETA)**","**log10(THETA/BETA)**","**AP exp**","**AP offset**");
# eeg_measures = c('theta_avg_power','alpha_avg_power','beta_avg_power','aperiodic_exp','aperiodic_offset');
eeg_measures = c('norm_theta_avg_power','norm_alpha_avg_power','norm_beta_avg_power');
eeg_title_chars = c("**THETA**","**ALPHA**","**BETA**");
# eeg_inds_plot = c(1:length(eeg_title_chars));
eeg_inds_plot = c(1,2,3);
# x_vals_plot = c('speed_diffdiv_stat')
# x_vals_labs = c("**{DELTA Speed}/{Subj. Speed}**")
# x_vals_plot = 'speed_diff_stat'
# x_vals_labs = c("Trial_vel-Subj_vel/(Subj_vel)**")
x_vals_plot = c('speed_div_stat')
x_vals_labs = c("**{Trial_vel/Subj_vel}**")
cluster_inds_plot = c(3,4,5,6,7,8,12);
```

## create ratios
```{r}
df <- orig_eegt %>%
  select(subj_char,cond_char,cluster_id,group_id,alpha_avg_power,beta_avg_power,theta_avg_power) %>%
  pivot_wider(names_from = "cond_char", names_sep = '.', values_from = c(alpha_avg_power,beta_avg_power,theta_avg_power))

# df <- df %>%
#   group_by(subj_char) %>%
#   mutate(across(starts_with("alpha_avg_power"), ~ .x/alpha_avg_power.flat))
# df <- df %>%
#   group_by(subj_char) %>%
#   mutate(across(starts_with("beta_avg_power"), ~ .x/beta_avg_power.flat))
# df <- df %>%
#   group_by(subj_char) %>%
#   mutate(across(starts_with("theta_avg_power"), ~ .x/theta_avg_power.flat))
df <- df %>%
  group_by(subj_char) %>%
  mutate(across(starts_with("alpha_avg_power"), ~ .x-alpha_avg_power.flat))
df <- df %>%
  group_by(subj_char) %>%
  mutate(across(starts_with("beta_avg_power"), ~ .x-beta_avg_power.flat))
df <- df %>%
  group_by(subj_char) %>%
  mutate(across(starts_with("theta_avg_power"), ~ .x-theta_avg_power.flat))

df <- df %>%
  pivot_longer(cols = starts_with(c("alpha","beta","theta")), names_to = c(".value","cond_char"), names_pattern = "(.*_power).(.*)");

df$norm_alpha_avg_power <- df$alpha_avg_power
df$norm_beta_avg_power <- df$beta_avg_power
df$norm_theta_avg_power <- df$theta_avg_power
df <- select(df,-alpha_avg_power,-beta_avg_power,-theta_avg_power);
eegt <- merge(orig_eegt , df, by.x = c("subj_char","cond_char","cluster_id","group_id"), by.y = c("subj_char","cond_char","cluster_id","group_id"));
# kin_measures = c('mean_APexc_COV','mean_MLexc_COV','mean_StepDur_COV','mean_StanceDur');
eegt <- eegt %>%
  select(subj_char,cond_char,group_char,cluster_id,group_id,norm_alpha_avg_power,norm_theta_avg_power,norm_beta_avg_power,alpha_avg_power,beta_avg_power,theta_avg_power,mean_APexc_COV,mean_MLexc_COV,mean_StepDur_cov,mean_StanceDur,speed_div_stat,speed_diff_stat,speed_diffdiv_stat,speed_ms);
eegt$x_vals_plot = eegt[[x_vals_plot]];
```
## get speeds only 
```{r}
eegt <- filter_at(eegt,vars('cond_char'), any_vars(. %in% c('0.25','0.5','0.75','1.0')))
# eegt <- filter_at(eegt,vars('cond_char'), any_vars(. %in% c('flat','0.25','0.5','0.75','1.0')))
#%% SPEED_DIFF_STAT
# eegt <- eegt %>%
#   mutate(x_vals_plot = ifelse(cond_char == "flat", 0, x_vals_plot)) #as.character(speed_ms)
# eegt <- eegt %>%
#   mutate(cond_char = ifelse(cond_char == "flat", as.character(0), cond_char)) #as.character(speed_ms)
#%% SPEED_DIV_STAT
# eegt <- eegt %>%
#   mutate(x_vals_plot = ifelse(cond_char == "flat", 1, x_vals_plot)) #as.character(speed_ms)
# eegt <- eegt %>%
#   mutate(cond_char = ifelse(cond_char == "flat", as.character(1), cond_char)) #as.character(speed_ms)
#%% COND_CHAR
# eegt <- eegt %>%
#   mutate(cond_char = ifelse(cond_char == "flat", speed_ms, cond_char)) #as.character(speed_ms)
#%%
flat_speeds = unique(eegt$cond_char)
# eegt$speed_cond_num <- as.numeric(eegt$x_vals_plot);
eegt$speed_cond_num <- as.numeric(eegt$cond_char);
eegt <- mutate(eegt,across(c('subj_char'), factor))
eegt <- mutate(eegt,across(c('group_char'), factor))
# color_pal_group = as.vector(createPalette(length(levels(eegt$group_char)),c("#0000ff")));
color_pal_subj = brewer.pal(9,'PuBuGn')
      color_pal_subj = color_pal_subj[5:9];
head(eegt)
```

# MODERATION 1) LME EEG ~ 1+speed+kin+speed:kin
```{r eegspeedkininter, echo=FALSE, message=FALSE, results="asis"}
for (ci in cluster_inds_plot) {
  tmptc <- filter_at(eegt,vars('cluster_id'), any_vars(. %in% ci));
  for(ki in kin_inds_plot){
    tmptc = tmptc[complete.cases(tmptc[[kin_measures[ki]]]),]
  }
  tmpt <- tmptc;
  for(ki in kin_inds_plot){
    mod_char = paste("{outcome} ~ 1 + speed_cond_num + ",kin_measures[ki]," + speed_cond_num:",kin_measures[ki]," + (1|subj_char)");
    tbl <- tibble(outcome=eeg_measures[eeg_inds_plot]) %>%
      rowwise() %>%
      mutate(
        tbl = 
          lmer(str_glue(mod_char), data=tmpt) %>%
          tbl_regression(tidy_fun = broom.mixed::tidy,
                         pvalue_fun = purrr::partial(style_pvalue, digits = 2),
                         intercept=TRUE) %>%
          add_global_p() %>%
          add_q() %>%
          list()
        ) %>%
      pull(tbl) %>% 
      tbl_merge(tab_spanner=eeg_title_chars[eeg_inds_plot])
    
    #- HTML TAG
    # print(htmltools:tags(HTML(markdown::mark(text=paste0("\n\n### ", ci,",", ki, "\n")))))
    cat(paste0("\n\n### ", ci,",", kin_measures[ki], "\n"))
    #%% PRINT TABLE
    t_out <- as_gt(tbl) %>%
      gt::tab_header(title=c("Changes in ",kin_measures[ki],"for Cluster: ",ci)) %>%
      gt::tab_options(table.layout = "fixed") %>%
      gt::as_raw_html()
    print(t_out)
    
    rsq <- tibble(outcome=eeg_measures[eeg_inds_plot]) %>%
    rowwise() %>%
    mutate(
        mod = 
          lmer(str_glue(mod_char), data=tmpt) %>%
          r.squaredGLMM(),
          print(str_glue("{outcome}\n R2m: {round(mod[1],4)},\tR2c: {round(mod[2],4)}\n\n"))
    )
    
    #%% VISUALIZATION OF MODELS
    theme_set(theme_classic()) # This sets the default ggplot theme
    fitfit <- tibble(outcome=eeg_measures[eeg_inds_plot]) %>%
      rowwise() %>%
      mutate(
          mod = 
            lmer(str_glue(mod_char), data=tmpt)%>%
            list()
      )
    # color_pal_subj = as.vector(createPalette(length(levels(tmpt$subj_char)),c("#4f4f4f","#5f5f5f")));
    
    for(modi in 1:length(eeg_measures[eeg_inds_plot])){
      eegi = eeg_inds_plot[modi]
      #%% MODEL VALIDATIONS
      cat(paste0("\n\n#### ",eeg_title_chars[modi]," model validations\n"))
      tmpt <- tmpt %>%
        mutate(fit.m = predict(fitfit$mod[[modi]], re.form = NA),
               fit.c = predict(fitfit$mod[[modi]], re.form = NULL))
      print(plot_model(fitfit$mod[[modi]], type = 'diag'))
      cat("\n")
      cat(paste0("\n\n#### ",eeg_title_chars[modi]," plot\n"))
      #%% SCATTER3D IMPLEMENTATION
      xc = "speed_cond_num";
      yc = kin_measures[ki];
      intc = paste0(xc,":",yc)
      fix_effs <- fixef(fitfit$mod[[modi]])
      ran_effs <- ranef(fitfit$mod[[modi]])$subj_char
      #- plot
      subjs = unique(tmpt[[xc]])
      for(i in 1:length(subjs)){
        ts <- filter_at(tmpt,vars(xc),all_vars(. == subjs[i]))
        if(i == 1){
          scatter <- scatterplot3d(ts[[yc]], ts[[xc]], ts[[eeg_measures[eegi]]],
            main = paste0(eeg_title_chars[modi],"plot"),
            xlab = kin_title_chars[ki],
            ylab = "Speed (m/s)",
            zlab = eeg_title_chars[eegi],
            xlim = c(min(tmpt[[yc]]),max(tmpt[[yc]])),
            ylim = c(min(tmpt[[xc]]),max(tmpt[[xc]])),
            zlim = c(min(tmpt[[eeg_measures[eegi]]]),max(tmpt[[eeg_measures[eegi]]])),
            pch = 16,
            color = color_pal_subj[i],
            angle = 30) # adjust the viewing angle
        } else {
        scatter$points3d(ts[[yc]], ts[[xc]], ts[[eeg_measures[eegi]]] ,
            main = paste0(eeg_title_chars[modi],"plot"),
            col = color_pal_subj[i],
            pch=16)
        }
      }
      a <- fix_effs[xc]
      b <- fix_effs[yc]
      c <- fix_effs[intc]
      d <- fix_effs["(Intercept)"]
      # Create the plane's z-values using the equation of the plane
      plane_z <- function(y,x){a*x+b*y+c*x*y+d}
      scatter$contour3d(plane_z,y.count=4,
                        x.count=4,
                        y.resolution=10,
                        x.resolution=10,
                        lty="24",
                        type="l")
      # print(scatter)
      # l[[cnt]] <- tagList(HTML(markdown::mark(text=paste0("\n\n#### ", cnt, "\n"))),scatter)
    }
    
  } 
}
```

# MODERATION 2) LME EEG ~ 1+speed+kin
```{r eegspeedk, echo=FALSE, message=FALSE, results="asis"}
for (ci in cluster_inds_plot) {
  tmptc <- filter_at(eegt,vars('cluster_id'), any_vars(. %in% ci));
  for(ki in kin_inds_plot){
    tmptc = tmptc[complete.cases(tmptc[[kin_measures[ki]]]),]
  }
  tmpt <- tmptc;
  for(ki in kin_inds_plot){
    mod_char = paste("{outcome} ~ 1 + speed_cond_num + ",kin_measures[ki]," + (1|subj_char)");
    tbl <- tibble(outcome=eeg_measures[eeg_inds_plot]) %>%
      rowwise() %>%
      mutate(
        tbl =
          lmer(str_glue(mod_char), data=tmpt) %>%
          tbl_regression(tidy_fun = broom.mixed::tidy,
                         pvalue_fun = purrr::partial(style_pvalue, digits = 2),
                         intercept=TRUE) %>%
          add_global_p() %>%
          add_q() %>%
          list()
        ) %>%
      pull(tbl) %>%
      tbl_merge(tab_spanner=eeg_title_chars[eeg_inds_plot])

    #- HTML TAG
    # print(htmltools:tags(HTML(markdown::mark(text=paste0("\n\n### ", ci,",", ki, "\n")))))
    cat(paste0("\n\n### ", ci,",", kin_measures[ki], "\n"))
    #%% PRINT TABLE
    t_out <- as_gt(tbl) %>%
      gt::tab_header(title=c("Changes in ",kin_measures[ki],"for Cluster: ",ci)) %>%
      gt::tab_options(table.layout = "fixed") %>%
      gt::as_raw_html()
    print(t_out)

    rsq <- tibble(outcome=eeg_measures[eeg_inds_plot]) %>%
    rowwise() %>%
    mutate(
        mod =
          lmer(str_glue(mod_char), data=tmpt) %>%
          r.squaredGLMM(),
          print(str_glue("{outcome}\n R2m: {round(mod[1],4)},\tR2c: {round(mod[2],4)}\n\n"))
    )

    #%% VISUALIZATION OF MODELS
    theme_set(theme_classic()) # This sets the default ggplot theme
    fitfit <- tibble(outcome=eeg_measures[eeg_inds_plot]) %>%
      rowwise() %>%
      mutate(
          mod =
            lmer(str_glue(mod_char), data=tmpt)%>%
            list()
      )
    # color_pal_subj = as.vector(createPalette(length(levels(tmpt$subj_char)),c("#4f4f4f","#5f5f5f")));

    for(modi in 1:length(eeg_measures[eeg_inds_plot])){
      eegi = eeg_inds_plot[modi]
      #%% MODEL VALIDATIONS
      cat(paste0("\n\n#### ",eeg_title_chars[modi]," model validations\n"))
      tmpt <- tmpt %>%
        mutate(fit.m = predict(fitfit$mod[[modi]], re.form = NA),
               fit.c = predict(fitfit$mod[[modi]], re.form = NULL))
      print(plot_model(fitfit$mod[[modi]], type = 'diag'))
      #%% SCATTER3D IMPLEMENTATION
      cat(paste0("\n\n#### ",eeg_title_chars[modi]," plot\n"))
      xc = "speed_cond_num";
      yc = kin_measures[ki];
      fix_effs <- fixef(fitfit$mod[[modi]])
      ran_effs <- ranef(fitfit$mod[[modi]])$subj_char
      #- plot
      subjs = unique(tmpt[[xc]])
      for(i in 1:length(subjs)){
        ts <- filter_at(tmpt,vars(xc),all_vars(. == subjs[i]))
        if(i == 1){
          scatter <- scatterplot3d(ts[[yc]], ts[[xc]], ts[[eeg_measures[eegi]]],
            main = paste0(eeg_title_chars[modi],"plot"),
            xlab = kin_title_chars[ki],
            ylab = "Speed (m/s)",
            zlab = eeg_title_chars[eegi],
            xlim = c(min(tmpt[[yc]]),max(tmpt[[yc]])),
            ylim = c(min(tmpt[[xc]]),max(tmpt[[xc]])),
            zlim = c(min(tmpt[[eeg_measures[eegi]]]),max(tmpt[[eeg_measures[eegi]]])),
            pch = 16,
            color = color_pal_subj[i],
            angle = 30) # adjust the viewing angle
        } else {
        scatter$points3d(ts[[yc]], ts[[xc]], ts[[eeg_measures[eegi]]] ,
            main = paste0(eeg_title_chars[modi],"plot"),
            col = color_pal_subj[i],
            pch=16)
        }
      }
      # scatter$plane3d(Intercept = as.numeric(fix_effs[1]),
      #                 x.coef = as.numeric(fix_effs[3]),
      #                 y.coef = as.numeric(fix_effs[2]),
      #                 draw_polygon = TRUE,
      #                 draw_lines = FALSE,
      #                 polygon_args = list(col = rgb(0.8,0.8,0.8,0.5)))
      a <- fix_effs[xc]
      b <- fix_effs[yc]
      d <- fix_effs["(Intercept)"]
      # Create the plane's z-values using the equation of the plane
      plane_z <- function(y,x){a*x+b*y+d}
      scatter$contour3d(plane_z,y.count=10,
                        x.count=10,
                        y.resolution = 50,
                        x.resolution=50,
                        lty="24",
                        type="l")
      # print(scatter)
      # l[[cnt]] <- tagList(HTML(markdown::mark(text=paste0("\n\n#### ", cnt, "\n"))),scatter)
    }
    
  }
}
```