---
title: "Linear Mixed Effects Models for Kin & Speed Predictors for EEG"
author: "Jacob Salminen"
date: \`r format(Sys.Date(),"%d-%m-%Y")`\
output:
  html_document:
    theme: flatly
    toc: true
    toc_depth: 6
    toc_float:
      collapsed: true
      smooth_scroll: true
    df_print: paged
    self_contained: yes
---

```{r setup, include=FALSE}
# ERROR. png() device not found bug try: dev.off()
# ERROR. png() device not found fixed by changing cell names to a simple "windows friendlY" format so that knitr could save files.
knitr::opts_chunk$set(echo = TRUE)
```

# Packages & Setup
```{r}
# install.packages(c("tidyverse","purrr","R.matlab","readxl","dplyr"))
#%% PACKAGES FOR STATS
library(readxl);
library(purrr);
library(tidyverse);
library(tibble);
library(knitr);
library(gtsummary);
library(kableExtra);
library(lme4);
library(MuMIn);
library(car);
library(effectsize)
library(sjPlot);
#%% PACKAGES FOR PLOTS & HTML HANDLING
# library(effects);
# library(sjPlot);
# library(plotly);
# library(webshot)
# library(reshape2);
# library(htmltools)
# library(Polychrome);
# library(htmlwidgets);
# library(shiny)
# library(webshot)
library(scatterplot3d)
library(RColorBrewer)
library(openxlsx)
```

## GTSUMMARY THEME
``` {r}
gtsummary::set_gtsummary_theme(theme_gtsummary_journal("jama"))
#--
ispc <- function() {
  sys_name <- Sys.info()["sysname"]
  if (sys_name == "Windows") {
    return(TRUE)
  } else {
    return(FALSE)
  }
}
```
# Set Parameters 
```{r} 
#%% CLUSTERS TO PLOT
# clusters = c(3,4,6,7,8,9,10,13) # 10172024_MIM_YAOAN89_antsnorm_dipfix_iccREMG0p4_powpow0p3_skull0p01_15mmrej_speed
clusters = c(3,4,5,7,10,12,13) # RSup/RSM, PreC, LSM, Mid Cing, LSup, LPPA, RPPA
# #%% KIN PARAMS
# kin_measures = c('mu_ml_exc_mm_gc','mu_stance_dur','mu_step_dur',
#                  'std_ml_exc_mm_gc','std_stance_dur','std_step_dur');
# kin_title_chars = c("ml exc. Mean","stance dur. Mean","step dur. Mean",
#                     "ml exc. Std. Dev.","stance dur. Std. Dev.","step dur. Std. Dev.")
# 
# #%% EEG PARAMS 
# eeg_measures = c('std_avg_theta','std_avg_alpha','std_avg_beta',
#                      'mu_avg_theta','mu_avg_alpha','mu_avg_beta');
# eeg_title_chars = c("**BETA** Std. Dev.","**ALPHA** Std. Dev.","**BETA** Std. Dev.",
#                          "**BETA** Mean","**ALPHA** Mean","**BETA** Mean");
#%% KIN PARAMS
# kin_measures = c('mu_ml_exc_mm_gc','mu_step_dur');
# kin_title_chars = c("ml exc. Mean","step dur. Mean")
kin_measures = c('std_ml_exc_mm_gc','std_step_dur',
                 'mu_ml_exc_mm_gc','mu_step_dur');
kin_title_chars = c("ML Exc. Std. Dev","Step Dur. Std. Dev",
                    "ML Exc. Mean","Step Dur. Mean")

#%% EEG PARAMS
# eeg_measures = c('mu_avg_theta','mu_avg_alpha','mu_avg_beta');
# eeg_title_chars = c("**THETA** Mean","**ALPHA** Mean","**BETA** Mean");
eeg_measures = c('mu_avg_theta','mu_avg_alpha','mu_avg_beta',
                 'std_avg_theta','std_avg_alpha','std_avg_beta');
eeg_title_chars = c("**THETA** Mean","**ALPHA** Mean","**BETA** Mean",
                    "**THETA** Std. Dev.","**ALPHA** Std. Dev.","**BETA** Std. Dev.");
# eeg_measures = c('mu_ap_exponent','mu_ap_offset');
# eeg_title_chars = c("Aperiodic Exp.","Aperiodic Off.");
```

# Load Data 
```{r loaddata}
# excel_dir <-"/jsalminen/GitHub/MIND_IN_MOTION_PRJ/_data/MIM_dataset/_studies/10172024_MIM_YAOAN89_antsnorm_dipfix_iccREMG0p4_powpow0p3_skull0p01_15mmrej_speed/__iclabel_cluster_kmeansalt_rb5/icrej_5/11/kin_eeg_step_to_step/sbs_eeg_psd_meandesignb.xlsx"
# excel_dir <- "/jsalminen/GitHub/MIND_IN_MOTION_PRJ/_data/MIM_dataset/_studies/01192025_mim_yaoa_nopowpow_crit_speed/__iclabel_cluster_kmeansalt_rb3/icrej_5/11/kin_eeg_step_to_step/sbs_eeg_psd_slidingb5.xlsx"
# excel_dir <- "/jsalminen/GitHub/MIND_IN_MOTION_PRJ/_data/MIM_dataset/_studies/01192025_mim_yaoa_nopowp ow_crit_speed/__iclabel_cluster_kmeansalt_rb3/icrej_5/11/kin_eeg_step_to_step/sbs_eeg_psd_meandesignb_nfslidingb5.xlsx"

# fext = "meandesignb";
# fext = "meandesignb_nfslidingb5";
# fext = "slidingb5";
# fext = "slidingb6";
# fext = "new_slidingb6";
# fext = "new_meandesignb_nfslidingb6";
# fext = "new_meancondb_nfslidingb6";
fext = "new_perstridefb_nfslidingb6";
excel_dir <- paste0("/jsalminen/GitHub/MIND_IN_MOTION_PRJ/_data/MIM_dataset/_studies/01192025_mim_yaoa_nopowpow_crit_speed/__iclabel_cluster_kmeansalt_rb3/icrej_5/11/kin_eeg_step_to_step/sbs_eeg_psd_",fext,".xlsx")

if(ispc()){
  excel_dir <- paste0("M:",excel_dir)
}else{
  excel_dir <- paste0("/blue/dferris",excel_dir);
}

orig_eegt <- read_excel(excel_dir,sheet="Sheet1")
#%% SUBSET
# orig_eegt <- orig_eegt %>%
#   select(subj_char,cond_char,speed_n,group_n,group_name,group_char,cluster_n,model_n,model_char,stride_n,
#          avg_theta,avg_beta,avg_alpha,
#          avg_theta_post,avg_alpha_post,avg_beta_post,
#          avg_theta_pre,avg_alpha_pre,avg_beta_pre,
#          ml_exc_mm,ap_exc_mm,ud_exc_mm,ml_exc_mm_gc,ap_exc_mm_gc,ud_exc_mm_gc,
#          stance_dur,step_dur,single_sup_dur,double_sup_dur);
#%% SUBSET
orig_eegt <- orig_eegt %>%
  select(subj_char,cond_char,speed_n,group_n,group_name,group_char,cluster_n,model_n,model_char,mu_stride_n,
         std_avg_theta,std_avg_beta,std_avg_alpha,
         std_ml_exc_mm_gc,std_ap_exc_mm_gc,std_ud_exc_mm_gc,
         std_stance_dur,std_step_dur,std_single_sup_dur,std_double_sup_dur,
         mu_avg_theta,mu_avg_beta,mu_avg_alpha,
         mu_ml_exc_mm_gc,mu_ap_exc_mm_gc,mu_ud_exc_mm_gc,
         mu_stance_dur,mu_step_dur,mu_single_sup_dur,mu_double_sup_dur,
         );

```

# Format Table
```{r}
eegt <- orig_eegt;
#%% SELECT SPEEDS
eegt <- filter_at(eegt,vars('cond_char'), any_vars(. %in% c('0p25','0p5','0p75','1p0')))
flat_speeds = unique(eegt$cond_char)

#%% MUTATE VARIABLES
eegt$speed_cond_num <- as.numeric(eegt$speed_n); #as.numeric(eegt$cond_char);
eegt <- mutate(eegt,across(c('subj_char'), factor))
eegt <- mutate(eegt,across(c('group_char'), factor))
eegt <- mutate(eegt,across(c('group_name'), factor))
eegt <- mutate(eegt,across(c('model_char'), factor))

#%% COLORS
color_pal_subj = brewer.pal(9,'PuBuGn')
color_pal_subj = color_pal_subj[5:9];

#%% TBL VALUES
tbl_clusterS = unique(eegt$cluster_n);
tbl_subjects = unique(eegt$subj_char);
tbl_groups = unique(eegt$group_char);

#%% DISPLAY TBL
head(eegt)
dtbl <- eegt;
rm(eegt)
```

# Table Manipulations
```{r tblmanip}
#%% Calculate mean and standard deviation by group
# dtbl <- orig_eegt
# dtbl <- orig_eegt %>%
#   select(subj_char,cond_char,speed_n,model_n,group_char,cluster_n,
#          avg_theta_post,avg_alpha_post,avg_beta_post,
#          ml_exc_mm,ap_exc_mm,ud_exc_mm,ml_exc_mm_gc,ap_exc_mm_gc,ud_exc_mm_gc,
#          step_dur,single_sup_dur,double_sup_dur,stance_dur);
#-- (01/30/2025)
dtbl <- orig_eegt %>%
  select(subj_char,cond_char,speed_n,group_char,cluster_n,model_n,
     std_avg_theta,std_avg_beta,std_avg_alpha,
     std_ml_exc_mm_gc,std_ap_exc_mm_gc,std_ud_exc_mm_gc,
     std_stance_dur,std_step_dur,std_single_sup_dur,std_double_sup_dur,
     mu_avg_theta,mu_avg_beta,mu_avg_alpha,
     mu_ml_exc_mm_gc,mu_ap_exc_mm_gc,mu_ud_exc_mm_gc,
     mu_stance_dur,mu_step_dur,mu_single_sup_dur,mu_double_sup_dur,
     );
dtbl <- dtbl %>%
  group_by(subj_char,cond_char,speed_n,model_n,group_char,cluster_n) %>%
  summarise_all(list("mean","sd"))
dtbl <- transform(dtbl,cov_avg_theta_post = mu_avg_theta_fn2/mu_avg_theta_fn1)
dtbl <- transform(dtbl,cov_avg_beta_post = mu_avg_beta_fn2/mu_avg_beta_fn1)
dtbl <- transform(dtbl,cov_avg_alpha_post = mu_avg_alpha_fn2/mu_avg_alpha_fn1)
dtbl <- transform(dtbl,cov_ml_exc = mu_ml_exc_mm_gc_fn2/mu_ml_exc_mm_gc_fn1)
dtbl <- transform(dtbl,cov_step_dur = mu_step_dur_fn2/mu_step_dur_fn1)
dtbl <- transform(dtbl,cov_stance_dur = mu_stance_dur_fn2/mu_stance_dur_fn1)

#%% MUTATE VARIABLES
dtbl$speed_cond_num <- as.numeric(dtbl$speed_n); #as.numeric(dtbl$cond_char);
dtbl <- mutate(dtbl,across(c('subj_char'), factor))
dtbl <- mutate(dtbl,across(c('group_char'), factor))
dtbl <- mutate(dtbl,across(c('model_n'), factor))

color_pal_subj = brewer.pal(9,'PuBuGn')
color_pal_subj = color_pal_subj[5:9];

#%% TBL VALUES
tbl_clusterS = unique(dtbl$cluster_n);
tbl_subjects = unique(dtbl$subj_char);
tbl_groups = unique(dtbl$group_char);

#%% KIN PARAMS
# kin_measures = c('ml_exc_mm_gc_fn1','ml_exc_mm_gc_fn2','step_dur_fn2','stance_dur_fn2');
# kin_title_chars = c("ml exc. mean","ml exc. std","step dur. std","stance dur. std")
# kin_measures = c('cov_ml_exc','cov_step_dur','cov_stance_dur');
# kin_title_chars = c("ml exc. COV","step dur. COV","stance dur. COV")
kin_measures = c('mu_ml_exc_mm_gc_fn2','mu_step_dur_fn2');
kin_title_chars = c("ml exc. Std Dev.","step dur. Std Dev.")

#%% EEG PARAMS
#-- EEG PARAMS (fn1 = mean, fn2 = sd)
# eeg_measures = c('mu_avg_theta_fn2','mu_avg_beta_fn2','mu_avg_alpha_fn2',
#                      'mu_avg_theta_fn1','mu_avg_beta_fn1','mu_avg_alpha_fn1');
# eeg_title_chars = c("**THETA** Std. Dev.","**BETA** Std. Dev.","**ALPHA** Std. Dev.",
#                     "**THETA** Mean","**BETA** Mean","**ALPHA** Mean");
eeg_measures = c('std_avg_theta_fn2','std_avg_beta_fn2','std_avg_alpha_fn2',
                     'std_avg_theta_fn1','std_avg_beta_fn1','std_avg_alpha_fn1');
eeg_title_chars = c("**THETA** Std. Dev.","**BETA** Std. Dev.","**ALPHA** Std. Dev.",
                    "**THETA** Mean","**BETA** Mean","**ALPHA** Mean");
#-- CLUSTERS TO PLOT
# clusters = c(3,4,6,7,8,9,10,13) # 10172024_MIM_YAOAN89_antsnorm_dipfix_iccREMG0p4_powpow0p3_skull0p01_15mmrej_speed
clusters = c(3,4,5,7,10,12,13) # RSup/RSM, PreC, LSM, Mid Cing, LSup, LPPA, RPPA

#%% MUTATE VARIABLES
fext = paste0("meansd_",fext);
dtbl$speed_cond_num <- as.numeric(dtbl$speed_n);
write.xlsx(dtbl,paste0("01302025_lme_eeg_kin_",fext,"_tbl.xlsx"))
```

# Functions
```{r}
calc_cohensf2 <- function(mod_main,mod_alt){
  r2_out = r.squaredGLMM(mod_main);
  r2_outalt = r.squaredGLMM(mod_alt);
  r2m = r2_out[1] # input your R2
  f2m = r2m/(1 - r2m)
  r2c = r2_out[2] # input your R2
  f2c = r2c/(1 - r2c)
  f2m = (r2_out[1]-r2_outalt[1])/(1-r2_out[1]);
  f2c = (r2_out[2]-r2_outalt[2])/(1-r2_out[2]);
  print(str_glue("r2m: {round(r2m,4)},\tr2c: {round(r2c,4)}\n\n"))
  print(str_glue("f2m: {round(f2m,4)},\tf2c: {round(f2c,4)}\n\n"))
  vals = data.frame(r2m, r2c, f2m, f2c);
  return (vals)
}

#%% EXCEL DATAFRAME
excel_df <- data.frame(cluster_num=double(),
                        group_char=character(),
                        model_char=character(),
                        kinematic_char=character(),
                        freq_band_char=character(),
                        coeff_int=double(),
                        coeff_sp=double(),
                        coeff_kin=double(),
                        coeff_intact=double(),
                        pval_int=double(),
                        pval_sp=double(),
                        pval_kin=double(),
                        pval_intact=double(),
                        r2_m_int=double(),
                        r2_c_int=double(),
                        f2_m_int=double(),
                        f2_c_int=double(),
                        fsq_sp=double(),
                        fsq_kin=double(),
                        fsq_intact=double(),
                        etasq_sp=double(),
                        etasq_kin=double(),
                        etasq_intact=double(),
                        ran_effs_char=character(),
                        ran_effs_n=character())
```

# KIN INTERACTION) LME Kin ~ 1+speed+group+speed:group
```{r speedkininterall, echo=FALSE, message=FALSE, results="asis"}
theme_set(theme_classic()) # This sets the default ggplot theme
#%% LOOP VARS
cis <- rep(NA,length(clusters)*length(kin_measures))
kis <- rep(NA,length(clusters)*length(kin_measures))
cnt = 1;
for (i in 1:length(clusters)) {
  for(j in 1:length(kin_measures)){
    cis[cnt] = i;
    kis[cnt] = j;
    cnt = cnt + 1;
  }
}

for (i in 1:length(cis)){
  #%% SET LOOP PARAMS
  ci = clusters[cis[i]]; 
  ki = kin_measures[kis[i]];
  
  #%% HTML TAG
  cat(paste0("\n\n## ", ci,',', ki,"\n"))
  
  #%% SUBSET BY CLUSTER
  tmpt <- filter_at(dtbl,vars('cluster_n'), any_vars(. %in% ci));
  #-- remove NAN cases
  tmpt = tmpt[complete.cases(tmpt[[ki]]),];
  
  #%% REMOVE KIN_MEASURES < 0.005 & THAT ARE GREATER THAN OR LESS THAN 3STD FROM MEAN
  # #- bad strides cutoff
  # sub_s = tmpt[[ki]] < 0.005
  # #(12/18/2024) JS, changing from 0.01 to 0.005 to see if I can retain some more data without it looking funky
  # tmpt = tmpt[sub_s==FALSE, ]
  # #- mean & std cutoff
  # muc = mean(tmpt[[ki]])
  # stdc = sd(tmpt[[ki]])
  # inds_keep = tmpt[[ki]] > muc-3*stdc & tmpt[[ki]] < muc+3*stdc
  # tmpt = tmpt[inds_keep,]
  
  #%% COMPUTE LME MODEL
  mod_char = paste(ki," ~ 1 + speed_cond_num + group_char + speed_cond_num:group_char + (1|subj_char)");
  mod <- lme4::lmer(str_glue(mod_char), data=tmpt);
  tbl <- mod %>%
    tbl_regression(tidy_fun = broom.mixed::tidy,
                   pvalue_fun = purrr::partial(style_pvalue, digits = 2),
                     intercept=TRUE) %>%
    add_global_p() %>%
    add_q()
  
  #%% PRINT TABLE
  t_out <- as_gt(tbl) %>%
    gt::tab_header(title=c("Changes in ",ki,"for Cluster: ",ci)) %>%
    gt::tab_options(table.layout = "fixed") %>%
    gt::as_raw_html()
  print(t_out)
  #-- extract fixed & random effects coeffs
  anv_vals <- car::Anova(mod,type=3)
  fix_effs <- fixef(mod)
  ran_effs <- ranef(mod)$subj_char
  print(anv_vals)
  
  #%% R-SQUARED VALUE
  # r.squaredGLMM() %>%
  #   print(str_glue("{outcome}\n R2m: {round(mod[1],4)},\tR2c: {round(mod[2],4)}\n\n"))
  
  #%% EFFECT SIZES
  cat(paste0("\n\n### model effect sizes\n"))
  #-- Intercept Model for Cohen's f^2
  print('intercept model\n');
  mod_char_int = paste(ki," ~ 1 + (1|subj_char)");
  tmp_mod = lme4::lmer(str_glue(mod_char_int), data=tmpt)
  cf_alt = calc_cohensf2(mod, tmp_mod)
  
  #-- calculate effect sizes using r-package 
  etasq_res <- effectsize::eta_squared(mod, partial = TRUE)
  cohens_fsq_res <- effectsize::cohens_f_squared(mod, partial = TRUE)
  
  #%% EXCEL PRINTS
  new_row = data.frame(cluster_num=ci,
                      group_char=c('all'),
                      model_char=c('group_speed_intact'),
                      kinematic_char=c(ki),
                      freq_band_char=c('none'),
                      coeff_int=mod@beta[1],
                      coeff_sp=mod@beta[2],
                      coeff_kin=mod@beta[3],
                      coeff_intact=mod@beta[4],
                      pval_int=anv_vals$`Pr(>Chisq)`[1],
                      pval_sp=anv_vals$`Pr(>Chisq)`[2],
                      pval_kin=anv_vals$`Pr(>Chisq)`[3],
                      pval_intact=anv_vals$`Pr(>Chisq)`[4],
                      r2_m_int=cf_alt$r2m,
                      r2_c_int=cf_alt$r2c,
                      f2_m_int=cf_alt$f2m,
                      f2_c_int=cf_alt$f2c,
                      fsq_sp=cohens_fsq_res$Cohens_f2_partial[1],
                      fsq_kin=cohens_fsq_res$Cohens_f2_partial[2],
                      fsq_intact=cohens_fsq_res$Cohens_f2_partial[3],
                      etasq_sp=etasq_res$Eta2_partial[1],
                      etasq_kin=etasq_res$Eta2_partial[2],
                      etasq_intact=etasq_res$Eta2_partial[3],
                      ran_effs_char=paste(unlist(row.names(ran_effs)),collapse=','),
                      ran_effs_n=paste(unlist(ran_effs$`(Intercept)`),collapse=','))
  excel_df <- rbind(excel_df,new_row)
  
  #%% MODEL VALIDATION PLOTS
  cat(paste0("\n\n### model validations\n"))
  print(plot_model(mod, type = 'diag'))
  cat("\n")
  tmpt$fit.m <- predict(mod, re.form = NA)
  tmpt$fit.c <- predict(mod, re.form = NULL)
  
  #%% SCATTER3D IMPLEMENTATION
  print(
      tmpt %>%
        ggplot() +
        geom_jitter(aes(x = speed_cond_num, y = .data[[ki]], color = subj_char), pch=20, size=10, alpha=0.2) +
        geom_line(aes(x= speed_cond_num, y=fit.c, group = subj_char),linetype = "dashed", linewidth = .5) +
        geom_line(aes(x= speed_cond_num, y=fit.m), linewidth = 2)+
        facet_wrap(~group_char) + 
        ggtitle(kin_measures[kis[i]]) +
        xlab("Treadmill Speed (m/s)") +
        ylab(kin_title_chars[kis[i]]) +
        guides(group="none")
    )
}
```

<!-- # KIN GROUP MAIN) LME Kin ~ 1+speed+group -->
<!-- ```{r kinspeedgroupall, echo=FALSE, message=FALSE, results="asis"} -->
<!-- # theme_set(theme_classic()) # This sets the default ggplot theme -->
<!-- #%% LOOP VARS -->
<!-- cis <- rep(NA,length(clusters)*length(kin_measures)) -->
<!-- kis <- rep(NA,length(clusters)*length(kin_measures)) -->
<!-- cnt = 1; -->
<!-- for (i in 1:length(clusters)) { -->
<!--   for(j in 1:length(kin_measures)){ -->
<!--     cis[cnt] = i; -->
<!--     kis[cnt] = j; -->
<!--     cnt = cnt + 1; -->
<!--   } -->
<!-- } -->

<!-- for (i in 1:length(cis)){ -->
<!--   #%% SET LOOP PARAMS -->
<!--   ci = clusters[cis[i]]; -->
<!--   ki = kin_measures[kis[i]]; -->

<!--   #%% HTML TAG -->
<!--   cat(paste0("\n\n## ", ci,',', ki,"\n")) -->

<!--   #%% SUBSET BY CLUSTER -->
<!--   tmpt <- filter_at(dtbl,vars('cluster_n'), any_vars(. %in% ci)); -->
<!--   #-- remove NAN cases -->
<!--   tmpt = tmpt[complete.cases(tmpt[[ki]]),]; -->

<!--   #%% REMOVE KIN_MEASURES < 0.005 & THAT ARE GREATER THAN OR LESS THAN 3STD FROM MEAN -->
<!--   # #- remove NAN cases -->
<!--   # tmpt = tmpt[complete.cases(tmpt[[ki]]),]; -->
<!--   # #- bad strides cutoff -->
<!--   # sub_s = tmpt[[ki]] < 0.005 -->
<!--   # #(12/18/2024) JS, changing from 0.01 to 0.005 to see if I can retain some more data without it looking funky -->
<!--   # tmpt = tmpt[sub_s==FALSE, ] -->
<!--   # #- mean & std cutoff -->
<!--   # muc = mean(tmpt[[ki]]) -->
<!--   # stdc = sd(tmpt[[ki]]) -->
<!--   # inds_keep = tmpt[[ki]] > muc-3*stdc & tmpt[[ki]] < muc+3*stdc -->
<!--   # tmpt = tmpt[inds_keep,] -->

<!--   #%% COMPUTE LME MODEL -->
<!--   mod_char = paste(ki," ~ 1 + speed_cond_num + group_char + (1|subj_char)"); -->
<!--   mod <- lme4::lmer(str_glue(mod_char), data=tmpt); -->
<!--   tbl <- mod %>% -->
<!--     tbl_regression(tidy_fun = broom.mixed::tidy, -->
<!--                    pvalue_fun = purrr::partial(style_pvalue, digits = 2), -->
<!--                      intercept=TRUE) %>% -->
<!--     add_global_p() %>% -->
<!--     add_q() -->

<!--   #%% PRINT TABLE -->
<!--   t_out <- as_gt(tbl) %>% -->
<!--     gt::tab_header(title=c("Changes in ",ki,"for Cluster: ",ci)) %>% -->
<!--     gt::tab_options(table.layout = "fixed") %>% -->
<!--     gt::as_raw_html() -->
<!--   print(t_out) -->
<!--   #-- extract fixed & random effects coeffs -->
<!--   anv_vals <- car::Anova(mod,type=3) -->
<!--   fix_effs <- fixef(mod) -->
<!--   ran_effs <- ranef(mod)$subj_char -->
<!--   print(anv_vals) -->

<!--   #%% R-SQUARED VALUE -->
<!--   # r.squaredGLMM() %>% -->
<!--   #   print(str_glue("{outcome}\n R2m: {round(mod[1],4)},\tR2c: {round(mod[2],4)}\n\n")) -->

<!--   #%% EFFECT SIZES -->
<!--   cat(paste0("\n\n### model effect sizes\n")) -->
<!--   #-- Intercept Model for Cohen's f^2 -->
<!--   print('intercept model\n'); -->
<!--   mod_char_int = paste(ki," ~ 1 + (1|subj_char)"); -->
<!--   tmp_mod = lme4::lmer(str_glue(mod_char_int), data=tmpt) -->
<!--   cf_alt = calc_cohensf2(mod, tmp_mod) -->

<!--   #-- calculate effect sizes using r-package -->
<!--   etasq_res <- effectsize::eta_squared(mod, partial = TRUE) -->
<!--   cohens_fsq_res <- effectsize::cohens_f_squared(mod, partial = TRUE) -->

<!--   #%% EXCEL PRINTS -->
<!--   new_row = data.frame(cluster_num=ci, -->
<!--                       group_char=c('all'), -->
<!--                       model_char=c('group_speed_main'), -->
<!--                       kinematic_char=c(ki), -->
<!--                       freq_band_char=c('none'), -->
<!--                       coeff_int=mod@beta[1], -->
<!--                       coeff_sp=mod@beta[2], -->
<!--                       coeff_kin=mod@beta[3], -->
<!--                       coeff_intact=mod@beta[4], -->
<!--                       pval_int=anv_vals$`Pr(>Chisq)`[1], -->
<!--                       pval_sp=anv_vals$`Pr(>Chisq)`[2], -->
<!--                       pval_kin=anv_vals$`Pr(>Chisq)`[3], -->
<!--                       pval_intact=anv_vals$`Pr(>Chisq)`[4], -->
<!--                       r2_m_int=cf_alt$r2m, -->
<!--                       r2_c_int=cf_alt$r2c, -->
<!--                       f2_m_int=cf_alt$f2m, -->
<!--                       f2_c_int=cf_alt$f2c, -->
<!--                       fsq_sp=cohens_fsq_res$Cohens_f2_partial[1], -->
<!--                       fsq_kin=cohens_fsq_res$Cohens_f2_partial[2], -->
<!--                       fsq_intact=cohens_fsq_res$Cohens_f2_partial[3], -->
<!--                       etasq_sp=etasq_res$Eta2_partial[1], -->
<!--                       etasq_kin=etasq_res$Eta2_partial[2], -->
<!--                       etasq_intact=etasq_res$Eta2_partial[3], -->
<!--                       ran_effs_char=paste(unlist(row.names(ran_effs)),collapse=','), -->
<!--                       ran_effs_n=paste(unlist(ran_effs$`(Intercept)`),collapse=',')) -->
<!--   excel_df <- rbind(excel_df,new_row) -->

<!--   #%% MODEL VALIDATION PLOTS -->
<!--   cat(paste0("\n\n### model validations\n")) -->
<!--   # print(plot_model(mod, type = 'diag')) -->
<!--   cat("\n") -->
<!--   tmpt$fit.m <- predict(mod, re.form = NA) -->
<!--   tmpt$fit.c <- predict(mod, re.form = NULL) -->

<!--   #%% SCATTER3D IMPLEMENTATION -->
<!--   print( -->
<!--     tmpt %>% -->
<!--       ggplot() + -->
<!--       geom_jitter(aes(x = speed_cond_num, y = .data[[ki]], color = subj_char), pch=20, size=10, alpha=0.2) + -->
<!--       geom_line(aes(x= speed_cond_num, y=fit.c, group = subj_char),linetype = "dashed", linewidth = .5) + -->
<!--       geom_line(aes(x= speed_cond_num, y=fit.m), linewidth = 2)+ -->
<!--       facet_wrap(~group_char) + -->
<!--       ggtitle(kin_measures[kis[i]])+ -->
<!--       xlab("Treadmill Speed (m/s)") + -->
<!--       ylab(kin_title_chars[kis[i]]) + -->
<!--       guides(group="none") -->
<!--     ) -->
<!-- } -->
<!-- #%% SAVE WIDGET AS AN INDEPENDENT HTML FILE -->
<!-- # pwd <- getwd() -->
<!-- # write.xlsx(excel_df,file.path(pwd,"speed_kin_lme_behavior_meansd.xlsx")) -->
<!-- ``` -->

# EEG-SPEED ALL) LME EEG ~ 1+speed
```{r eegspeedall, echo=FALSE, message=FALSE, results="asis"}
theme_set(theme_classic()) # This sets the default ggplot theme
#%% LOOP VARS
cis <- rep(NA,length(clusters)*length(eeg_measures))
eis <- rep(NA,length(clusters)*length(eeg_measures))
cnt = 1;
for (i in 1:length(clusters)) {
  for(k in 1:length(eeg_measures)){
    cis[cnt] = i;
    eis[cnt] = k;
    cnt = cnt + 1;
  }
}

for (i in 1:length(cis)){
  #%% SET LOOP PARAMS
  ci = clusters[cis[i]];
  ei = eeg_measures[eis[i]];
  
  #%% HTML TAG
  cat(paste0("\n\n## ", ci,',',ei,"\n"))
  
  #%% SUBSET BY CLUSTER
  tmpt <- filter_at(dtbl,vars('cluster_n'), any_vars(. %in% ci));
  #-- remove NAN cases
  # tmpt = tmpt[complete.cases(tmpt[[ki]]),];
  
  #%% THAT ARE GREATER THAN OR LESS THAN 3STD FROM MEAN
  #- mean & std cutoff
  # muc = mean(tmpt[[ei]])
  # stdc = sd(tmpt[[ei]])
  # inds_keep = tmpt[[ei]] > muc-4*stdc & tmpt[[ei]] < muc+4*stdc
  # tmpt = tmpt[inds_keep,]
  
  #%% COMPUTE LME MODEL
  mod_char = paste(ei," ~ 1 + speed_cond_num + (1|subj_char)");
  mod <- lme4::lmer(str_glue(mod_char), data=tmpt);
  tbl <- mod %>%
    tbl_regression(tidy_fun = broom.mixed::tidy,
                   pvalue_fun = purrr::partial(style_pvalue, digits = 2),
                     intercept=TRUE) %>%
    add_global_p() %>%
    add_q()
  
  #%% PRINT TABLE
  t_out <- as_gt(tbl) %>%
    gt::tab_header(title=c("Changes in ",ei,"for Cluster: ",ci)) %>%
    gt::tab_options(table.layout = "fixed") %>%
    gt::as_raw_html()
  print(t_out)
  #-- extract fixed & random effects coeffs
  anv_vals <- car::Anova(mod,type=3)
  fix_effs <- fixef(mod)
  ran_effs <- ranef(mod)$subj_char
  print(anv_vals);
  
  #%% R-SQUARED VALUE
  # r.squaredGLMM() %>%
  #   print(str_glue("{outcome}\n R2m: {round(mod[1],4)},\tR2c: {round(mod[2],4)}\n\n"))
  
  #%% EFFECT SIZES
  cat(paste0("\n\n### model effect sizes\n"))
  #-- Intercept Model for Cohen's f^2
  print('intercept model\n');
  mod_char_int = paste(ei," ~ 1 + (1|subj_char)");
  tmp_mod = lme4::lmer(str_glue(mod_char_int), data=tmpt)
  cf_alt = calc_cohensf2(mod, tmp_mod)
  
  #-- calculate effect sizes using r-package 
  etasq_res <- effectsize::eta_squared(mod, partial = TRUE)
  cohens_fsq_res <- effectsize::cohens_f_squared(mod, partial = TRUE)
  
  #%% EXCEL PRINTS
  new_row = data.frame(cluster_num=ci,
                      group_char=c('all'),
                      model_char=c('all_speed_only'),
                      kinematic_char=c('none'),
                      freq_band_char=c(ei),
                      coeff_int=mod@beta[1],
                      coeff_sp=mod@beta[2],
                      coeff_kin=mod@beta[3],
                      coeff_intact=mod@beta[4],
                      pval_int=anv_vals$`Pr(>Chisq)`[1],
                      pval_sp=anv_vals$`Pr(>Chisq)`[2],
                      pval_kin=anv_vals$`Pr(>Chisq)`[3],
                      pval_intact=anv_vals$`Pr(>Chisq)`[4],
                      r2_m_int=cf_alt$r2m,
                      r2_c_int=cf_alt$r2c,
                      f2_m_int=cf_alt$f2m,
                      f2_c_int=cf_alt$f2c,
                      fsq_sp=cohens_fsq_res$Cohens_f2_partial[1],
                      fsq_kin=cohens_fsq_res$Cohens_f2_partial[2],
                      fsq_intact=cohens_fsq_res$Cohens_f2_partial[3],
                      etasq_sp=etasq_res$Eta2_partial[1],
                      etasq_kin=etasq_res$Eta2_partial[2],
                      etasq_intact=etasq_res$Eta2_partial[3],
                      ran_effs_char=paste(unlist(row.names(ran_effs)),collapse=','),
                      ran_effs_n=paste(unlist(ran_effs$`(Intercept)`),collapse=','))
  excel_df <- rbind(excel_df,new_row)
  
  #%% MODEL VALIDATION PLOTS
  cat(paste0("\n\n### model validations\n"))
  print(plot_model(mod, type = 'diag'))
  cat("\n")
  
  #%% MODEL VALIDATIONS
  cat(paste0("\n\n### model validations\n"))
  # print(plot_model(mod, type = 'diag'))
  cat("\n")
  tmpt$fit.m <- predict(mod, re.form = NA)
  tmpt$fit.c <- predict(mod, re.form = NULL)
  
  #%% VISUALIZATION OF MODELS
  cat(paste0("\n\n### data plot\n"))
  theme_set(theme_classic()) # This sets the default ggplot theme
  print(
    tmpt %>%
      ggplot() +
      geom_jitter(aes(x = speed_cond_num, y = .data[[ei]], color = subj_char), pch=20, size=10, alpha=0.2) +
      geom_line(aes(x= speed_cond_num, y=fit.c, group = subj_char),linetype = "dashed", linewidth = .5) +
      geom_line(aes(x= speed_cond_num, y=fit.m), linewidth = 2)+
      facet_wrap(~group_char) + 
      ggtitle(eeg_title_chars[eis[i]])+ 
      xlab("Treadmill Speed (m/s)") +
      ylab(eeg_title_chars[eis[i]]) +
      guides(group="none")
  )

}
# write.xlsx(excel_df,"lme_eeg_kin_mean_sd_stats.xlsx")
```

# EEG-SPEED GROUP) LME EEG ~ 1+speed
```{r eegspeedgroup, echo=FALSE, message=FALSE, results="asis"}
theme_set(theme_classic()) # This sets the default ggplot theme
#%% LOOP VARS
cis <- rep(NA,length(clusters)*length(eeg_measures)*length(tbl_groups))
eis <- rep(NA,length(clusters)*length(eeg_measures)*length(tbl_groups))
gis <- rep(NA,length(clusters)*length(eeg_measures)*length(tbl_groups))
cnt = 1;
for (i in 1:length(clusters)) {
  for(k in 1:length(eeg_measures)){
    for(g in 1:length(tbl_groups)){
      cis[cnt] = i;
      eis[cnt] = k;
      gis[cnt] = g;
      cnt = cnt + 1;
    }
  }
}

for (i in 1:length(cis)){
  #%% SET LOOP PARAMS
  ci = clusters[cis[i]];
  ei = eeg_measures[eis[i]];
  gi = tbl_groups[gis[i]];

  #%% HTML TAG
  cat(paste0("\n\n## ", ci,',',gi,',',ei,"\n"))

  #%% SUBSET BY CLUSTER
  tmpt <- filter_at(dtbl,vars('cluster_n'), any_vars(. %in% ci));
  #-- remove NAN cases
  # tmpt = tmpt[complete.cases(tmpt[[ki]]),];

  #%% THAT ARE GREATER THAN OR LESS THAN 3STD FROM MEAN
  #- mean & std cutoff
  # muc = mean(tmpt[[ei]])
  # stdc = sd(tmpt[[ei]])
  # inds_keep = tmpt[[ei]] > muc-4*stdc & tmpt[[ei]] < muc+4*stdc
  # tmpt = tmpt[inds_keep,]

  #%% SUBSET BY GROUP
  tmpt <- filter_at(tmpt,vars('group_char'), any_vars(. %in% gi));

  #%% COMPUTE LME MODEL
  mod_char = paste(ei," ~ 1 + speed_cond_num + (1|subj_char)");
  mod <- lme4::lmer(str_glue(mod_char), data=tmpt);
  tbl <- mod %>%
    tbl_regression(tidy_fun = broom.mixed::tidy,
                   pvalue_fun = purrr::partial(style_pvalue, digits = 2),
                     intercept=TRUE) %>%
    add_global_p() %>%
    add_q()

  #%% PRINT TABLE
  t_out <- as_gt(tbl) %>%
    gt::tab_header(title=c("Changes in ",ei,"for Cluster: ",ci)) %>%
    gt::tab_options(table.layout = "fixed") %>%
    gt::as_raw_html()
  print(t_out)
  #-- extract fixed & random effects coeffs
  anv_vals <- car::Anova(mod,type=3)
  fix_effs <- fixef(mod)
  ran_effs <- ranef(mod)$subj_char
  print(anv_vals);

  #%% R-SQUARED VALUE
  # r.squaredGLMM(mod) %>%
  #   print(str_glue("R2m: {round(R2m,4)},\tR2c: {round(R2c,4)}\n\n"))

  #%% EFFECT SIZES
  cat(paste0("\n\n### model effect sizes\n"))
  #-- Intercept Model for Cohen's f^2
  print('intercept model\n');
  mod_char_int = paste(ei," ~ 1 + (1|subj_char)");
  tmp_mod = lme4::lmer(str_glue(mod_char_int), data=tmpt)
  cf_alt = calc_cohensf2(mod, tmp_mod)

  #-- calculate effect sizes using r-package
  etasq_res <- effectsize::eta_squared(mod, partial = TRUE)
  cohens_fsq_res <- effectsize::cohens_f_squared(mod, partial = TRUE)

  #%% EXCEL PRINTS
  new_row = data.frame(cluster_num=ci,
                      group_char=c(gi),
                      model_char=c('speed_only_group'),
                      kinematic_char=c('none'),
                      freq_band_char=c(ei),
                      coeff_int=mod@beta[1],
                      coeff_sp=mod@beta[2],
                      coeff_kin=mod@beta[3],
                      coeff_intact=mod@beta[4],
                      pval_int=anv_vals$`Pr(>Chisq)`[1],
                      pval_sp=anv_vals$`Pr(>Chisq)`[2],
                      pval_kin=anv_vals$`Pr(>Chisq)`[3],
                      pval_intact=anv_vals$`Pr(>Chisq)`[4],
                      r2_m_int=cf_alt$r2m,
                      r2_c_int=cf_alt$r2c,
                      f2_m_int=cf_alt$f2m,
                      f2_c_int=cf_alt$f2c,
                      fsq_sp=cohens_fsq_res$Cohens_f2_partial[1],
                      fsq_kin=cohens_fsq_res$Cohens_f2_partial[2],
                      fsq_intact=cohens_fsq_res$Cohens_f2_partial[3],
                      etasq_sp=etasq_res$Eta2_partial[1],
                      etasq_kin=etasq_res$Eta2_partial[2],
                      etasq_intact=etasq_res$Eta2_partial[3],
                      ran_effs_char=paste(unlist(row.names(ran_effs)),collapse=','),
                      ran_effs_n=paste(unlist(ran_effs$`(Intercept)`),collapse=','))
  excel_df <- rbind(excel_df,new_row)

  #%% MODEL VALIDATIONS
  cat(paste0("\n\n### model validations\n"))
  print(plot_model(mod, type = 'diag'))
  cat("\n")
  tmpt$fit.m <- predict(mod, re.form = NA)
  tmpt$fit.c <- predict(mod, re.form = NULL)

  #%% VISUALIZATION OF MODELS
  cat(paste0("\n\n### data plot\n"))
  theme_set(theme_classic()) # This sets the default ggplot theme
  print(
    tmpt %>%
      ggplot() +
      geom_jitter(aes(x = speed_cond_num, y = .data[[ei]], color = subj_char), pch=20, size=10, alpha=0.2) +
      geom_line(aes(x= speed_cond_num, y=fit.c, group = subj_char),linetype = "dashed", linewidth = .5) +
      geom_line(aes(x= speed_cond_num, y=fit.m), linewidth = 2)+
      facet_wrap(~group_char) +
      ggtitle(eeg_title_chars[eis[i]])+
      xlab("Treadmill Speed (m/s)") +
      ylab(eeg_title_chars[eis[i]]) +
      guides(group="none")
  )
}
# write.xlsx(excel_df,"lme_eeg_kin_imufix_condb.xlsx")
```

# SPEED-GROUP INTERACTION) LME EEG ~ 1+speed+group+speed:group
```{r eegspeedgroupinter, echo=FALSE, message=FALSE, results="asis"}
theme_set(theme_classic()) # This sets the default ggplot theme
#%% LOOP VARS
cis <- rep(NA,length(clusters)*length(eeg_measures))
eis <- rep(NA,length(clusters)*length(eeg_measures))
cnt = 1;
for (i in 1:length(clusters)) {
  for(k in 1:length(eeg_measures)){
    cis[cnt] = i;
    eis[cnt] = k;
    cnt = cnt + 1;
  }
}

for (i in 1:length(cis)){
  #%% SET LOOP PARAMS
  ci = clusters[cis[i]];
  ei = eeg_measures[eis[i]];

  #%% HTML TAG
  cat(paste0("\n\n## ", ci,',',ei,"\n"))

  #%% SUBSET BY CLUSTER
  tmpt <- filter_at(dtbl,vars('cluster_n'), any_vars(. %in% ci));
  # -- remove NAN cases
  # tmpt = tmpt[complete.cases(tmpt[[ki]]),];

  #%% THAT ARE GREATER THAN OR LESS THAN 3STD FROM MEAN
  #- mean & std cutoff
  # muc = mean(tmpt[[ei]])
  # stdc = sd(tmpt[[ei]])
  # inds_keep = tmpt[[ei]] > muc-4*stdc & tmpt[[ei]] < muc+4*stdc
  # tmpt = tmpt[inds_keep,]

  #%% COMPUTE LME MODEL
  mod_char = paste(ei," ~ 1 + speed_cond_num + group_char + speed_cond_num:group_char + (1|subj_char)");
  mod <- lme4::lmer(str_glue(mod_char), data=tmpt);
  tbl <- mod %>%
    tbl_regression(tidy_fun = broom.mixed::tidy,
                   pvalue_fun = purrr::partial(style_pvalue, digits = 2),
                     intercept=TRUE) %>%
    add_global_p() %>%
    add_q()

  #%% PRINT TABLE
  t_out <- as_gt(tbl) %>%
    gt::tab_header(title=c("Changes in ",ei,"for Cluster: ",ci)) %>%
    gt::tab_options(table.layout = "fixed") %>%
    gt::as_raw_html()
  print(t_out)
  #-- extract fixed & random effects coeffs
  anv_vals <- car::Anova(mod,type=3)
  fix_effs <- fixef(mod)
  ran_effs <- ranef(mod)$subj_char
  print(anv_vals);

  #%% R-SQUARED VALUE
  # r.squaredGLMM() %>%
  #   print(str_glue("{outcome}\n R2m: {round(mod[1],4)},\tR2c: {round(mod[2],4)}\n\n"))

  #%% EFFECT SIZES
  cat(paste0("\n\n### model effect sizes\n"))
  #-- Intercept Model for Cohen's f^2
  print('intercept model\n');
  mod_char_int = paste(ei," ~ 1 + (1|subj_char)");
  tmp_mod = lme4::lmer(str_glue(mod_char_int), data=tmpt)
  cf_alt = calc_cohensf2(mod, tmp_mod)

  #-- calculate effect sizes using r-package
  etasq_res <- effectsize::eta_squared(mod, partial = TRUE)
  cohens_fsq_res <- effectsize::cohens_f_squared(mod, partial = TRUE)

  #%% EXCEL PRINTS
  new_row = data.frame(cluster_num=ci,
                      group_char=c('all'),
                      model_char=c('all_speed_grou_intact'),
                      kinematic_char=c('none'),
                      freq_band_char=c(ei),
                      coeff_int=mod@beta[1],
                      coeff_sp=mod@beta[2],
                      coeff_kin=mod@beta[3],
                      coeff_intact=mod@beta[4],
                      pval_int=anv_vals$`Pr(>Chisq)`[1],
                      pval_sp=anv_vals$`Pr(>Chisq)`[2],
                      pval_kin=anv_vals$`Pr(>Chisq)`[3],
                      pval_intact=anv_vals$`Pr(>Chisq)`[4],
                      r2_m_int=cf_alt$r2m,
                      r2_c_int=cf_alt$r2c,
                      f2_m_int=cf_alt$f2m,
                      f2_c_int=cf_alt$f2c,
                      fsq_sp=cohens_fsq_res$Cohens_f2_partial[1],
                      fsq_kin=cohens_fsq_res$Cohens_f2_partial[2],
                      fsq_intact=cohens_fsq_res$Cohens_f2_partial[3],
                      etasq_sp=etasq_res$Eta2_partial[1],
                      etasq_kin=etasq_res$Eta2_partial[2],
                      etasq_intact=etasq_res$Eta2_partial[3],
                      ran_effs_char=paste(unlist(row.names(ran_effs)),collapse=','),
                      ran_effs_n=paste(unlist(ran_effs$`(Intercept)`),collapse=','))
  excel_df <- rbind(excel_df,new_row)

  #%% MODEL VALIDATION PLOTS
  cat(paste0("\n\n### model validations\n"))
  print(plot_model(mod, type = 'diag'))
  cat("\n")

  #%% MODEL VALIDATIONS
  cat(paste0("\n\n### model validations\n"))
  # print(plot_model(mod, type = 'diag'))
  cat("\n")
  tmpt$fit.m <- predict(mod, re.form = NA)
  tmpt$fit.c <- predict(mod, re.form = NULL)

  #%% VISUALIZATION OF MODELS
  cat(paste0("\n\n### data plot\n"))
  theme_set(theme_classic()) # This sets the default ggplot theme
  print(
    tmpt %>%
      ggplot() +
      geom_jitter(aes(x = speed_cond_num, y = .data[[ei]], color = subj_char), pch=20, size=10, alpha=0.2) +
      geom_line(aes(x= speed_cond_num, y=fit.c, group = subj_char),linetype = "dashed", linewidth = .5) +
      geom_line(aes(x= speed_cond_num, y=fit.m), linewidth = 2)+
      facet_wrap(~group_char) +
      ggtitle(eeg_title_chars[eis[i]])+
      xlab("Treadmill Speed (m/s)") +
      ylab(eeg_title_chars[eis[i]]) +
      guides(group="none")
  )

}
# write.xlsx(excel_df,paste0("013022025_lme_eeg_kin_meansd_",fext,"_stats.xlsx"))
# write.xlsx(excel_df,paste0("013022025_lme_eeg_kin_",fext,"_stats.xlsx"))
```

<!-- # EEG-KIN ALL) LME EEG ~ 1+kin -->
<!-- ```{r eegkinall, echo=FALSE, message=FALSE, results="asis"} -->
<!-- theme_set(theme_classic()) # This sets the default ggplot theme -->
<!-- #%% LOOP VARS -->
<!-- cis <- rep(NA,length(clusters)*length(kin_measures)*length(eeg_measures)) -->
<!-- kis <- rep(NA,length(clusters)*length(kin_measures)*length(eeg_measures)) -->
<!-- eis <- rep(NA,length(clusters)*length(kin_measures)*length(eeg_measures)) -->
<!-- cnt = 1; -->
<!-- for (i in 1:length(clusters)) { -->
<!--   for(j in 1:length(kin_measures)){ -->
<!--     for(k in 1:length(eeg_measures)){ -->
<!--       cis[cnt] = i; -->
<!--       kis[cnt] = j; -->
<!--       eis[cnt] = k; -->
<!--       cnt = cnt + 1; -->
<!--     } -->
<!--   } -->
<!-- } -->

<!-- for (i in 1:length(cis)){ -->
<!--   #%% SET LOOP PARAMS -->
<!--   ci = clusters[cis[i]]; -->
<!--   ki = kin_measures[kis[i]]; -->
<!--   ei = eeg_measures[eis[i]]; -->

<!--   #%% HTML TAG -->
<!--   cat(paste0("\n\n## ", ci,',', ki,',',ei,"\n")) -->

<!--   #%% SUBSET BY CLUSTER -->
<!--   tmpt <- filter_at(dtbl,vars('cluster_n'), any_vars(. %in% ci)); -->

<!--   #%% REMOVE KIN_MEASURES < 0.005 & THAT ARE GREATER THAN OR LESS THAN 3STD FROM MEAN -->
<!--   # #- remove NAN cases -->
<!--   # tmpt = tmpt[complete.cases(tmpt[[ki]]),]; -->
<!--   # #- bad strides cutoff -->
<!--   # sub_s = tmpt[[ki]] < 0.005 -->
<!--   # #(12/18/2024) JS, changing from 0.01 to 0.005 to see if I can retain some more data without it looking funky -->
<!--   # tmpt = tmpt[sub_s==FALSE, ] -->
<!--   # #- mean & std cutoff -->
<!--   # muc = mean(tmpt[[ki]]) -->
<!--   # stdc = sd(tmpt[[ki]]) -->
<!--   # inds_keep = tmpt[[ki]] > muc-3*stdc & tmpt[[ki]] < muc+3*stdc -->
<!--   # tmpt = tmpt[inds_keep,] -->

<!--   #%% COMPUTE LME MODEL -->
<!--   mod_char = paste(ei," ~ 1 + ",ki," + (1|subj_char)"); -->
<!--   mod <- lme4::lmer(str_glue(mod_char), data=tmpt); -->
<!--   tbl <- mod %>% -->
<!--     tbl_regression(tidy_fun = broom.mixed::tidy, -->
<!--                    pvalue_fun = purrr::partial(style_pvalue, digits = 2), -->
<!--                      intercept=TRUE) %>% -->
<!--     add_global_p() %>% -->
<!--     add_q() -->

<!--   #%% PRINT TABLE -->
<!--   t_out <- as_gt(tbl) %>% -->
<!--     gt::tab_header(title=c("Changes in ",ki,"for Cluster: ",ci)) %>% -->
<!--     gt::tab_options(table.layout = "fixed") %>% -->
<!--     gt::as_raw_html() -->
<!--   print(t_out) -->

<!--   #%% R-SQUARED VALUE -->
<!--   # r.squaredGLMM() %>% -->
<!--   #   print(str_glue("{outcome}\n R2m: {round(mod[1],4)},\tR2c: {round(mod[2],4)}\n\n")) -->

<!--   #%% EFFECT SIZES -->
<!--   cat(paste0("\n\n### model effect sizes\n")) -->
<!--   #-- Intercept Model for Cohen's f^2 -->
<!--   print('intercept model\n'); -->
<!--   mod_char_int = paste(ei," ~ 1 + (1|subj_char)"); -->
<!--   tmp_mod = lme4::lmer(str_glue(mod_char_int), data=tmpt) -->
<!--   cf_alt = calc_cohensf2(mod, tmp_mod) -->
<!--   #-- extract fixed & random effects coeffs -->
<!--   anv_vals <- car::Anova(mod,type=3) -->
<!--   fix_effs <- fixef(mod) -->
<!--   ran_effs <- ranef(mod)$subj_char -->
<!--   #-- calculate effect sizes using r-package -->
<!--   etasq_res <- effectsize::eta_squared(mod, partial = TRUE) -->
<!--   cohens_fsq_res <- effectsize::cohens_f_squared(mod, partial = TRUE) -->

<!--   #%% EXCEL PRINTS -->
<!--   new_row = data.frame(cluster_num=ci, -->
<!--                       group_char=c('all'), -->
<!--                       model_char=c('all_interaction'), -->
<!--                       kinematic_char=c(ki), -->
<!--                       freq_band_char=c(ei), -->
<!--                       coeff_int=mod@beta[1], -->
<!--                       coeff_sp=mod@beta[2], -->
<!--                       coeff_kin=mod@beta[3], -->
<!--                       coeff_intact=mod@beta[4], -->
<!--                       pval_int=anv_vals$`Pr(>Chisq)`[1], -->
<!--                       pval_sp=anv_vals$`Pr(>Chisq)`[2], -->
<!--                       pval_kin=anv_vals$`Pr(>Chisq)`[3], -->
<!--                       pval_intact=anv_vals$`Pr(>Chisq)`[4], -->
<!--                       r2_m_int=cf_alt$r2m, -->
<!--                       r2_c_int=cf_alt$r2c, -->
<!--                       f2_m_int=cf_alt$f2m, -->
<!--                       f2_c_int=cf_alt$f2c, -->
<!--                       fsq_sp=cohens_fsq_res$Cohens_f2_partial[1], -->
<!--                       fsq_kin=cohens_fsq_res$Cohens_f2_partial[2], -->
<!--                       fsq_intact=cohens_fsq_res$Cohens_f2_partial[3], -->
<!--                       etasq_sp=etasq_res$Eta2_partial[1], -->
<!--                       etasq_kin=etasq_res$Eta2_partial[2], -->
<!--                       etasq_intact=etasq_res$Eta2_partial[3], -->
<!--                       ran_effs_char=paste(unlist(row.names(ran_effs)),collapse=','), -->
<!--                       ran_effs_n=paste(unlist(ran_effs$`(Intercept)`),collapse=',')) -->
<!--   excel_df <- rbind(excel_df,new_row) -->

<!--   #%% MODEL VALIDATION PLOTS -->
<!--   cat(paste0("\n\n### model validations\n")) -->
<!--   print(plot_model(mod, type = 'diag')) -->
<!--   cat("\n") -->

<!--   #%% SCATTER3D IMPLEMENTATION -->
<!--   cat(paste0("\n\n### plot\n")) -->
<!--   xc = "speed_cond_num"; -->
<!--   yc = ki; -->
<!--   intc = paste0(xc,":",yc) -->
<!--   #- plot -->
<!--   pch_n = 1; -->
<!--   conds = rev(unique(tmpt[[xc]])) -->
<!--   for(i in 1:length(conds)){ -->
<!--     ts <- filter_at(tmpt,vars(xc),all_vars(. == conds[i])) -->
<!--     if(i == 1){ -->
<!--       scatter <- scatterplot3d(ts[[yc]], ts[[xc]], ts[[ei]], -->
<!--         main = paste0(eeg_title_chars[eis[i]],"plot"), -->
<!--         xlab = kin_title_chars[kis[i]], -->
<!--         ylab = "Speed (m/s)", -->
<!--         zlab = eeg_title_chars[eis[i]], -->
<!--         xlim = c(min(tmpt[[yc]]),max(tmpt[[yc]])), -->
<!--         ylim = c(min(tmpt[[xc]]),max(tmpt[[xc]])), -->
<!--         zlim = c(min(tmpt[[ei]]),max(tmpt[[ei]])), -->
<!--         pch = pch_n, -->
<!--         color = color_pal_subj[i], -->
<!--         angle = 30) # adjust the viewing angle -->
<!--     } else { -->
<!--     scatter$points3d(ts[[yc]], ts[[xc]], ts[[ei]] , -->
<!--         main = paste0(eeg_title_chars[eis[i]],"plot"), -->
<!--         col = color_pal_subj[i], -->
<!--         pch=pch_n) -->
<!--     } -->
<!--   } -->
<!--   a <- fix_effs[xc] -->
<!--   b <- fix_effs[yc] -->
<!--   c <- fix_effs[intc] -->
<!--   d <- fix_effs["(Intercept)"] -->
<!--   # Create the plane's z-values using the equation of the plane -->
<!--   plane_z <- function(y,x){a*x+b*y+c*x*y+d} -->
<!--   scatter$contour3d(plane_z,y.count=4, -->
<!--                     x.count=4, -->
<!--                     y.resolution=10, -->
<!--                     x.resolution=10, -->
<!--                     lty="24", -->
<!--                     type="l") -->

<!-- } -->
<!-- ``` -->

# MODERATION ALL) LME EEG ~ 1+speed+kin+speed:kin
```{r eegspeedkininterall, echo=FALSE, message=FALSE, results="asis"}
theme_set(theme_classic()) # This sets the default ggplot theme
#%% LOOP VARS
cis <- rep(NA,length(clusters)*length(kin_measures)*length(eeg_measures))
kis <- rep(NA,length(clusters)*length(kin_measures)*length(eeg_measures))
eis <- rep(NA,length(clusters)*length(kin_measures)*length(eeg_measures))
cnt = 1;
for (i in 1:length(clusters)) {
  for(j in 1:length(kin_measures)){
    for(k in 1:length(eeg_measures)){
      cis[cnt] = i;
      kis[cnt] = j;
      eis[cnt] = k;
      cnt = cnt + 1;
    }
  }
}

for (i in 1:length(cis)){
  #%% SET LOOP PARAMS
  ci = clusters[cis[i]];
  ki = kin_measures[kis[i]];
  ei = eeg_measures[eis[i]];

  #%% HTML TAG
  cat(paste0("\n\n## ", ci,',', ki,',',ei,"\n"))

  #%% SUBSET BY CLUSTER
  tmpt <- filter_at(dtbl,vars('cluster_n'), any_vars(. %in% ci));

  #%% REMOVE KIN_MEASURES < 0.005 & THAT ARE GREATER THAN OR LESS THAN 3STD FROM MEAN
  #- remove NAN cases
  tmpt = tmpt[complete.cases(tmpt[[ki]]),];
  # #- bad strides cutoff
  # sub_s = tmpt[[ki]] < 0.005
  # #(12/18/2024) JS, changing from 0.01 to 0.005 to see if I can retain some more data without it looking funky
  # tmpt = tmpt[sub_s==FALSE, ]
  # #- mean & std cutoff
  # muc = mean(tmpt[[ki]])
  # stdc = sd(tmpt[[ki]])
  # inds_keep = tmpt[[ki]] > muc-3*stdc & tmpt[[ki]] < muc+3*stdc
  # tmpt = tmpt[inds_keep,]

  #%% COMPUTE LME MODEL
  mod_char = paste(ei," ~ 1 + speed_cond_num + ",ki," + speed_cond_num:",ki," + (1|subj_char)");
  mod <- lme4::lmer(str_glue(mod_char), data=tmpt);
  tbl <- mod %>%
    tbl_regression(tidy_fun = broom.mixed::tidy,
                   pvalue_fun = purrr::partial(style_pvalue, digits = 2),
                     intercept=TRUE) %>%
    add_global_p() %>%
    add_q()

  #%% PRINT TABLE
  t_out <- as_gt(tbl) %>%
    gt::tab_header(title=c("Changes in ",ki,"for Cluster: ",ci)) %>%
    gt::tab_options(table.layout = "fixed") %>%
    gt::as_raw_html()
  print(t_out)

  #%% R-SQUARED VALUE
  # r.squaredGLMM() %>%
  #   print(str_glue("{outcome}\n R2m: {round(mod[1],4)},\tR2c: {round(mod[2],4)}\n\n"))

  #%% EFFECT SIZES
  cat(paste0("\n\n### model effect sizes\n"))
  #-- Intercept Model for Cohen's f^2
  print('intercept model\n');
  mod_char_int = paste(ei," ~ 1 + (1|subj_char)");
  tmp_mod = lme4::lmer(str_glue(mod_char_int), data=tmpt)
  cf_alt = calc_cohensf2(mod, tmp_mod)
  #-- extract fixed & random effects coeffs
  anv_vals <- car::Anova(mod,type=3)
  fix_effs <- fixef(mod)
  ran_effs <- ranef(mod)$subj_char
  #-- calculate effect sizes using r-package
  etasq_res <- effectsize::eta_squared(mod, partial = TRUE)
  cohens_fsq_res <- effectsize::cohens_f_squared(mod, partial = TRUE)

  #%% EXCEL PRINTS
  new_row = data.frame(cluster_num=ci,
                      group_char=c('all'),
                      model_char=c('all_interaction'),
                      kinematic_char=c(ki),
                      freq_band_char=c(ei),
                      coeff_int=mod@beta[1],
                      coeff_sp=mod@beta[2],
                      coeff_kin=mod@beta[3],
                      coeff_intact=mod@beta[4],
                      pval_int=anv_vals$`Pr(>Chisq)`[1],
                      pval_sp=anv_vals$`Pr(>Chisq)`[2],
                      pval_kin=anv_vals$`Pr(>Chisq)`[3],
                      pval_intact=anv_vals$`Pr(>Chisq)`[4],
                      r2_m_int=cf_alt$r2m,
                      r2_c_int=cf_alt$r2c,
                      f2_m_int=cf_alt$f2m,
                      f2_c_int=cf_alt$f2c,
                      fsq_sp=cohens_fsq_res$Cohens_f2_partial[1],
                      fsq_kin=cohens_fsq_res$Cohens_f2_partial[2],
                      fsq_intact=cohens_fsq_res$Cohens_f2_partial[3],
                      etasq_sp=etasq_res$Eta2_partial[1],
                      etasq_kin=etasq_res$Eta2_partial[2],
                      etasq_intact=etasq_res$Eta2_partial[3],
                      ran_effs_char=paste(unlist(row.names(ran_effs)),collapse=','),
                      ran_effs_n=paste(unlist(ran_effs$`(Intercept)`),collapse=','))
  excel_df <- rbind(excel_df,new_row)

  #%% MODEL VALIDATION PLOTS
  cat(paste0("\n\n### model validations\n"))
  print(plot_model(mod, type = 'diag'))
  cat("\n")

  #%% SCATTER3D IMPLEMENTATION
  cat(paste0("\n\n### plot\n"))
  xc = "speed_cond_num";
  yc = ki;
  intc = paste0(xc,":",yc)
  #- plot
  pch_n = 1;
  conds = rev(unique(tmpt[[xc]]))
  for(i in 1:length(conds)){
    ts <- filter_at(tmpt,vars(xc),all_vars(. == conds[i]))
    if(i == 1){
      scatter <- scatterplot3d(ts[[yc]], ts[[xc]], ts[[ei]],
        main = paste0(eeg_title_chars[eis[i]],"plot"),
        xlab = kin_title_chars[kis[i]],
        ylab = "Speed (m/s)",
        zlab = eeg_title_chars[eis[i]],
        xlim = c(min(tmpt[[yc]]),max(tmpt[[yc]])),
        ylim = c(min(tmpt[[xc]]),max(tmpt[[xc]])),
        zlim = c(min(tmpt[[ei]]),max(tmpt[[ei]])),
        pch = pch_n,
        color = color_pal_subj[i],
        angle = 30) # adjust the viewing angle
    } else {
    scatter$points3d(ts[[yc]], ts[[xc]], ts[[ei]] ,
        main = paste0(eeg_title_chars[eis[i]],"plot"),
        col = color_pal_subj[i],
        pch=pch_n)
    }
  }
  a <- fix_effs[xc]
  b <- fix_effs[yc]
  c <- fix_effs[intc]
  d <- fix_effs["(Intercept)"]
  # Create the plane's z-values using the equation of the plane
  plane_z <- function(y,x){a*x+b*y+c*x*y+d}
  scatter$contour3d(plane_z,y.count=4,
                    x.count=4,
                    y.resolution=10,
                    x.resolution=10,
                    lty="24",
                    type="l")

}
# write.xlsx(excel_df,"013022025_lme_eeg_kin_raw_slidingavgb5.xlsx")
write.xlsx(excel_df,paste0("013022025_lme_eeg_kin_",fext,".xlsx"))
```
