---
title: "Linear Mixed Effects Models for Kin & Speed Predictors for EEG"
author: "Jacob Salminen"
date: \`r format(Sys.Date(),"%d-%m-%Y")`\
output:
  html_document:
    theme: flatly
    toc: true
    toc_depth: 6
    toc_float:
      collapsed: true
      smooth_scroll: true
    df_print: paged
    self_contained: yes
---

```{r setup, include=FALSE}
# ERROR. png() device not found bug try: dev.off()
# ERROR. png() device not found fixed by changing cell names to a simple "windows friendlY" format so that knitr could save files.
knitr::opts_chunk$set(echo = TRUE)
```

# Packages & Setup
```{r}
# install.packages(c("tidyverse","purrr","R.matlab","readxl","dplyr"))
#%% PACKAGES FOR STATS
library(readxl);
library(purrr);
library(tidyverse);
library(tibble);
library(knitr);
library(gtsummary);
library(kableExtra);
library(lme4);
library(MuMIn);
library(car);
library(effectsize)
library(sjPlot);
#%% PACKAGES FOR PLOTS & HTML HANDLING
# library(effects);
# library(sjPlot);
# library(plotly);
# library(webshot)
# library(reshape2);
# library(htmltools)
# library(Polychrome);
# library(htmlwidgets);
# library(shiny)
# library(webshot)
library(scatterplot3d)
library(RColorBrewer)
library(openxlsx)
```

## GTSUMMARY THEME
``` {r}
gtsummary::set_gtsummary_theme(theme_gtsummary_journal("jama"))
#--
ispc <- function() {
  sys_name <- Sys.info()["sysname"]
  if (sys_name == "Windows") {
    return(TRUE)
  } else {
    return(FALSE)
  }
}
```
# Set Parameters 
```{r} 
#%% CLUSTERS TO PLOT
clusters = c(3,4,5,7,10,12,13) # RSup/RSM, PreC, LSM, Mid Cing, LSup, LPPA, RPPA

# #%% KIN PARAMS
# kin_measures = c('mu_ml_exc_mm_gc_fn2','mu_step_dur_fn2');
# kin_title_chars = c("ml exc. Std Dev.","step dur. Std Dev.")

#%% EEG PARAMS
# -- EEG PARAMS (fn1 = mean, fn2 = sd)
# eeg_measures = c('std_avg_theta_fn2','std_avg_beta_fn2','std_avg_alpha_fn2',
#                      'std_avg_theta_fn1','std_avg_beta_fn1','std_avg_alpha_fn1');
# eeg_title_chars = c("**THETA** Std. Dev.","**BETA** Std. Dev.","**ALPHA** Std. Dev.",
#                     "**THETA** Mean","**BETA** Mean","**ALPHA** Mean");

#%% EEG PARAMS
# eeg_measures = c('mu_ap_exponent','mu_ap_offset');
# eeg_title_chars = c("Aperiodic Exp.","Aperiodic Off.");

eeg_measures = c('mu_ap_exponent_fn1','mu_ap_offset_fn1',
                 'mu_ap_exponent_fn2','mu_ap_offset_fn2');
eeg_title_chars = c("Aperiodic Exp. mu","Aperiodic Off. mu",
                    "Aperiodic Exp. std","Aperiodic Off. std");
```

<!-- # Load Data -->
<!-- ```{r loaddata} -->
<!-- #%% EEG COMPARISON 1 -->
<!-- fext = "new_meandesignb_nfslidingb6"; -->
<!-- excel_dir <- paste0("/jsalminen/GitHub/MIND_IN_MOTION_PRJ/_data/MIM_dataset/_studies/01192025_mim_yaoa_nopowpow_crit_speed/__iclabel_cluster_kmeansalt_rb3/icrej_5/11/kin_eeg_step_to_step/sbs_eeg_psd_",fext,".xlsx") -->
<!-- if(ispc()){ -->
<!--   excel_dir <- paste0("M:",excel_dir) -->
<!-- }else{ -->
<!--   excel_dir <- paste0("/blue/dferris",excel_dir); -->
<!-- } -->
<!-- #%% SUBSET -->
<!-- dtbl <- read_excel(excel_dir,sheet="Sheet1") -->
<!-- dtbl <- dtbl %>% -->
<!--   select(subj_char,cond_char,epoch_type,speed_n,group_n,group_char,cluster_n,model_n,mu_stride_n, -->
<!--          mu_ap_exponent,mu_ap_offset); -->
<!-- #-- -->
<!-- dtbl <- dtbl %>% -->
<!--   group_by(subj_char,cond_char,epoch_type,speed_n,model_n,group_char,cluster_n) %>% -->
<!--   summarise_all(list("mean","sd")) -->
<!-- #%% MUTATE VARIABLES -->
<!-- dtbl$speed_cond_num <- as.numeric(dtbl$speed_n); -->
<!-- dtbl$subj_char <- as.factor(dtbl$subj_char); -->
<!-- dtbl$group_char <- as.factor(dtbl$group_char); -->
<!-- dtbl$model_n <- as.factor(dtbl$model_n); -->
<!-- dtbl$cond_char <- as.factor(dtbl$cond_char); -->
<!-- #-- assign -->
<!-- dtbl1 = dtbl; -->
<!-- write.xlsx(dtbl,paste0("01302025_lme_eeg_kin_meansd_ap_",fext,"_tbl.xlsx")) -->
<!-- ``` -->

```{r}
#%% EEG COMPARISON 2
fext = "new_meancondb_nfslidingb6";
excel_dir <- paste0("/jsalminen/GitHub/MIND_IN_MOTION_PRJ/_data/MIM_dataset/_studies/01192025_mim_yaoa_nopowpow_crit_speed/__iclabel_cluster_kmeansalt_rb3/icrej_5/11/kin_eeg_step_to_step/sbs_eeg_psd_",fext,".xlsx")
if(ispc()){
  excel_dir <- paste0("M:",excel_dir)
}else{
  excel_dir <- paste0("/blue/dferris",excel_dir);
}

#%% SUBSET
dtbl <- read_excel(excel_dir,sheet="Sheet1")
dtbl <- dtbl %>%
  select(subj_char,cond_char,epoch_type,speed_n,group_n,group_char,cluster_n,model_n,mu_stride_n,
         mu_ap_exponent,mu_ap_offset);
#-- 
dtbl <- dtbl %>%
  group_by(subj_char,cond_char,epoch_type,speed_n,model_n,group_char,cluster_n) %>%
  summarise_all(list("mean","sd"))

#%% MUTATE VARIABLES
dtbl$speed_cond_num <- as.numeric(dtbl$speed_n);
dtbl$subj_char <- as.factor(dtbl$subj_char);
dtbl$group_char <- as.factor(dtbl$group_char);
dtbl$model_n <- as.factor(dtbl$model_n);
dtbl$cond_char <- as.factor(dtbl$cond_char);
#-- assign
dtbl2 = dtbl;
write.xlsx(dtbl,paste0("01302025_lme_eeg_kin_meansd_ap_",fext,"_tbl.xlsx"))
```

```{r}
#%% EEG COMPARISON 3
fext = "new_slidingb6";
excel_dir <- paste0("/jsalminen/GitHub/MIND_IN_MOTION_PRJ/_data/MIM_dataset/_studies/01192025_mim_yaoa_nopowpow_crit_speed/__iclabel_cluster_kmeansalt_rb3/icrej_5/11/kin_eeg_step_to_step/sbs_eeg_psd_",fext,".xlsx")
if(ispc()){
  excel_dir <- paste0("M:",excel_dir)
}else{
  excel_dir <- paste0("/blue/dferris",excel_dir);
}

#%% SUBSET
dtbl <- read_excel(excel_dir,sheet="Sheet1")
dtbl <- dtbl %>%
  select(subj_char,cond_char,epoch_type,speed_n,group_n,group_char,cluster_n,model_n,mu_stride_n,
         mu_ap_exponent,mu_ap_offset);

#-- 
dtbl <- dtbl %>%
  group_by(subj_char,cond_char,epoch_type,speed_n,model_n,group_char,cluster_n) %>%
  summarise_all(list("mean","sd"))

#%% MUTATE VARIABLES
dtbl$speed_cond_num <- as.numeric(dtbl$speed_n);
dtbl$subj_char <- as.factor(dtbl$subj_char);
dtbl$group_char <- as.factor(dtbl$group_char);
dtbl$model_n <- as.factor(dtbl$model_n);
dtbl$cond_char <- as.factor(dtbl$cond_char);
#-- assign
dtbl3 = dtbl;
write.xlsx(dtbl,paste0("01302025_lme_eeg_kin_meansd_ap_",fext,"_tbl.xlsx"))
```

```{r}
#%% EEG COMPARISON 4
fext = "new_perstridefb_nfslidingb6";
excel_dir <- paste0("/jsalminen/GitHub/MIND_IN_MOTION_PRJ/_data/MIM_dataset/_studies/01192025_mim_yaoa_nopowpow_crit_speed/__iclabel_cluster_kmeansalt_rb3/icrej_5/11/kin_eeg_step_to_step/sbs_eeg_psd_",fext,".xlsx")
if(ispc()){
  excel_dir <- paste0("M:",excel_dir)
}else{
  excel_dir <- paste0("/blue/dferris",excel_dir);
}

#%% SUBSET
dtbl <- read_excel(excel_dir,sheet="Sheet1")
dtbl <- dtbl %>%
  select(subj_char,cond_char,epoch_type,speed_n,group_n,group_char,cluster_n,model_n,mu_stride_n,
         mu_ap_exponent,mu_ap_offset);
#-- 
dtbl <- dtbl %>%
  group_by(subj_char,cond_char,epoch_type,speed_n,model_n,group_char,cluster_n) %>%
  summarise_all(list("mean","sd"))

#%% MUTATE VARIABLES
dtbl$speed_cond_num <- as.numeric(dtbl$speed_n);
dtbl$subj_char <- as.factor(dtbl$subj_char);
dtbl$group_char <- as.factor(dtbl$group_char);
dtbl$model_n <- as.factor(dtbl$model_n);
dtbl$cond_char <- as.factor(dtbl$cond_char);
#-- assign
dtbl4 = dtbl;
write.xlsx(dtbl,paste0("01302025_lme_eeg_kin_meansd_ap_",fext,"_tbl.xlsx"))

```

# Format Table
```{r}
#%% BIND TABLES
dtbl <- bind_rows(dtbl2,dtbl3,dtbl4)
#%% COLORS
color_pal_subj = brewer.pal(9,'PuBuGn')
color_pal_subj = color_pal_subj[5:9];

#%% TBL VALUES
tbl_etypes = unique(dtbl$epoch_type);
tbl_clusterS = unique(dtbl$cluster_n);
tbl_subjects = unique(dtbl$subj_char);
tbl_groups = unique(dtbl$group_char);
```

# Functions
```{r}
calc_cohensf2 <- function(mod_main,mod_alt){
  r2_out = r.squaredGLMM(mod_main);
  r2_outalt = r.squaredGLMM(mod_alt);
  r2m = r2_out[1] # input your R2
  f2m = r2m/(1 - r2m)
  r2c = r2_out[2] # input your R2
  f2c = r2c/(1 - r2c)
  f2m = (r2_out[1]-r2_outalt[1])/(1-r2_out[1]);
  f2c = (r2_out[2]-r2_outalt[2])/(1-r2_out[2]);
  print(str_glue("r2m: {round(r2m,4)},\tr2c: {round(r2c,4)}\n\n"))
  print(str_glue("f2m: {round(f2m,4)},\tf2c: {round(f2c,4)}\n\n"))
  vals = data.frame(r2m, r2c, f2m, f2c);
  return (vals)
}

#%% EXCEL DATAFRAME
excel_df <- data.frame(cluster_num=double(),
                        group_char=character(),
                        model_char=character(),
                        kinematic_char=character(),
                        freq_band_char=character(),
                        coeff_int=double(),
                        coeff_sp=double(),
                        coeff_kin=double(),
                        coeff_intact=double(),
                        pval_int=double(),
                        pval_sp=double(),
                        pval_kin=double(),
                        pval_intact=double(),
                        r2_m_int=double(),
                        r2_c_int=double(),
                        f2_m_int=double(),
                        f2_c_int=double(),
                        fsq_sp=double(),
                        fsq_kin=double(),
                        fsq_intact=double(),
                        etasq_sp=double(),
                        etasq_kin=double(),
                        etasq_intact=double(),
                        ran_effs_char=character(),
                        ran_effs_n=character())
```

# EEG-SPEED ALL) LME EEG ~ 1+speed
```{r eegspeedall, echo=FALSE, message=FALSE, results="asis"}
theme_set(theme_classic()) # This sets the default ggplot theme
#%% LOOP VARS
cis <- rep(NA,length(clusters)*length(eeg_measures)*length(tbl_etypes))
eis <- rep(NA,length(clusters)*length(eeg_measures)*length(tbl_etypes))
epis <- rep(NA,length(clusters)*length(eeg_measures)*length(tbl_etypes))
cnt = 1;
for (i in 1:length(clusters)) {
  for(k in 1:length(eeg_measures)){
    for(j in 1:length(tbl_etypes)){
      cis[cnt] = i;
      eis[cnt] = k;
      epis[cnt] = j;
      cnt = cnt + 1;
    }
  }
}

for (i in 1:length(cis)){
  #%% SET LOOP PARAMS
  ci = clusters[cis[i]];
  ei = eeg_measures[eis[i]];
  epi = tbl_etypes[epis[i]];
  #%% HTML TAG
  cat(paste0("\n\n## ",epi,',', ci,',',ei,"\n"))
  
  #%% SUBSET BY EPOCH TYPE
  tmpt <- filter_at(dtbl,vars('epoch_type'), any_vars(. %in% epi));
  
  #%% SUBSET BY CLUSTER
  tmpt <- filter_at(tmpt,vars('cluster_n'), any_vars(. %in% ci));
  #-- remove NAN cases
  # tmpt = tmpt[complete.cases(tmpt[[ki]]),];
  
  #%% THAT ARE GREATER THAN OR LESS THAN 3STD FROM MEAN
  #- mean & std cutoff
  # muc = mean(tmpt[[ei]])
  # stdc = sd(tmpt[[ei]])
  # inds_keep = tmpt[[ei]] > muc-4*stdc & tmpt[[ei]] < muc+4*stdc
  # tmpt = tmpt[inds_keep,]
  
  #%% COMPUTE LME MODEL
  mod_char = paste(ei," ~ 1 + speed_cond_num + (1|subj_char)");
  mod <- lme4::lmer(str_glue(mod_char), data=tmpt);
  tbl <- mod %>%
    tbl_regression(tidy_fun = broom.mixed::tidy,
                   pvalue_fun = purrr::partial(style_pvalue, digits = 2),
                     intercept=TRUE) %>%
    add_global_p() %>%
    add_q()
  
  #%% PRINT TABLE
  t_out <- as_gt(tbl) %>%
    gt::tab_header(title=c("Changes in ",ei,"for Cluster: ",ci)) %>%
    gt::tab_options(table.layout = "fixed") %>%
    gt::as_raw_html()
  print(t_out)
  #-- extract fixed & random effects coeffs
  anv_vals <- car::Anova(mod,type=3)
  fix_effs <- fixef(mod)
  ran_effs <- ranef(mod)$subj_char
  print(anv_vals);
  
  #%% R-SQUARED VALUE
  # r.squaredGLMM() %>%
  #   print(str_glue("{outcome}\n R2m: {round(mod[1],4)},\tR2c: {round(mod[2],4)}\n\n"))
  
  #%% EFFECT SIZES
  cat(paste0("\n\n### model effect sizes\n"))
  #-- Intercept Model for Cohen's f^2
  print('intercept model\n');
  mod_char_int = paste(ei," ~ 1 + (1|subj_char)");
  tmp_mod = lme4::lmer(str_glue(mod_char_int), data=tmpt)
  cf_alt = calc_cohensf2(mod, tmp_mod)
  
  #-- calculate effect sizes using r-package 
  etasq_res <- effectsize::eta_squared(mod, partial = TRUE)
  cohens_fsq_res <- effectsize::cohens_f_squared(mod, partial = TRUE)
  
  #%% EXCEL PRINTS
  new_row = data.frame(cluster_num=ci,
                      group_char=c('all'),
                      model_char=c('all_speed_only'),
                      kinematic_char=c('none'),
                      freq_band_char=c(ei),
                      coeff_int=mod@beta[1],
                      coeff_sp=mod@beta[2],
                      coeff_kin=mod@beta[3],
                      coeff_intact=mod@beta[4],
                      pval_int=anv_vals$`Pr(>Chisq)`[1],
                      pval_sp=anv_vals$`Pr(>Chisq)`[2],
                      pval_kin=anv_vals$`Pr(>Chisq)`[3],
                      pval_intact=anv_vals$`Pr(>Chisq)`[4],
                      r2_m_int=cf_alt$r2m,
                      r2_c_int=cf_alt$r2c,
                      f2_m_int=cf_alt$f2m,
                      f2_c_int=cf_alt$f2c,
                      fsq_sp=cohens_fsq_res$Cohens_f2_partial[1],
                      fsq_kin=cohens_fsq_res$Cohens_f2_partial[2],
                      fsq_intact=cohens_fsq_res$Cohens_f2_partial[3],
                      etasq_sp=etasq_res$Eta2_partial[1],
                      etasq_kin=etasq_res$Eta2_partial[2],
                      etasq_intact=etasq_res$Eta2_partial[3],
                      ran_effs_char=paste(unlist(row.names(ran_effs)),collapse=','),
                      ran_effs_n=paste(unlist(ran_effs$`(Intercept)`),collapse=','))
  excel_df <- rbind(excel_df,new_row)
  
  #%% MODEL VALIDATION PLOTS
  cat(paste0("\n\n### model validations\n"))
  print(plot_model(mod, type = 'diag'))
  cat("\n")
  
  #%% MODEL VALIDATIONS
  cat(paste0("\n\n### model validations\n"))
  # print(plot_model(mod, type = 'diag'))
  cat("\n")
  tmpt$fit.m <- predict(mod, re.form = NA)
  tmpt$fit.c <- predict(mod, re.form = NULL)
  
  #%% VISUALIZATION OF MODELS
  cat(paste0("\n\n### data plot\n"))
  theme_set(theme_classic()) # This sets the default ggplot theme
  print(
    tmpt %>%
      ggplot() +
      geom_jitter(aes(x = speed_cond_num, y = .data[[ei]], color = subj_char), pch=20, size=10, alpha=0.2) +
      geom_line(aes(x= speed_cond_num, y=fit.c, group = subj_char),linetype = "dashed", linewidth = .5) +
      geom_line(aes(x= speed_cond_num, y=fit.m), linewidth = 2)+
      facet_wrap(~group_char) + 
      ggtitle(eeg_title_chars[eis[i]])+ 
      xlab("Treadmill Speed (m/s)") +
      ylab(eeg_title_chars[eis[i]]) +
      guides(group="none")
  )

}
# write.xlsx(excel_df,"lme_eeg_kin_mean_sd_stats.xlsx")
```

# EEG-SPEED GROUP) LME EEG ~ 1+speed
```{r eegspeedgroup, echo=FALSE, message=FALSE, results="asis"}
theme_set(theme_classic()) # This sets the default ggplot theme
#%% LOOP VARS
cis <- rep(NA,length(clusters)*length(eeg_measures)*length(tbl_groups))
eis <- rep(NA,length(clusters)*length(eeg_measures)*length(tbl_groups))
gis <- rep(NA,length(clusters)*length(eeg_measures)*length(tbl_groups))
epis <- rep(NA,length(clusters)*length(eeg_measures)*length(tbl_etypes))
cnt = 1;
for (i in 1:length(clusters)) {
  for(k in 1:length(eeg_measures)){
    for(g in 1:length(tbl_groups)){
      for(j in 1:length(tbl_etypes)){
        cis[cnt] = i;
        eis[cnt] = k;
        gis[cnt] = g;
        epis[cnt] = j;
        cnt = cnt + 1;
      }
    }
  }
}

for (i in 1:length(cis)){
  #%% SET LOOP PARAMS
  ci = clusters[cis[i]];
  ei = eeg_measures[eis[i]];
  gi = tbl_groups[gis[i]];
  epi = tbl_etypes[epis[i]];
  
  #%% HTML TAG
  cat(paste0("\n\n## ",epi,',', ci,',',gi,',',ei,"\n"))
  
  #%% SUBSET BY EPOCH TYPE
  tmpt <- filter_at(dtbl,vars('epoch_type'), any_vars(. %in% epi));

  #%% SUBSET BY CLUSTER
  tmpt <- filter_at(tmpt,vars('cluster_n'), any_vars(. %in% ci));
  #-- remove NAN cases
  # tmpt = tmpt[complete.cases(tmpt[[ki]]),];

  #%% THAT ARE GREATER THAN OR LESS THAN 3STD FROM MEAN
  #- mean & std cutoff
  # muc = mean(tmpt[[ei]])
  # stdc = sd(tmpt[[ei]])
  # inds_keep = tmpt[[ei]] > muc-4*stdc & tmpt[[ei]] < muc+4*stdc
  # tmpt = tmpt[inds_keep,]

  #%% SUBSET BY GROUP
  tmpt <- filter_at(tmpt,vars('group_char'), any_vars(. %in% gi));

  #%% COMPUTE LME MODEL
  mod_char = paste(ei," ~ 1 + speed_cond_num + (1|subj_char)");
  mod <- lme4::lmer(str_glue(mod_char), data=tmpt);
  tbl <- mod %>%
    tbl_regression(tidy_fun = broom.mixed::tidy,
                   pvalue_fun = purrr::partial(style_pvalue, digits = 2),
                     intercept=TRUE) %>%
    add_global_p() %>%
    add_q()

  #%% PRINT TABLE
  t_out <- as_gt(tbl) %>%
    gt::tab_header(title=c("Changes in ",ei,"for Cluster: ",ci)) %>%
    gt::tab_options(table.layout = "fixed") %>%
    gt::as_raw_html()
  print(t_out)
  #-- extract fixed & random effects coeffs
  anv_vals <- car::Anova(mod,type=3)
  fix_effs <- fixef(mod)
  ran_effs <- ranef(mod)$subj_char
  print(anv_vals);

  #%% R-SQUARED VALUE
  # r.squaredGLMM(mod) %>%
  #   print(str_glue("R2m: {round(R2m,4)},\tR2c: {round(R2c,4)}\n\n"))

  #%% EFFECT SIZES
  cat(paste0("\n\n### model effect sizes\n"))
  #-- Intercept Model for Cohen's f^2
  print('intercept model\n');
  mod_char_int = paste(ei," ~ 1 + (1|subj_char)");
  tmp_mod = lme4::lmer(str_glue(mod_char_int), data=tmpt)
  cf_alt = calc_cohensf2(mod, tmp_mod)

  #-- calculate effect sizes using r-package
  etasq_res <- effectsize::eta_squared(mod, partial = TRUE)
  cohens_fsq_res <- effectsize::cohens_f_squared(mod, partial = TRUE)

  #%% EXCEL PRINTS
  new_row = data.frame(cluster_num=ci,
                      group_char=c(gi),
                      model_char=c('speed_only_group'),
                      kinematic_char=c('none'),
                      freq_band_char=c(ei),
                      coeff_int=mod@beta[1],
                      coeff_sp=mod@beta[2],
                      coeff_kin=mod@beta[3],
                      coeff_intact=mod@beta[4],
                      pval_int=anv_vals$`Pr(>Chisq)`[1],
                      pval_sp=anv_vals$`Pr(>Chisq)`[2],
                      pval_kin=anv_vals$`Pr(>Chisq)`[3],
                      pval_intact=anv_vals$`Pr(>Chisq)`[4],
                      r2_m_int=cf_alt$r2m,
                      r2_c_int=cf_alt$r2c,
                      f2_m_int=cf_alt$f2m,
                      f2_c_int=cf_alt$f2c,
                      fsq_sp=cohens_fsq_res$Cohens_f2_partial[1],
                      fsq_kin=cohens_fsq_res$Cohens_f2_partial[2],
                      fsq_intact=cohens_fsq_res$Cohens_f2_partial[3],
                      etasq_sp=etasq_res$Eta2_partial[1],
                      etasq_kin=etasq_res$Eta2_partial[2],
                      etasq_intact=etasq_res$Eta2_partial[3],
                      ran_effs_char=paste(unlist(row.names(ran_effs)),collapse=','),
                      ran_effs_n=paste(unlist(ran_effs$`(Intercept)`),collapse=','))
  excel_df <- rbind(excel_df,new_row)

  #%% MODEL VALIDATIONS
  cat(paste0("\n\n### model validations\n"))
  print(plot_model(mod, type = 'diag'))
  cat("\n")
  tmpt$fit.m <- predict(mod, re.form = NA)
  tmpt$fit.c <- predict(mod, re.form = NULL)

  #%% VISUALIZATION OF MODELS
  cat(paste0("\n\n### data plot\n"))
  theme_set(theme_classic()) # This sets the default ggplot theme
  print(
    tmpt %>%
      ggplot() +
      geom_jitter(aes(x = speed_cond_num, y = .data[[ei]], color = subj_char), pch=20, size=10, alpha=0.2) +
      geom_line(aes(x= speed_cond_num, y=fit.c, group = subj_char),linetype = "dashed", linewidth = .5) +
      geom_line(aes(x= speed_cond_num, y=fit.m), linewidth = 2)+
      facet_wrap(~group_char) +
      ggtitle(eeg_title_chars[eis[i]])+
      xlab("Treadmill Speed (m/s)") +
      ylab(eeg_title_chars[eis[i]]) +
      guides(group="none")
  )
}
# write.xlsx(excel_df,"lme_eeg_kin_imufix_condb.xlsx")
```
