---
title: "Linear Mixed Effects Models for Kin & Speed Predictors for EEG"
author: "Jacob Salminen"
date: \`r format(Sys.Date(),"%d-%m-%Y")`\
output:
  html_document:
    theme: flatly
    toc: true
    toc_depth: 6
    toc_float:
      collapsed: true
      smooth_scroll: true
    df_print: paged
---

```{r setup, include=FALSE}
# ERROR. png() device not found bug try: dev.off()
# ERROR. png() device not found fixed by changing cell names to a simple "windows friendlY" format so that knitr could save files.
knitr::opts_chunk$set(echo = TRUE)
```

# Packages & Setup
```{r}
# install.packages(c("tidyverse","purrr","R.matlab","readxl","dplyr"))
# install.packages(c("dplyr","readxl","purrr","tidyvers","tibble","knitr","gtsummary","kableExtra","lme4","MumIn","sjPlot","htmltools","Polychrome","scatterplot3d","RcolorBrewer","openxlsx","broom"))

#%% PACKAGES FOR STATS
library(readxl);
library(purrr);
library(tidyverse);
library(tibble);
library(knitr);
library(gtsummary);
library(kableExtra);
library(lme4);
library(MuMIn);
library(car);
library(effectsize)
library(sjPlot);

#%% PACKAGES FOR PLOTTING & HTML HANDLING
# library(effects);
# library(plotly);
# library(webshot)
# library(reshape2);
library(htmltools)
library(Polychrome);
# library(htmlwidgets);
# library(shiny)
# library(webshot)
library(scatterplot3d)
library(RColorBrewer)
library(openxlsx)
```

# Set Parameters 
```{r} 
#%% KIN PARAMS
# kin_measures = c('ml_exc_mm','ap_exc_mm','ml_exc_mm_gc','ap_exc_mm_gc')
# kin_title_chars = c("Step width","ap exc.", "step width GC (m)","ap exc. GC (m)")
kin_measures = c('ml_exc_mm','ap_exc_mm','ml_exc_mm_gc','ap_exc_mm_gc')
kin_title_chars = c("Step width","ap exc.", "step width GC (m)","ap exc. GC (m)")
#(01/17/2025) JS, only using the mean of the steps measure as per conversation with dan. Seems to be an effective way to reduce variability, but maintain validity with the gait-cycle-based PSD measures

#%% EEG PARAMS
eeg_measures = c('avg_theta_post',
                 'avg_alpha_post',
                 'avg_beta_post');
eeg_title_chars = c("**THETA** Post",
                    "**ALPHA** Post",
                    "**BETA** Post");
#(01/17/2025) JS, only using the "post" measures as per conversation with dan. The other measures would be "tied" similarly in the model. the LME does not take into account the relativity of the data points in time, just their aggregate deviations. 

#%% CLUSTERS TO PLOT
clusters = c(3,4,6,7,8,9,10,13)
```

# Load Data 
```{r}
excel_dir <-"/jsalminen/GitHub/MIND_IN_MOTION_PRJ/_data/MIM_dataset/_studies/10172024_MIM_YAOAN89_antsnorm_dipfix_iccREMG0p4_powpow0p3_skull0p01_15mmrej_speed/__iclabel_cluster_kmeansalt_rb5/icrej_5/11/sbs_eeg_psd_meandesignb.xlsx"

if(ispc()){
  excel_dir <- paste0("M:",excel_dir)
}else{
  excel_dir <- paste0("/blue/dferris",excel_dir);
}

orig_eegt <- read_excel(excel_dir,sheet="Sheet1")
#%% SUBSET
orig_eegt <- orig_eegt %>%
  select(subj_char,cond_char,speed_n,group_n,group_name,group_char,cluster_n,model_n,model_char,
         avg_theta,avg_beta,avg_alpha,
         avg_theta_post,avg_alpha_post,avg_beta_post,
         avg_theta_pre,avg_alpha_pre,avg_beta_pre,
         ml_exc_mm,ap_exc_mm,ud_exc_mm,ml_exc_mm_gc,ap_exc_mm_gc,ud_exc_mm_gc);

```

# Format Table 
```{r}
eegt <- orig_eegt;
#%% SELECT SPEEDS
eegt <- filter_at(eegt,vars('cond_char'), any_vars(. %in% c('0p25','0p5','0p75','1p0')))
flat_speeds = unique(eegt$cond_char)

#%% MUTATE VARIABLES
eegt$speed_cond_num <- as.numeric(eegt$speed_n); #as.numeric(eegt$cond_char);
eegt <- mutate(eegt,across(c('subj_char'), factor))
eegt <- mutate(eegt,across(c('group_char'), factor))

#%% COLORS
color_pal_subj = brewer.pal(9,'PuBuGn')
color_pal_subj = color_pal_subj[5:9];

#%% TBL VALUES
tbl_clusterS = unique(eegt$cluster_n);
tbl_subjects = unique(eegt$subj_char);
tbl_groups = unique(eegt$group_char);

#%% DISPLAY TBL
head(eegt)
```

# Table Manipulatiosn
```{r}
# Calculate mean and standard deviation by group
# data_summary <- eegt %>%
#   group_by(subj_char) %>%
#   summarise(mean_value = mean(ml_exc_mm,avg_theta_post,avg_alpha_post,avg_beta_post),
#             sd_value = sd(ml_exc_mm,avg_theta_post,avg_alpha_post,avg_beta_post))
dtbl <- eegt %>%
  select(subj_char,cond_char,speed_n,group_char,cluster_n,
         avg_theta,avg_beta,avg_alpha,
         avg_theta_post,avg_alpha_post,avg_beta_post,
         avg_theta_pre,avg_alpha_pre,avg_beta_pre,
         ml_exc_mm,ap_exc_mm,ud_exc_mm,ml_exc_mm_gc,ap_exc_mm_gc,ud_exc_mm_gc);

#%% NEW VARS TO ANALYZE
#-- KIN PARAMS
kin_measures = c('ml_exc_mm_gc_fn1','ml_exc_mm_gc_fn2')
kin_title_chars = c("ML Exc. Mean","ML Exc Std (m)")
#-- EEG PARAMS
eeg_measures = c('avg_theta_post_fn1',
                 'avg_alpha_post_fn1',
                 'avg_beta_post_fn1');
eeg_title_chars = c("**THETA** Post",
                    "**ALPHA** Post",
                    "**BETA** Post");
#-- CLUSTERS TO PLOT
clusters = c(3,4,6,7,8,9,10,13)
eegt <- data_summary;

#%% MUTATE VARIABLES
eegt$speed_cond_num <- as.numeric(eegt$speed_n); #as.numeric(eegt$cond_char);
write.xlsx(dtbl,"lme_eeg_kin_mean_sd_tbl.xlsx")
```

## Functions
```{r}
calc_cohensf2 <- function(mod_main,mod_alt){
  r2_out = r.squaredGLMM(mod_main);
  r2_outalt = r.squaredGLMM(mod_alt);
  r2m = r2_out[1] # input your R2
  f2m = r2m/(1 - r2m)
  r2c = r2_out[2] # input your R2
  f2c = r2c/(1 - r2c)
  f2m = (r2_out[1]-r2_outalt[1])/(1-r2_out[1]);
  f2c = (r2_out[2]-r2_outalt[2])/(1-r2_out[2]);
  print(str_glue("r2m: {round(r2m,4)},\tr2c: {round(r2c,4)}\n\n"))
  print(str_glue("f2m: {round(f2m,4)},\tf2c: {round(f2c,4)}\n\n"))
  vals = data.frame(r2m, r2c, f2m, f2c);
  return (vals)
}
#%% EXCEL DATAFRAME
excel_df <- data.frame(cluster_num=double(),
                        group_char=character(),
                        model_char=character(),
                        kinematic_char=character(),
                        freq_band_char=character(),
                        coeff_int=double(),
                        coeff_sp=double(),
                        coeff_group=double(),
                        coeff_intact=double(),
                        pval_int=double(),
                        pval_sp=double(),
                        pval_group=double(),
                        pval_intact=double(),
                        r2_m_int=double(),
                        r2_c_int=double(),
                        f2_m_int=double(),
                        f2_c_int=double(),
                        fsq_sp=double(),
                        fsq_group=double(),
                        fsq_intact=double(),
                        etasq_sp=double(),
                        etasq_group=double(),
                        etasq_intact=double(),
                        ran_effs_char=character(),
                        ran_effs_n=character())
```
# NO CLUSTER-WISE ANALYSIS
## MODERATION GROUP-WISE) LME kin ~ 1+speed
```{r groupwisekinspeed, echo=FALSE, message=FALSE, results="asis"}
for (ci in cluster_inds_plot) {
  tmptc <- filter_at(eegt,vars('cluster_n'), any_vars(. %in% ci))
  cat(paste0("\n\n### CL ",ci,"\n"))
  for(ki in kin_inds_plot){
    for (gi in 1:length(groups)) {
      tmpt <- filter_at(tmptc,vars('group_char'), any_vars(. %in% groups[gi]));
      
      #%% PREPARE TABLE
      tmpt = tmpt[complete.cases(tmpt[[kin_measures[ki]]]),];
      sub_s = tmpt[[kin_measures[ki]]] < 0.005
      #(12/18/2024) JS, changing from 0.01 to 0.005 to see if I can retain some more data without it looking funky
      tmpt = tmpt[sub_s==FALSE, ]
      #--
      muc = mean(tmpt[[kin_measures[ki]]])
      stdc = sd(tmpt[[kin_measures[ki]]])
      inds_keep = tmpt[[kin_measures[ki]]] > muc-3*stdc & tmpt[[kin_measures[ki]]] < muc+3*stdc
      tmpt = tmpt[inds_keep,]
      
      #%% COMPUTE LME MODEL
      cat(paste0("\n\n#### group ",groups[gi],"\n"))
      mod_char = paste(kin_measures[ki]," ~ 1 + speed_cond_num  + (1|subj_char)");
      mod <- lme4::lmer(str_glue(mod_char), data=tmpt);
      tbl <- mod %>%
        tbl_regression(tidy_fun = broom.mixed::tidy,
                       pvalue_fun = purrr::partial(style_pvalue, digits = 2),
                       intercept=TRUE) %>%
        add_global_p() %>%
        add_q()
      
      #%% PRINT TABLE
      t_out <- as_gt(tbl) %>%
        gt::tab_header(title=c("Changes in ",kin_measures[ki])) %>%
        gt::tab_options(table.layout = "fixed") %>%
        gt::as_raw_html()
      print(t_out)
      tmp = mod %>%
        r.squaredGLMM()
      print(str_glue("{kin_measures[ki]}\n R2m: {round(tmp[1],4)},\tR2c: {round(tmp[2],4)}\n\n"))
      
      #%% EFFECT SIZES
      cat(paste0("\n\n##### ",kin_measures[ki]," model effect sizes\n"))
      alt_mod_char_int = paste(kin_measures[ki]," ~ 1 + (1|subj_char)");
      #--
      print('intercept model\n');
      tmp_mod = lmer(str_glue(alt_mod_char_int), data=tmpt)
      vals1=calc_cohensf2(mod, tmp_mod)
      #--
      anv_vals <- car::Anova(mod,type=3)
      fix_effs <- fixef(mod)
      ran_effs <- ranef(mod)$subj_char
      #-- calculate effect sizes
      etasq_res <- effectsize::eta_squared(mod, partial = TRUE)
      cohens_fsq_res <- effectsize::cohens_f_squared(mod, partial = TRUE)
      
      #%% EXCEL PRINTS
      new_row = data.frame(cluster_num=ci,
                          group_char=groups[gi],
                          model_char=c('group_wise_speed'),
                          kinematic_char=c(kin_measures[ki]),
                          freq_band_char=c('nan'),
                          coeff_int=mod@beta[1],
                          coeff_sp=mod@beta[2],
                          coeff_group=mod@beta[3],
                          coeff_intact=mod@beta[4],
                          pval_int=anv_vals$`Pr(>Chisq)`[1],
                          pval_sp=anv_vals$`Pr(>Chisq)`[2],
                          pval_group=anv_vals$`Pr(>Chisq)`[3],
                          pval_intact=anv_vals$`Pr(>Chisq)`[4],
                          r2_m_int=vals1$r2m,
                          r2_c_int=vals1$r2c,
                          f2_m_int=vals1$f2m,
                          f2_c_int=vals1$f2c,
                          fsq_sp=cohens_fsq_res$Cohens_f2_partial[1],
                          fsq_group=cohens_fsq_res$Cohens_f2_partial[2],
                          fsq_intact=cohens_fsq_res$Cohens_f2_partial[3],
                          etasq_sp=etasq_res$Eta2_partial[1],
                          etasq_group=etasq_res$Eta2_partial[2],
                          etasq_intact=etasq_res$Eta2_partial[3],
                          ran_effs_char=paste(unlist(row.names(ran_effs)),collapse=','),
                          ran_effs_n=paste(unlist(ran_effs$`(Intercept)`),collapse=','))
      excel_df <- rbind(excel_df,new_row)
      
      #%% MODEL VALIDATIONS
      cat(paste0("\n\n##### ",kin_measures[ki]," model validations\n"))
      # print(plot_model(mod, type = 'diag'))
      cat("\n")
      
      #%% VISUALIZATION OF MODELS
      theme_set(theme_classic()) # This sets the default ggplot theme
      cat("\n")
      tmpt <- tmpt %>%
          mutate(fit.m = predict(mod, re.form = NA),
                 fit.c = predict(mod, re.form = NULL))
      #%% VISUALIZATION OF MODELS
      theme_set(theme_classic()) # This sets the default ggplot theme
      print(
        tmpt %>%
          ggplot() +
          geom_jitter(aes(x = speed_cond_num, y = .data[[kin_measures[ki]]], color = subj_char),pch=20, size=.1, alpha=0.1) +
          geom_line(aes(x= speed_cond_num, y=fit.c, group = subj_char),linetype = "dashed", linewidth = .5) +
          geom_line(aes(x= speed_cond_num, y=fit.m), linewidth = 2) +
          ggtitle(kin_measures[ki])+ 
          guides(group="none")
      )
    }
  }
}
# write.xlsx(excel_df,"moderation_eeg_psd_kin_speed_intact_nonorm_sepgroup.xlsx")
```

## MODERATION 1, NO GROUP) KIN ~ 1 + SPEED
```{r nogroupkinspeed, echo=FALSE, message=FALSE, results="asis"}
for (ci in cluster_inds_plot) {
  tmptc <- filter_at(eegt,vars('cluster_n'), any_vars(. %in% ci))
  cat(paste0("\n\n### CL ",ci,"\n"))
  for(ki in kin_inds_plot){
    tmpt <- tmptc;
    #%% PREPARE TABLE
    tmpt = tmpt[complete.cases(tmpt[[kin_measures[ki]]]),];
    sub_s = tmpt[[kin_measures[ki]]] < 0.005
    #(12/18/2024) JS, changing from 0.01 to 0.005 to see if I can retain some more data without it looking funky
    tmpt = tmpt[sub_s==FALSE, ]
    #--
    muc = mean(tmpt[[kin_measures[ki]]])
    stdc = sd(tmpt[[kin_measures[ki]]])
    inds_keep = tmpt[[kin_measures[ki]]] > muc-3*stdc & tmpt[[kin_measures[ki]]] < muc+3*stdc
    tmpt = tmpt[inds_keep,]
    
    #%% COMPUTE LME MODEL
    cat(paste0("\n\n#### kin ",kin_measures[ki],"\n"))
    mod_char = paste(kin_measures[ki]," ~ 1 + speed_cond_num  + (1|subj_char)");
    mod <- lme4::lmer(str_glue(mod_char), data=tmpt);
    tbl <- mod %>%
      tbl_regression(tidy_fun = broom.mixed::tidy,
                     pvalue_fun = purrr::partial(style_pvalue, digits = 2),
                     intercept=TRUE) %>%
      add_global_p() %>%
      add_q()
    
    #%% PRINT TABLE
    t_out <- as_gt(tbl) %>%
      gt::tab_header(title=c("Changes in ",kin_measures[ki])) %>%
      gt::tab_options(table.layout = "fixed") %>%
      gt::as_raw_html()
    print(t_out)
    tmp = mod %>%
      r.squaredGLMM()
    print(str_glue("{kin_measures[ki]}\n R2m: {round(tmp[1],4)},\tR2c: {round(tmp[2],4)}\n\n"))
    
    #%% EFFECT SIZES
    cat(paste0("\n\n##### ",kin_measures[ki]," model effect sizes\n"))
    alt_mod_char_int = paste(kin_measures[ki]," ~ 1 + (1|subj_char)");
    #--
    print('intercept model\n');
    tmp_mod = lmer(str_glue(alt_mod_char_int), data=tmpt)
    vals1=calc_cohensf2(mod, tmp_mod)
    #--
    anv_vals <- car::Anova(mod,type=3)
    print(anv_vals);
    fix_effs <- fixef(mod)
    ran_effs <- ranef(mod)$subj_char
    #-- calculate effect sizes
    etasq_res <- effectsize::eta_squared(mod, partial = TRUE)
    cohens_fsq_res <- effectsize::cohens_f_squared(mod, partial = TRUE)
    
    #%% EXCEL PRINTS
    new_row = data.frame(cluster_num=ci,
                        group_char=c('all'),
                        model_char=c('all'),
                        kinematic_char=c(kin_measures[ki]),
                        freq_band_char=c('nan'),
                        coeff_int=mod@beta[1],
                        coeff_sp=mod@beta[2],
                        coeff_group=mod@beta[3],
                        coeff_intact=mod@beta[4],
                        pval_int=anv_vals$`Pr(>Chisq)`[1],
                        pval_sp=anv_vals$`Pr(>Chisq)`[2],
                        pval_group=anv_vals$`Pr(>Chisq)`[3],
                        pval_intact=anv_vals$`Pr(>Chisq)`[4],
                        r2_m_int=vals1$r2m,
                        r2_c_int=vals1$r2c,
                        f2_m_int=vals1$f2m,
                        f2_c_int=vals1$f2c,
                        fsq_sp=cohens_fsq_res$Cohens_f2_partial[1],
                        fsq_group=cohens_fsq_res$Cohens_f2_partial[2],
                        fsq_intact=cohens_fsq_res$Cohens_f2_partial[3],
                        etasq_sp=etasq_res$Eta2_partial[1],
                        etasq_group=etasq_res$Eta2_partial[2],
                        etasq_intact=etasq_res$Eta2_partial[3],
                        ran_effs_char=paste(unlist(row.names(ran_effs)),collapse=','),
                        ran_effs_n=paste(unlist(ran_effs$`(Intercept)`),collapse=','))
    excel_df <- rbind(excel_df,new_row)
    
    #%% MODEL VALIDATIONS
    cat(paste0("\n\n##### ",kin_measures[ki]," model validations\n"))
    # print(plot_model(mod, type = 'diag'))
    cat("\n")
    tmpt <- tmpt %>%
        mutate(fit.m = predict(mod, re.form = NA),
               fit.c = predict(mod, re.form = NULL))
    #%% VISUALIZATION OF MODELS
    theme_set(theme_classic()) # This sets the default ggplot theme
    print(
      tmpt %>%
        ggplot() +
        geom_jitter(aes(x = speed_cond_num, y = .data[[kin_measures[ki]]], color = subj_char), pch=20, size=.1, alpha=0.2) +
        geom_line(aes(x= speed_cond_num, y=fit.c, group = subj_char),linetype = "dashed", linewidth = .5) +
        geom_line(aes(x= speed_cond_num, y=fit.m, group = group_char), linewidth = 2)+
        facet_wrap(~group_char) + 
        ggtitle(kin_measures[ki])+ 
        guides(group="none")
    )
  }
}
```

## INTACT, GROUP TERM) KIN ~ 1 + SPEED + GROUP + SPEED:GROUP
```{r kinspeedgroupintact, echo=FALSE, message=FALSE, results="asis"}
for (ci in cluster_inds_plot) {
  tmptc <- filter_at(eegt,vars('cluster_n'), any_vars(. %in% ci))
  cat(paste0("\n\n### CL ",ci,"\n"))
  for(ki in kin_inds_plot){
    tmpt <- tmptc;
    #%% PREPARE TABLE
    tmpt = tmpt[complete.cases(tmpt[[kin_measures[ki]]]),];
    sub_s = tmpt[[kin_measures[ki]]] < 0.005
    #(12/18/2024) JS, changing from 0.01 to 0.005 to see if I can retain some more data without it looking funky
    tmpt = tmpt[sub_s==FALSE, ]
    #--
    muc = mean(tmpt[[kin_measures[ki]]])
    stdc = sd(tmpt[[kin_measures[ki]]])
    inds_keep = tmpt[[kin_measures[ki]]] > muc-3*stdc & tmpt[[kin_measures[ki]]] < muc+3*stdc
    tmpt = tmpt[inds_keep,]
    
    #%% COMPUTE LME MODEL
    cat(paste0("\n\n#### kin ",kin_measures[ki],"\n"))
    mod_char = paste(kin_measures[ki]," ~ 1 + speed_cond_num  + group_char + speed_cond_num:group_char + (1|subj_char)");
    mod <- lme4::lmer(str_glue(mod_char), data=tmpt);
    tbl <- mod %>%
      tbl_regression(tidy_fun = broom.mixed::tidy,
                     pvalue_fun = purrr::partial(style_pvalue, digits = 2),
                     intercept=TRUE) %>%
      add_global_p() %>%
      add_q()
    
    #%% PRINT TABLE
    t_out <- as_gt(tbl) %>%
      gt::tab_header(title=c("Changes in ",kin_measures[ki])) %>%
      gt::tab_options(table.layout = "fixed") %>%
      gt::as_raw_html()
    print(t_out)
    tmp = mod %>%
      r.squaredGLMM()
    print(str_glue("{kin_measures[ki]}\n R2m: {round(tmp[1],4)},\tR2c: {round(tmp[2],4)}\n\n"))
    
    #%% EFFECT SIZES
    cat(paste0("\n\n##### ",kin_measures[ki]," model effect sizes\n"))
    alt_mod_char_int = paste(kin_measures[ki]," ~ 1 + (1|subj_char)");
    #--
    print('intercept model\n');
    tmp_mod = lmer(str_glue(alt_mod_char_int), data=tmpt)
    vals1=calc_cohensf2(mod, tmp_mod)
    #--
    anv_vals <- car::Anova(mod,type=3)
    fix_effs <- fixef(mod)
    ran_effs <- ranef(mod)$subj_char
    #-- calculate effect sizes
    etasq_res <- effectsize::eta_squared(mod, partial = TRUE)
    cohens_fsq_res <- effectsize::cohens_f_squared(mod, partial = TRUE)
    
    #%% EXCEL PRINTS
    new_row = data.frame(cluster_num=ci,
                        group_char=c('all'),
                        model_char=c('group_term_speed_intact'),
                        kinematic_char=c(kin_measures[ki]),
                        freq_band_char=c('nan'),
                        coeff_int=mod@beta[1],
                        coeff_sp=mod@beta[2],
                        coeff_group=mod@beta[3],
                        coeff_intact=mod@beta[4],
                        pval_int=anv_vals$`Pr(>Chisq)`[1],
                        pval_sp=anv_vals$`Pr(>Chisq)`[2],
                        pval_group=anv_vals$`Pr(>Chisq)`[3],
                        pval_intact=anv_vals$`Pr(>Chisq)`[4],
                        r2_m_int=vals1$r2m,
                        r2_c_int=vals1$r2c,
                        f2_m_int=vals1$f2m,
                        f2_c_int=vals1$f2c,
                        fsq_sp=cohens_fsq_res$Cohens_f2_partial[1],
                        fsq_group=cohens_fsq_res$Cohens_f2_partial[2],
                        fsq_intact=cohens_fsq_res$Cohens_f2_partial[3],
                        etasq_sp=etasq_res$Eta2_partial[1],
                        etasq_group=etasq_res$Eta2_partial[2],
                        etasq_intact=etasq_res$Eta2_partial[3],
                        ran_effs_char=paste(unlist(row.names(ran_effs)),collapse=','),
                        ran_effs_n=paste(unlist(ran_effs$`(Intercept)`),collapse=','))
    excel_df <- rbind(excel_df,new_row)
    
    #%% MODEL VALIDATIONS
    cat(paste0("\n\n##### ",kin_measures[ki]," model validations\n"))
    # print(plot_model(mod, type = 'diag'))
    cat("\n")
    tmpt <- tmpt %>%
        mutate(fit.m = predict(mod, re.form = NA),
               fit.c = predict(mod, re.form = NULL))
    
    #%% VISUALIZATION OF MODELS
    theme_set(theme_classic()) # This sets the default ggplot theme
    print(
      tmpt %>%
        ggplot() +
        geom_jitter(aes(x = speed_cond_num, y = .data[[kin_measures[ki]]], color = subj_char), pch=20, size=.1, alpha=0.2) +
        geom_line(aes(x= speed_cond_num, y=fit.c, group = subj_char),linetype = "dashed", linewidth = .5) +
        geom_line(aes(x= speed_cond_num, y=fit.m), linewidth = 2)+
        facet_wrap(~group_char) + 
        ggtitle(kin_measures[ki])+ 
        guides(group="none")
    )
  }
}
```

## NO INTACT, GROUP TERM) KIN ~ 1 + SPEED + GROUP
```{r kinspeedgroup, echo=FALSE, message=FALSE, results="asis"}
for (ci in cluster_inds_plot) {
  tmptc <- filter_at(eegt,vars('cluster_n'), any_vars(. %in% ci))
  cat(paste0("\n\n### CL ",ci,"\n"))
  for(ki in kin_inds_plot){
    tmpt <- tmptc;
    #%% PREPARE TABLE
    tmpt = tmpt[complete.cases(tmpt[[kin_measures[ki]]]),];
    sub_s = tmpt[[kin_measures[ki]]] < 0.005
    #(12/18/2024) JS, changing from 0.01 to 0.005 to see if I can retain some more data without it looking funky
    tmpt = tmpt[sub_s==FALSE, ]
    #--
    muc = mean(tmpt[[kin_measures[ki]]])
    stdc = sd(tmpt[[kin_measures[ki]]])
    inds_keep = tmpt[[kin_measures[ki]]] > muc-3*stdc & tmpt[[kin_measures[ki]]] < muc+3*stdc
    tmpt = tmpt[inds_keep,]
    
    #%% COMPUTE LME MODEL
    cat(paste0("\n\n#### kin ",kin_measures[ki],"\n"))
    mod_char = paste(kin_measures[ki]," ~ 1 + speed_cond_num  + group_char + (1|subj_char)");
    mod <- lme4::lmer(str_glue(mod_char), data=tmpt);
    tbl <- mod %>%
      tbl_regression(tidy_fun = broom.mixed::tidy,
                     pvalue_fun = purrr::partial(style_pvalue, digits = 2),
                     intercept=TRUE) %>%
      add_global_p() %>%
      add_q()
    
    #%% PRINT TABLE
    t_out <- as_gt(tbl) %>%
      gt::tab_header(title=c("Changes in ",kin_measures[ki])) %>%
      gt::tab_options(table.layout = "fixed") %>%
      gt::as_raw_html()
    print(t_out)
    tmp = mod %>%
      r.squaredGLMM()
    print(str_glue("{kin_measures[ki]}\n R2m: {round(tmp[1],4)},\tR2c: {round(tmp[2],4)}\n\n"))
    
    #%% EFFECT SIZES
    cat(paste0("\n\n##### ",kin_measures[ki]," model effect sizes\n"))
    alt_mod_char_int = paste(kin_measures[ki]," ~ 1 + (1|subj_char)");
    #--
    print('intercept model\n');
    tmp_mod = lmer(str_glue(alt_mod_char_int), data=tmpt)
    vals1=calc_cohensf2(mod, tmp_mod)
    #--
    anv_vals <- car::Anova(mod,type=3)
    fix_effs <- fixef(mod)
    ran_effs <- ranef(mod)$subj_char
    #-- calculate effect sizes
    etasq_res <- effectsize::eta_squared(mod, partial = TRUE)
    cohens_fsq_res <- effectsize::cohens_f_squared(mod, partial = TRUE)
    
    #%% EXCEL PRINTS
    new_row = data.frame(cluster_num=ci,
                        group_char=c('all'),
                        model_char=c('group_term_speed'),
                        kinematic_char=c(kin_measures[ki]),
                        freq_band_char=c('nan'),
                        coeff_int=mod@beta[1],
                        coeff_sp=mod@beta[2],
                        coeff_group=mod@beta[3],
                        coeff_intact=mod@beta[4],
                        pval_int=anv_vals$`Pr(>Chisq)`[1],
                        pval_sp=anv_vals$`Pr(>Chisq)`[2],
                        pval_group=anv_vals$`Pr(>Chisq)`[3],
                        pval_intact=anv_vals$`Pr(>Chisq)`[4],
                        r2_m_int=vals1$r2m,
                        r2_c_int=vals1$r2c,
                        f2_m_int=vals1$f2m,
                        f2_c_int=vals1$f2c,
                        fsq_sp=cohens_fsq_res$Cohens_f2_partial[1],
                        fsq_group=cohens_fsq_res$Cohens_f2_partial[2],
                        fsq_intact=cohens_fsq_res$Cohens_f2_partial[3],
                        etasq_sp=etasq_res$Eta2_partial[1],
                        etasq_group=etasq_res$Eta2_partial[2],
                        etasq_intact=etasq_res$Eta2_partial[3],
                        ran_effs_char=paste(unlist(row.names(ran_effs)),collapse=','),
                        ran_effs_n=paste(unlist(ran_effs$`(Intercept)`),collapse=','))
    excel_df <- rbind(excel_df,new_row)
    
    #%% MODEL VALIDATIONS
    cat(paste0("\n\n##### ",kin_measures[ki]," model validations\n"))
    # print(plot_model(mod, type = 'diag'))
    cat("\n")
    tmpt <- tmpt %>%
        mutate(fit.m = predict(mod, re.form = NA),
               fit.c = predict(mod, re.form = NULL))
    #%% VISUALIZATION OF MODELS
    theme_set(theme_classic()) # This sets the default ggplot theme
    print(
      tmpt %>%
        ggplot() +
        geom_jitter(aes(x = speed_cond_num, y = .data[[kin_measures[ki]]], color = subj_char), pch=20, size=.1, alpha=0.2) +
        geom_line(aes(x= speed_cond_num, y=fit.c, group = subj_char),linetype = "dashed", linewidth = .5) +
        geom_line(aes(x= speed_cond_num, y=fit.m), linewidth = 2)+
        facet_wrap(~group_char) + 
        ggtitle(kin_measures[ki])+ 
        guides(group="none")
    )
  }
}
#%% SAVE WIDGET AS AN INDEPENDENT HTML FILE
pwd <- getwd()
write.xlsx(excel_df,file.path(pwd,"speed_kin_lme_behavior.xlsx"))
```