%   Project Title: MIM YOUNGER AND OLDER ADULTS KINEMATICS-EEG ANALYSIS
%
%   Code Designer: Jacob salminen
%## SBATCH (SLURM KICKOFF SCRIPT)
% sbatch /blue/dferris/jsalminen/GitHub/par_EEGProcessing/src/2_STUDY/mim_yaoa_speed_kin/.sh

%{
%## RESTORE MATLAB
% WARNING: restores default pathing to matlab 
restoredefaultpath;
clc;
close all;
clearvars
%}
%% SET WORKSPACE ======================================================= %%
% opengl('dsave', 'software') % might be needed to plot dipole plots?
%## TIME
tic
ADD_ALL_SUBMODS = false;
%## Determine Working Directories
if ~ispc
    try
        SCRIPT_DIR = matlab.desktop.editor.getActiveFilename;
        SCRIPT_DIR = fileparts(SCRIPT_DIR);
        SRC_DIR = fileparts(SCRIPT_DIR); % change this if in sub folder
    catch e
        fprintf('ERROR. PWD_DIR couldn''t be set...\n%s',getReport(e))
        SCRIPT_DIR = getenv('SCRIPT_DIR');
        SRC_DIR = getenv('SRC_DIR');
    end
else
    try
        SCRIPT_DIR = matlab.desktop.editor.getActiveFilename;
        SCRIPT_DIR = fileparts(SCRIPT_DIR);
    catch e
        fprintf('ERROR. PWD_DIR couldn''t be set...\n%s',getReport(e))
        SCRIPT_DIR = dir(['.' filesep]);
        SCRIPT_DIR = SCRIPT_DIR(1).folder;
    end
    SRC_DIR = fileparts(SCRIPT_DIR); % change this if in sub folder
end
%## Add Study, Src, & Script Paths
addpath(SCRIPT_DIR)
addpath(SRC_DIR);
cd(SRC_DIR);
fprintf(1,'Current folder: %s\n',SRC_DIR);
%## Set PWD_DIR, EEGLAB path, _functions path, and others...
set_workspace
%% (DATASET INFORMATION) =============================================== %%
% [SUBJ_PICS,GROUP_NAMES,SUBJ_ITERS,~,~,~,~] = mim_dataset_information('yaoa_spca');
[SUBJ_PICS,GROUP_NAMES,SUBJ_ITERS,~,~,~,~] = mim_dataset_information('yaoa_spca_speed');
%% (PATHS) ============================================================= %%
%- datset name
DATA_SET = 'MIM_dataset';
%- study name
% STUDY_DNAME = '10172024_MIM_YAOAN89_antsnorm_dipfix_iccREMG0p4_powpow0p3_skull0p01_15mmrej_speed';
% STUDY_DNAME =  '01192025_mim_yaoa_nopowpow_crit_speed';
STUDY_DNAME = '02202025_mim_yaoa_powpow0p3_crit_speed';
STUDY_FNAME = 'kin_eeg_epoch_study';
ANALYSIS_DNAME = 'kin_eeg_step_to_step';
studies_fpath = [PATHS.data_dir filesep DATA_SET filesep '_studies'];

%## CLUSTER LOADING
CLUSTER_K = 11;
CLUSTER_STUDY_NAME = 'temp_study_rejics5';
% cluster_fpath = [studies_fpath filesep sprintf('%s',STUDY_DNAME) filesep '__iclabel_cluster_kmeansalt_rb10'];
% cluster_fpath = [studies_fpath filesep sprintf('%s',STUDY_DNAME) filesep '__iclabel_cluster_kmeansalt_rb3'];
cluster_fpath = [studies_fpath filesep sprintf('%s',STUDY_DNAME) filesep '__iclabel_cluster_allcond_rb3'];
cluster_study_fpath = [cluster_fpath filesep 'icrej_5'];
cluster_k_dir = [cluster_study_fpath filesep sprintf('%i',CLUSTER_K)];
%## R-STATS LOADING
r_stats_dir = [PATHS.src_dir filesep 'r_scripts' filesep 'sbs_lme_mods'];
%-
save_dir = [cluster_k_dir filesep ANALYSIS_DNAME];
if ~exist(save_dir,'dir')
    mkdir(save_dir);
end
%% ===================================================================== %%
% if ~ispc
%     [STUDY,ALLEEG] = pop_loadstudy('filename',[STUDY_FNAME '_UNIX.study'],'filepath',save_dir);
% else
%     [STUDY,ALLEEG] = pop_loadstudy('filename',[STUDY_FNAME '.study'],'filepath',save_dir);
% end
%## LOAD CLUSTER STUDY
if ~ispc
    tmp = load('-mat',[cluster_study_fpath filesep sprintf('%s_UNIX.study',CLUSTER_STUDY_NAME)]);
    CL_STUDY = tmp.STUDY;
else
    tmp = load('-mat',[cluster_study_fpath filesep sprintf('%s.study',CLUSTER_STUDY_NAME)]);
    CL_STUDY = tmp.STUDY;
end

%## LOAD STUDY
if ~ispc
    tmp = load('-mat',[studies_fpath filesep sprintf('%s',STUDY_DNAME) filesep sprintf('%s_UNIX.study',STUDY_FNAME)]);
    STUDY = tmp.STUDY;
else
    tmp = load('-mat',[studies_fpath filesep sprintf('%s',STUDY_DNAME) filesep sprintf('%s.study',STUDY_FNAME)]);
    STUDY = tmp.STUDY;
end
%-
cl_struct = par_load(cluster_k_dir,sprintf('cl_inf_%i.mat',CLUSTER_K));
STUDY.cluster = cl_struct;
[comps_out,main_cl_inds,outlier_cl_inds] = eeglab_get_cluster_comps(STUDY);
CLUSTER_PICS = main_cl_inds;

%% (LOAD STATISTICS & DATA EXCEL SHEET FROM R) ========================= %%
%## FNAMES
%-- r stats
% fextr = 'allcond_perstridefb_mi_nfslidingb36_rerun';
% fextr = 'allcond_perstridefb_apfix_std_mi_nfslidingb36_rerun';
fextr = 'allcond_perstridefb_apfix_std_mi_nfslidingb36';

%## IMPORT MEANSD DATA
% KIN_TABLE = readtable([r_stats_dir filesep sprintf('03122025_lme_eeg_kin_meansd_%s_tbl.xlsx',fextr)], ...
%     "FileType","spreadsheet","UseExcel",true);
% KIN_TABLE = readtable([r_stats_dir filesep sprintf('03312025_lme_eeg_kin_meansd_%s_tbl.xlsx',fextr)], ...
%     "FileType","spreadsheet","UseExcel",true);
% %-- r-stats
% RSTATS_IMPORT = readtable([r_stats_dir filesep sprintf('03312025_lme_eeg_kin_meansd_%s_stats.xlsx',fextr)], ...
%     "FileType","spreadsheet","UseExcel",true);
KIN_TABLE = readtable([r_stats_dir filesep sprintf('05132025_lme_eeg_kin_meansd_%s_tbl.xlsx',fextr)], ...
    "FileType","spreadsheet","UseExcel",true);
%-- r-stats
RSTATS_IMPORT = readtable([r_stats_dir filesep sprintf('05132025_lme_eeg_kin_meansd_%s_stats.xlsx',fextr)], ...
    "FileType","spreadsheet","UseExcel",true);

%% MEASURES TO ANALYZE ================================================= %%
xtick_label_c = {'0.25 m/s','0.50 m/s','0.75 m/s','1.0 m/s'};
cluster_inds_plot = [3,4,5,6,7,8,9,11,12];

%##
speed_xvals = (0:5)*0.25;
c_chars = {'0.25 m/s','0.50 m/s','0.75 m/s','1.0 m/s'};
g_chars_topo = {'Young Adults',{'Older High','Functioning Adults'},{'Older Low','Functioning Adults'}};
g_chars_subp = {'YA','OHFA','OLFA'};
cmaps_speed = linspecer(4*3);
cmaps_speed = [cmaps_speed(1,:);cmaps_speed(2,:);cmaps_speed(3,:);cmaps_speed(4,:)];
%## EXTRACT PSD DATA
color_dark = cmaps_speed; %color.speed;
color_light = cmaps_speed+0.15; %color.speed_shade;
xtick_label_g = {'0.25','0.50','0.75','1.0'};
cond_offsets = [-0.35,-0.1,0.15,0.40];
%--
des_i = 2;
cl_n = 3;
s_chars = {STUDY.datasetinfo(STUDY.cluster(cl_n).sets).subject};
desdes = cat(1,STUDY.design.variable);
g_chars = {'H1000','H2000','H3000'};
G_ORDER = categorical(g_chars);
%% ===================================================================== %%
%## PARAMETERS
%-
% group_chars = unique(KIN_TABLE.group_char)
designs = unique(KIN_TABLE.model_n);
group_chars = unique(KIN_TABLE.group_char);
cond_chars = unique(KIN_TABLE.cond_char);
clusters = unique(RSTATS_IMPORT.cluster_num);
%--
SAVE_RES = 300;
TITLE_TXT_SIZE = 14;
%--
LAB_A_YOFFSET = -0.16;
LAB_A_XOFFSET = -0.125;
LAB_B_YOFFSET = 0.065;
LAB_B_XOFFSET = -0.125;
LAB_C_YOFFSET = 0.06; %0.075
LAB_C_XOFFSET = -0.125;
LAB_D_YOFFSET = 0.09;
LAB_D_XOFFSET = -0.125;
%## 
AXES_DEFAULT_PROPS = {'box','off', ...
    'xtick',[], ...
    'ytick',[],...
    'ztick',[], ...
    'xcolor',[1,1,1], ...
    'ycolor',[1,1,1]};

%## VIOLIN PLOTS
label_struct = struct('Units','normalized',...
    'FontName','Arial', ...
    'FontSize',8, ...
    'FontWeight','bold');
group_anno_struct = struct(...
    'FontName','Arial', ...
    'FontSize',8, ...
    'FontWeight','normal', ...
    'HorizontalAlignment','center',...
    'Units','data');
ax_struct = struct('box','off', ...
    'LineWidth',1, ...
    'FontWeight','normal', ...
    'FontName','Arial', ...
    'FontSize',12, ...
    'OuterPosition',[0 0 1 1], ...
    'Position',[0.3,0.3,0.5,0.5]);
title_props_struct = struct('Units','normalized',...
    'FontName','Arial', ...
    'FontSize',8, ...
    'FontWeight','bold');
stats_char_struct = struct('FontSize',9,...
    'FontName','Arial',...
    'FontWeight','bold', ...
    'Units','normalized');
reg_line_struct = struct('LineStyle','-', ...
    'Color','k', ...
    'LineWidth',2);
DEF_VPLOT_STRUCT = struct('color_map',linspecer(10),...
    'cond_labels',{{'0.25','0.50','0.75','1.0'}},...
    'cond_offsets',[-0.35,-0.1,0.15,0.40],...
    'do_group_labels',true, ... % group props
    'do_combine_groups',false,...
    'group_labels',{{'YA','OHFA','OLFA'}},...
    'group_offsets',[0.125,0.475,0.812],...
    'group_label_offset',[0,-0.285],...
    'group_label_props',group_anno_struct, ...
    'y_label',{{''}},... % y-label props
    'ytick',[], ... 
    'ytick_labs',{{''}}, ...
    'y_label_props',label_struct, ...
    'y_label_offset',[0,0], ...
    'ylim',[],...
    'x_label',{{'Speed (m/s)'}},... % x-label props
    'x_label_props',label_struct, ...
    'x_label_offset',[0,-0.1],...
    'xlim',[],...
    'xtick',[], ...
    'xtick_labs',{{''}}, ...
    'xtick_angle',75,...
    'title',{{''}},... % title props
    'title_props',title_props_struct, ...
    'ax_props',ax_struct, ... % ax props
    'stats_char_props',stats_char_struct, ... % stats & scatter props
    'reg_line_props',reg_line_struct, ...
    'scatter_props',struct(...
        'SizeData',4, ...
        'Marker','*', ...
        'CData',[0,0,0], ...
        'jitter','on', ...
        'jitterAmount', 0.05));
VIO_STRUCT = struct('Width',0.15,...
    'ShowWhiskers',false,...
    'ShowNotches',false,...
    'ShowBox',true,...
    'ShowMedian',true,...
    'Bandwidth',0.1,...
    'QuartileStyle','shadow',...
    'HalfViolin','full',...
    'DataStyle','scatter',...
    'MarkerSize',8,...
    'EdgeColor',[0.5,0.5,0.5],...
    'ViolinAlpha',{{0.3,0.4}},...
    'do_plot_outlier_marks',true,...
    'use_raw_bandwidth',false);
BRACKET_STRUCT = struct('sig_sign','+',...
    'line_specs',{{'LineStyle','-','LineWidth',2,'Color','k'}},...
    'text_specs',{{'FontSize',8,'FontName','Arial','FontWeight','bold'}},...
    'bracket_conn',[],...
    'conn_offset_y_upper',[],...
    'bracket_offset_y_upper',0,...
    'bracket_offset_y_lower',0,...
    'sig_offset_x',0,...
    'sig_offset_y',[]);
SIGLINE_STRUCT = struct('sig_sign','*',...
    'line_specs',{{'LineStyle','-','LineWidth',2,'Color','k'}},...
    'text_specs',{{'FontSize',8,'FontName','Arial','FontWeight','bold'}},...
    'conn_y',[],...
    'conn_offset_y',[],...
    'sig_offset_x',0,...
    'sig_offset_y',0);

%## MODELS
COEFF_CHARS_INT = {'(Intercept)','speed_cond_num','group_char1','group_char2', ...
    'speed_cond_num:group_char1','speed_cond_num:group_char2'};
ANV_CHARS_INT = {'(Intercept)','speed_cond_num','group_char','speed_cond_num:group_char'};
ANV_CHARS_GROUP = {'(Intercept)','speed_cond_num','group_char'};
COEFF_CHARS_GROUP = {'(Intercept)','speed_cond_num','group_char1','group_char2'};
%--
LETTERS = {'A','B','C'};
%% (ALL SUBJS MODEL) =================================================== %%
meas_ext = 'cov_behav';
tmp_savedir = [save_dir filesep fextr '_manufigs'];
mkdir(tmp_savedir);
%## INITIATE FIGURE
%-- initiate params
% cl_ii = find(cluster_inds_plot(cl_i) == double(string(clusters)));
% cl_n = double(string(clusters(cl_ii)));
% atlas_name = {'Interstride Variability','of','Gait Kinematics'};
% atlas_name = {'Coefficient of Variation','for','Pelvis Kinematics'};
atlas_name = {'Coefficient of Variation for Pelvis Kinematics'};

%## INITIATE FIGURE
%-- title
FG_TXT_SZ = 1;
fy_shift = 0;
fx_shift = 0;
TITLE_FONT_SIZE = 14;
FIGURE_POSITION =[1,1,6.5,9];
FONT_NAME = 'Arial';
TITLE_XSHIFT = 0.1;
TITLE_YSHIFT = 0.97+fy_shift;
TITLE_BOX_SZ = [0.8,0.4];
ttxs = (1-TITLE_BOX_SZ(1))/2;
ttys = TITLE_YSHIFT-(TITLE_BOX_SZ(2)/2);
%-- fig
fig = figure('color','white', ...
    'Renderer','Painters');    
annotation('textbox',[ttxs,ttys,TITLE_BOX_SZ],...
    'String',atlas_name, ...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle', ...
    'LineStyle','none', ...
    'FontName',FONT_NAME,...
    'FontSize',14, ...close 
    'FontWeight','Bold', ...
    'Units','normalized');
set(fig,'Units','inches', ...
    'Position',FIGURE_POSITION, ...
    'PaperUnits','inches', ...
    'PaperSize',[1 1], ...
    'PaperPosition',[0 0 1 1])
p_sz = get(fig,'Position');
set(gca,AXES_DEFAULT_PROPS{:});
hold on;

% VIOLIN PLOTS) ================================================== %%
%--
YLIM_NTICKS = 5;
YLIM_SIG_FIGS = 2;
PRC_YLIM = [3,97];
YLIM_FAC = 2;
IM_RESIZE = 0.8;
AX_SZ = [0.35,0.225];
AX_FONT_NAME = 'Arial';
AX_X_SHIFT = 1.3;
AX_Y_SHIFT = -1.45;
% F = AX_W*IM_RESIZE;
% xF = (AX_W*IM_RESIZE*AX_X_SHIFT-F)/2;
% AX_INIT_X = 0.5-F-xF;
F = AX_W*IM_RESIZE;
xF = (AX_W*IM_RESIZE*AX_X_SHIFT-F);
AX_INIT_X = 0.5-(3/2)*F-xF;
AX_INIT_Y = 0.72;
X_DIM = 3;
%-- std measures
EEG_MEASURES = {'cov_ml_exc_mm_gc_fn1', ...
    'cov_swing_dur_fn1', ...
    'cov_stance_dur_fn1'};
EEG_MEASURE_LABS = {'COV (%)', ...
    'COV (%)', ...
    'COV (%)'};
EEG_MEASURE_TITLES = {'Mediolateral Excursion', ...
    'Swing Duration', ...
    'Stance Duration'}; 
YLIMS =[0,0.5;0,0.3;0,0.3];
% YLIMS =[0,50;0,22.5;0,22.5];
YTICKS = {[-1e-8,0.1,0.2,0.3,0.4,0.5] ...
    [-1e-8,0.1,0.2,0.3], ...
    [-1e-8,0.1,0.2,0.3]};
% YTICKS = {[-1e-8,0.1,0.2,0.3,0.4,0.5]*100, ...
%     [-1e-8,0.1,0.2]*100, ...
%     [-1e-8,0.1,0.2]*100};
% YTICK_LABS = {{'0','0.1','0.2','0.3','0.4','0.5'}, ...
%     {'0','0.1','0.2','0.3'}, ...
%     {'0','0.1','0.2','0.3'}};
YTICK_LABS = {{'0','10','20','30','40','50'}, ...
    {'0','10','20','30'}, ...
    {'0','10','20','30'}};
%--
x_shift = AX_INIT_X;   
y_shift = AX_INIT_Y;
y_lims = zeros(length(EEG_MEASURES),2);
ax_s = cell(length(EEG_MEASURES),1);
x_cnt = 1;    
for e_i = 1:length(EEG_MEASURES)
    %##
    cond_plot_store = [];
    group_plot_store = [];        
    eeg_measure = EEG_MEASURES{e_i};

    %## SUB-SELECT DATA
    subjs = unique(KIN_TABLE.subj_char);
    conds = unique(KIN_TABLE.cond_char);
    tmp_tbl = cell(length(subjs)*length(conds),1);
    cnt = 1;
    for s_i = 1:length(subjs)
        for c_i = 1:length(conds)
            ind = find(strcmp(KIN_TABLE.subj_char,subjs{s_i}) & ...
                strcmp(KIN_TABLE.cond_char,conds{c_i}));
            tmp_tbl{cnt} = KIN_TABLE(ind(1),:);
            cnt = cnt + 1;
        end
    end
    tmp_tbl = cat(1,tmp_tbl{:});

    %## EXTRACT STATS INFO
    EXTRACT_STRUCT = struct( ...
        'group_chars', {{'H1000','H2000','H3000'}}, ...
        'group_order', categorical({'H1000','H2000','H3000'}), ...
        'model_char_int', 'speed_group_intact_all', ...
        'model_char_group', 'speed_group_all', ...
        'group_char', 'all', ...
        'anv_chars_int', {ANV_CHARS_INT}, ...
        'anv_chars_group', {ANV_CHARS_GROUP}, ...
        'coeff_chars_int', {COEFF_CHARS_INT}, ...
        'coeff_chars_group', {COEFF_CHARS_GROUP}, ...
        'eeg_measure', {'none'}, ...
        'kin_measure', {EEG_MEASURES{e_i}}, ...
        'coeff_study', {'speed'}, ...
        'do_display_str',true, ...
        'str_offset', [-0.05, 0], ...
        'str_font_size', 10*FG_TXT_SZ, ...
        'ci_bar_width', 0.15, ...
        'ci_bar_xpos', 0, ...
        'ci_bar_linespecs', {{'LineStyle','-','LineWidth',2,'Color','k'}}, ...
        'coeff_desm', [ ...                
            0, 1; ...                
           -1,-1; ...
            1, 0 ...
        ] ...
    );
    %--
    % [STATS_STRUCT,CONFINT_STRUCT,ranef] = extract_violin_stats(RSTATS_IMPORT,cl_n,params);
    [tmp_stats_struct,tmp_confint_struct,ranef,rawvalues] = get_r_stats_func(RSTATS_IMPORT,0, ...
        'EXTRACT_STRUCT',EXTRACT_STRUCT);
    % tmp_stats_struct.stats_char.str = {sprintf('R^{2}=%1.2f',rawvalues.rsq(1)),'',''};

    %## NORMALIZE DATA USING SUBJECT INTERCEPTS
    if ~isempty(ranef.char)
        for s_i = 1:length(ranef.char)
            int = ranef.int(s_i);
            ind = strcmp(ranef.char{s_i},tmp_tbl.subj_char);
            tmp_tbl(ind,eeg_measure) = tmp_tbl(ind,eeg_measure)-int;
        end
    end

    %## PLOT
    ax = axes();
    %-- set parameters
    %-- set parameter
    tmp_vio_struct = VIO_STRUCT;
    tmp_vio_struct.MarkerSize = 8*FG_TXT_SZ*0.8;
    tmp_vio_struct.vio_edge_alpha = 0.9;
    tmp_vio_struct.vio_edge_lw = 0.5*FG_TXT_SZ; 
    %--
    tmp_plot_struct = DEF_VPLOT_STRUCT;
    tmp_plot_struct.scatter_props.SizeData = 4*FG_TXT_SZ;
    tmp_plot_struct.title_props.FontSize = 10*FG_TXT_SZ;
    tmp_plot_struct.x_label_offset = [0,-0.15];
    tmp_plot_struct.x_label_props.FontSize = 10*FG_TXT_SZ;
    tmp_plot_struct.y_label_props.FontSize = 10*FG_TXT_SZ;
    tmp_plot_struct.group_label_props.FontSize = 10*FG_TXT_SZ;
    tmp_plot_struct.group_label_offset = [0,-0.265];
    tmp_plot_struct.ax_props = struct('box','off', ...
        'LineWidth',1, ...
        'FontWeight','normal', ...
        'FontName','Arial', ...
        'FontSize',9*FG_TXT_SZ, ...
        'OuterPosition',[0 0 1 1], ...
        'Position',[x_shift,y_shift,AX_SZ(1)*IM_RESIZE,AX_SZ(2)*IM_RESIZE]);
    tmp_plot_struct.group_labels = g_chars_subp; %params.group_chars; %g_chars_subp;
    tmp_plot_struct.color_map = color_dark;
    tmp_plot_struct.title = EEG_MEASURE_TITLES(e_i);
    tmp_plot_struct.y_label = EEG_MEASURE_LABS{e_i};
    tmp_plot_struct.ylim = YLIMS(e_i,:);
    tmp_plot_struct.ytick_labs = YTICK_LABS{e_i};
    tmp_plot_struct.ytick = YTICKS{e_i};

    if e_i ~= 1
        tmp_plot_struct.y_label = '';
    else        
        tmp_plot_struct.y_label = EEG_MEASURE_LABS{e_i};
    end
    tmp_plot_struct.x_label = 'Speed (m/s)';
    %-- group violin plot
    ax = group_violin(tmp_tbl,eeg_measure,'speed_n','group_char',...
        ax,...
        'VIOLIN_STRUCT',VIO_STRUCT,...
        'PLOT_STRUCT',tmp_plot_struct,...
        'STATS_STRUCT',tmp_stats_struct,...
        'BRACKET_STRUCT',BRACKET_STRUCT,...
        'SIGLINE_STRUCT',SIGLINE_STRUCT, ...
        'CONFINT_STRUCT',tmp_confint_struct);

    %## LETTER TITLE
    FG_TIT_FIX = [1,1];
    TIT_BOX_SZ = [0.1,0.1];
    TIT_SHIFT = [-0.1,0.11];
    ttxs = x_shift+TIT_SHIFT(1)*FG_TIT_FIX(1)+(TIT_BOX_SZ(1)/2);
    ttys = y_shift+TIT_SHIFT(2)*FG_TIT_FIX(2)+(TIT_BOX_SZ(2)/2);
    TIT_POS = [ttxs,ttys,TIT_BOX_SZ(1),TIT_BOX_SZ(2)];
    annotation('textbox',TIT_POS,...
        'String',sprintf('%s',LETTERS{e_i}), ...
        'HorizontalAlignment','left',...
        'VerticalAlignment','middle', ...
        'LineStyle','none', ...
        'FontName',FONT_NAME,...
        'FontSize',14*FG_TXT_SZ, ...
        'FontWeight','Bold', ...
        'Units','normalized');

    %## KEY
    if e_i == 1    
        SIG_K_PROPS = {'HorizontalAlignment','left',...
            'VerticalAlignment','top', ...
            'LineStyle','none', ...
            'FontName','Arial',...
            'FontSize',10*FG_TXT_SZ, ...
            'FontWeight','bold', ...
            'Units','normalized'};   
        
        KEY_CHARS = ['P_{value}<0.05: ', ...
            'Speed (S): *  |  ', ...
            'Group (G): +  |  ', ...
            sprintf('Interaction (S:G): %s',char(8225))];
        FG_ANN_FIX = [1,1];
        % ANNO_BOXSZ = [0.6,0.05];
        ANNO_SHIFT = [-0.065,0.14];
        ltxs = 0.175; %key_pos_store(1)+0.17; %+ANNO_SHIFT(1)*FG_ANN_FIX(1)+(0.1/2); %0.7069*FG_FIX(1)+fx_shift+LAB_B_YOFFSET+(0.1/2);
        ltys = AX_INIT_Y-0.125; %key_pos_store(2)-0.025; %tys+ANNO_SHIFT(2)*FG_ANN_FIX(2)+(0.1/2); %+fy_shift+LAB_B_XOFFSET+(0.1/2);
        ANNO_POS = [ltxs,ltys,0.8,0.05];
        annotation(fig,'textbox',ANNO_POS,...
            'String',KEY_CHARS, ...
            SIG_K_PROPS{:});
    end

    %-- ax sets
    %## AX SHIFTd
    if x_cnt < X_DIM
        x_shift = x_shift + AX_X_SHIFT*IM_RESIZE*AX_W;
    else
        y_shift = y_shift + AX_Y_SHIFT*IM_RESIZE*AX_H;
        x_shift = AX_INIT_X;
        x_cnt = 0;
    end
    x_cnt = x_cnt + 1; 
end
hold on;

%%
fname = sprintf('%s_manscript_plot',meas_ext);
exportgraphics(fig,[tmp_savedir filesep fname '.pdf'],...
    'ContentType','Vector')
exportgraphics(fig,[tmp_savedir filesep fname '.png'],...
    'Resolution',SAVE_RES)
% close(fig)