---
title: "Linear Mixed Effects Models for Kin & Speed Predictors for EEG"
author: "Jacob Salminen"
date: \`r format(Sys.Date(),"%d-%m-%Y")`\
output:
  html_document:
    theme: flatly
    toc: true
    toc_depth: 6
    toc_float:
      collapsed: false
      smooth_scroll: true
    df_print: paged
---

```{r setup, include=FALSE}
# ERROR. png() device not found bug try: dev.off()
# ERROR. png() device not found fixed by changing cell names to a simple "windows friendlY" format so that knitr could save files.
knitr::opts_chunk$set(echo = TRUE)
```

# Packages & Setup
```{r}
# install.packages(c("tidyverse","purrr","R.matlab","readxl","dplyr"))
library(readxl);
library(purrr);
library(tidyverse);
library(tibble);
library(knitr);
library(gtsummary);
library(kableExtra);
library(lme4);
library(MuMIn);
# library(effects);
library(sjPlot);
# library(rgl);
library(plotly);
library(webshot)
library(reshape2);
library(htmltools)
library(Polychrome);
# library(listviewer);
```

## GTSUMMARY THEME
``` {r}
gtsummary::set_gtsummary_theme(theme_gtsummary_journal("jama"))
```

## load table 
```{r} 
# excel_dir <-"M:/jsalminen/GitHub/par_EEGProcessing/src/_data/MIM_dataset/_studies/04162024_MIM_YAOAN89_antsnormalize_iccREMG0p4_powpow0p3_skull0p01/cluster/icrej_5/12/spec_data/group_spec/psd_calcs/fooof_kinematics_table.xlsx";
# excel_dir <-"M:/jsalminen/GitHub/par_EEGProcessing/src/_data/MIM_dataset/_studies/04232024_MIM_YAOAN89_antsnorm_dipfix_iccREMG0p4_powpow0p3_skull0p01_15mmrej/cluster/icrej_5/11/spec_data/group_spec/psd_calcs/fooof_kinematics_table_nans.xlsx";
excel_dir <-"M:/jsalminen/GitHub/par_EEGProcessing/src/_data/MIM_dataset/_studies/04232024_MIM_YAOAN89_antsnorm_dipfix_iccREMG0p4_powpow0p3_skull0p01_15mmrej/iclabel_cluster_kmeansalt_rb3/icrej_5/11/psd_calcs/group_spec/kin_tests/fooof_kinematics_table.xlsx";
orig_eegt <- read_excel(excel_dir,sheet="Sheet1") 
```

## get unique entries 
```{r} 

#%% KIN PARAMS
# kin_measures = c('mean_APexc_COV','mean_APexc_mean','mean_MLexc_COV','mean_MLexc_mean','mean_StepDur','mean_StepDur_cov','mean_UDexc_COV','mean_UDexc_mean','mean_StanceDur','mean_GaitCycleDur','mean_PeakUpDownVel_mean');
# kin_title_chars = c("AP Exc. COV","AP Exc. Mean","ML Exc. COV","ML Exc. Mean","Step Dur.","Step Dur. COV","UD Exc. COV","UD Exc Mean","Stance Dur.","Gait Cycle Dur.","Peak UD Vel. Mean")
# kin_measures = c('mean_APexc_COV','mean_MLexc_COV','mean_StepDur_cov','mean_StanceDur');
# kin_title_chars = c("AP Exc. COV","ML Exc. COV","Step Dur. COV","Stance Dur.")
kin_measures = c('mean_APexc_COV','mean_MLexc_COV');
kin_title_chars = c("AP Exc. COV","ML Exc. COV")
kin_inds_plot = c(1:length(kin_measures));
# kin_inds_plot = c(1,3,6,5,7);
#%% EEG PARAMS
clusters = unique(orig_eegt$cluster_id);
subjects = unique(orig_eegt$subj_char);
groups = unique(orig_eegt$group_char);
# eeg_measures = c('theta_avg_power','alpha_avg_power','beta_avg_power','beta_div_theta','theta_div_beta','log_beta_div_theta','log_theta_div_beta','aperiodic_exp','aperiodic_offset');
# eeg_title_chars = c("**THETA**","**ALPHA**","**BETA**","**BETA/THETA**","**THETA/BETA**","**log10(BETA/THETA)**","**log10(THETA/BETA)**","**AP exp**","**AP offset**");
# eeg_measures = c('theta_avg_power','alpha_avg_power','beta_avg_power','aperiodic_exp','aperiodic_offset');
eeg_measures = c('norm_theta_avg_power','norm_alpha_avg_power','norm_beta_avg_power');
eeg_title_chars = c("**THETA**","**ALPHA**","**BETA**");
# eeg_inds_plot = c(1:length(eeg_title_chars));
eeg_inds_plot = c(1,2,3);
x_vals_plot = c('speed_diffdiv_stat')
x_vals_labs = c("**(Trial-Subj.)/(Subj.)**")
cluster_inds_plot = c(3,4,5,6,7,8,12);
```

## create ratios
```{r}
df <- orig_eegt %>%
  select(subj_char,cond_char,cluster_id,group_id,alpha_avg_power,beta_avg_power,theta_avg_power) %>%
  pivot_wider(names_from = "cond_char", names_sep = '.', values_from = c(alpha_avg_power,beta_avg_power,theta_avg_power))

# df <- df %>%
#   group_by(subj_char) %>%
#   mutate(across(starts_with("alpha_avg_power"), ~ .x/alpha_avg_power.flat))
# df <- df %>%
#   group_by(subj_char) %>%
#   mutate(across(starts_with("beta_avg_power"), ~ .x/beta_avg_power.flat))
# df <- df %>%
#   group_by(subj_char) %>%
#   mutate(across(starts_with("theta_avg_power"), ~ .x/theta_avg_power.flat))
df <- df %>%
  group_by(subj_char) %>%
  mutate(across(starts_with("alpha_avg_power"), ~ .x-alpha_avg_power.flat))
df <- df %>%
  group_by(subj_char) %>%
  mutate(across(starts_with("beta_avg_power"), ~ .x-beta_avg_power.flat))
df <- df %>%
  group_by(subj_char) %>%
  mutate(across(starts_with("theta_avg_power"), ~ .x-theta_avg_power.flat))

df <- df %>%
  pivot_longer(cols = starts_with(c("alpha","beta","theta")), names_to = c(".value","cond_char"), names_pattern = "(.*_power).(.*)");

df$norm_alpha_avg_power <- df$alpha_avg_power
df$norm_beta_avg_power <- df$beta_avg_power
df$norm_theta_avg_power <- df$theta_avg_power
df <- select(df,-alpha_avg_power,-beta_avg_power,-theta_avg_power);
eegt <- merge(orig_eegt , df, by.x = c("subj_char","cond_char","cluster_id","group_id"), by.y = c("subj_char","cond_char","cluster_id","group_id"));
```
## get speeds only 
```{r}
eegt <- filter_at(eegt,vars('cond_char'), any_vars(. %in% c('0.25','0.5','0.75','1.0')))
flat_speeds = unique(eegt$cond_char)
eegt$speed_cond_num <- as.numeric(eegt$speed_diffdiv_stat); #as.numeric(eegt$cond_char)
eegt <- mutate(eegt,across(c('subj_char'), factor))
eegt <- mutate(eegt,across(c('group_char'), factor))
eegt$speed_cond_numsq <- eegt$speed_cond_num^2
head(eegt)
```

# EEG TESTS: SPEED, GROUP, INTERACTION

## LME EEG ~ 1+speed+group+speed:group
```{r eegspeedgroupinter, echo=FALSE, message=FALSE, results="asis"}
library(gtsummary)
# inter_pvalue = vector(mode="logical");
for (ci in cluster_inds_plot) {
  tmpt <- filter_at(eegt,vars('cluster_id'), any_vars(. %in% ci));
  for(ki in kin_inds_plot){
    tmpt = tmpt[complete.cases(tmpt[[kin_measures[ki]]]),]
  }
  tbl <- tibble(outcome=eeg_measures[eeg_inds_plot]) %>%
    rowwise() %>%
    mutate(
      tbl = 
        lmer(str_glue("{outcome} ~ 1 + speed_cond_numsq + speed_cond_num + group_char + speed_cond_num:group_char + (1+speed_cond_numsq+speed_cond_num|subj_char)"), data=tmpt) %>%
        tbl_regression(tidy_fun = broom.mixed::tidy,
                       pvalue_fun = purrr::partial(style_pvalue, digits = 2),
                       intercept=TRUE) %>%
        add_global_p() %>%
        add_q() %>%
        list()
      ) %>%
    pull(tbl) %>%
    tbl_merge(tab_spanner=eeg_title_chars[eeg_inds_plot])
  
  t_out <- as_gt(tbl) %>%
    gt::tab_header(title=c("Cluster: ",ci)) %>%
    gt::as_raw_html()
  print(t_out)
  
  rsq <- tibble(outcome=eeg_measures[eeg_inds_plot]) %>%
    rowwise() %>%
    mutate(
        mod = 
          lmer(str_glue("{outcome} ~ 1 + speed_cond_numsq + speed_cond_num + group_char + speed_cond_num:group_char + (1+speed_cond_numsq+speed_cond_num|subj_char)"), data=tmpt) %>%
          r.squaredGLMM(),
          print(str_glue("{outcome}\n R2m: {round(mod[1],4)},\tR2c: {round(mod[2],4)}\n\n"))
    )
  
  #%% VISUALIZATION OF MODELS
  theme_set(theme_classic()) # This sets the default ggplot theme
  fitfit <- tibble(outcome=eeg_measures[eeg_inds_plot]) %>%
    rowwise() %>%
    mutate(
        mod = 
          lmer(str_glue("{outcome} ~ 1 + speed_cond_numsq + speed_cond_num + group_char + speed_cond_num:group_char + (1+speed_cond_numsq+speed_cond_num|subj_char)"), data=tmpt)%>%
          list()
    )
  for(modi in 1:length(eeg_measures[eeg_inds_plot])){
    eegi = eeg_inds_plot[modi]
    tmpt <- tmpt %>%
      mutate(fit.m = predict(fitfit$mod[[modi]], re.form = NA),
             fit.c = predict(fitfit$mod[[modi]], re.form = NULL))
    
    # print(plot_model(fitfit$mod[[modi]], type = 'diag'))
    
    print(
      tmpt %>%
        ggplot(aes(x = speed_cond_num, y = .data[[eeg_measures[eegi]]], group = subj_char, col=group_char)) +
        geom_point(pch=16, size=2, alpha=0.5) +
        geom_line(aes(x= speed_cond_num, y=fit.c, group = subj_char),color="grey", size = .1) +
        geom_line(aes(x= speed_cond_num, y=fit.m, col = group_char), size = 2)+
        facet_wrap(vars(group_char))+
        ggtitle(eeg_measures[eegi])+ 
        guides(group="none")
    )
  }
  
  # t_out <- as_gt(tbl) %>%
  #   gt::tab_header(title=c("Cluster: ",ci)) %>%
  #   gt::tab_options(table.layout = "fixed") %>%
  #   gt::as_raw_html()
  # print(t_out)
  
  # t_out <- as_kable_extra(tbl, format = "latex") %>%
  #   add_header_above(c("Cluster: ",ci)) %>%
  #   kable_styling(latex_options="scale_down")
  # 
  # cat(knitr::knit_print(t_out));
  # if (ci%%2 == 0){
  #   cat('\\clearpage');
  # }
}
```
## LME EEG ~ 1+speed+group
```{r eegspeedgroup, echo=FALSE, message=FALSE, results="asis"}
library(gtsummary)
# inter_pvalue = vector(mode="logical");
for (ci in cluster_inds_plot) {
  tmpt <- filter_at(eegt,vars('cluster_id'), any_vars(. %in% ci));
  for(ki in kin_inds_plot){
    tmpt = tmpt[complete.cases(tmpt[[kin_measures[ki]]]),]
  }
  tbl <- tibble(outcome=eeg_measures[eeg_inds_plot]) %>%
    rowwise() %>%
    mutate(
      tbl = 
        lmer(str_glue("{outcome} ~ 1 + speed_cond_numsq + speed_cond_num + group_char + (1+speed_cond_numsq+speed_cond_num|subj_char)"), data=tmpt) %>%
        tbl_regression(tidy_fun = broom.mixed::tidy,
                       pvalue_fun = purrr::partial(style_pvalue, digits = 2),
                       intercept=TRUE) %>%
        add_global_p() %>%
        add_q() %>%
        list()
      ) %>%
    pull(tbl) %>%
    tbl_merge(tab_spanner=eeg_title_chars[eeg_inds_plot])
  
  t_out <- as_gt(tbl) %>%
    gt::tab_header(title=c("Cluster: ",ci)) %>%
    gt::as_raw_html()
  print(t_out)
  
  rsq <- tibble(outcome=eeg_measures[eeg_inds_plot]) %>%
    rowwise() %>%
    mutate(
        mod = 
          lmer(str_glue("{outcome} ~ 1 + speed_cond_numsq + speed_cond_num + group_char + (1+speed_cond_numsq+speed_cond_num|subj_char)"), data=tmpt) %>%
          r.squaredGLMM(),
          print(str_glue("{outcome}\n R2m: {round(mod[1],4)},\tR2c: {round(mod[2],4)}\n\n"))
    )
  
  #%% VISUALIZATION OF MODELS
  theme_set(theme_classic()) # This sets the default ggplot theme
  fitfit <- tibble(outcome=eeg_measures[eeg_inds_plot]) %>%
    rowwise() %>%
    mutate(
        mod = 
          lmer(str_glue("{outcome} ~ 1 + speed_cond_numsq + speed_cond_num + group_char + (1+speed_cond_numsq+speed_cond_num|subj_char)"), data=tmpt)%>%
          list()
    )
  for(modi in 1:length(eeg_measures[eeg_inds_plot])){
    eegi = eeg_inds_plot[modi]
    tmpt <- tmpt %>%
      mutate(fit.m = predict(fitfit$mod[[modi]], re.form = NA),
             fit.c = predict(fitfit$mod[[modi]], re.form = NULL))
    
    # print(plot_model(fitfit$mod[[modi]], type = 'diag'))
    
    print(
      tmpt %>%
        ggplot(aes(x = speed_cond_num, y = .data[[eeg_measures[eegi]]], group = subj_char, col=group_char)) +
        geom_point(pch=16, size=2, alpha=0.5) +
        geom_line(aes(x= speed_cond_num, y=fit.c, group = subj_char),color="grey", size = .1) +
        geom_line(aes(x= speed_cond_num, y=fit.m, col = group_char), size = 2)+
        facet_wrap(vars(group_char))+
        ggtitle(eeg_measures[eegi])+ 
        guides(group="none")
    )
  }
  
  # t_out <- as_gt(tbl) %>%
  #   gt::tab_header(title=c("Cluster: ",ci)) %>%
  #   gt::tab_options(table.layout = "fixed") %>%
  #   gt::as_raw_html()
  # print(t_out)
  
  # t_out <- as_kable_extra(tbl, format = "latex") %>%
  #   add_header_above(c("Cluster: ",ci)) %>%
  #   kable_styling(latex_options="scale_down")
  # 
  # cat(knitr::knit_print(t_out));
  # if (ci%%2 == 0){
  #   cat('\\clearpage');
  # }
}
```

## LME EEG ~ 1+speed
```{r eegspeed, echo=FALSE, message=FALSE, results="asis"}
# inter_pvalue = vector(mode="logical");
for (ci in cluster_inds_plot) {
  tmpt <- filter_at(eegt,vars('cluster_id'), any_vars(. %in% ci));
  for(ki in kin_inds_plot){
    tmpt = tmpt[complete.cases(tmpt[[kin_measures[ki]]]),]
  }
  tbl <- tibble(outcome=eeg_measures[eeg_inds_plot]) %>%
    rowwise() %>%
    mutate(
      tbl = 
        lmer(str_glue("{outcome} ~ 1 + speed_cond_numsq + speed_cond_num + (1+speed_cond_numsq+speed_cond_num|subj_char)"), data=tmpt) %>%
        tbl_regression(tidy_fun = broom.mixed::tidy,
                       pvalue_fun = purrr::partial(style_pvalue, digits = 2),
                       intercept=TRUE) %>%
        add_global_p() %>%
        add_q() %>%
        list()
      ) %>%
    pull(tbl) %>%
    tbl_merge(tab_spanner=eeg_title_chars[eeg_inds_plot])
  
  t_out <- as_gt(tbl) %>%
    gt::tab_header(title=c("Cluster: ",ci)) %>%
    gt::as_raw_html()
  print(t_out)
  
  rsq <- tibble(outcome=eeg_measures[eeg_inds_plot]) %>%
    rowwise() %>%
    mutate(
        mod = 
          lmer(str_glue("{outcome} ~ 1 + speed_cond_numsq + speed_cond_num + (1+speed_cond_numsq+speed_cond_num|subj_char)"), data=tmpt) %>%
          r.squaredGLMM(),
          print(str_glue("{outcome}\n R2m: {round(mod[1],4)},\tR2c: {round(mod[2],4)}\n\n"))
    )
  
  #%% VISUALIZATION OF MODELS
  theme_set(theme_classic()) # This sets the default ggplot theme
  fitfit <- tibble(outcome=eeg_measures[eeg_inds_plot]) %>%
    rowwise() %>%
    mutate(
        mod = 
          lmer(str_glue("{outcome} ~ 1 + speed_cond_numsq + speed_cond_num + (1+speed_cond_numsq+speed_cond_num|subj_char)"), data=tmpt)%>%
          list()
    )
  for(modi in 1:length(eeg_measures[eeg_inds_plot])){
    eegi = eeg_inds_plot[modi]
    tmpt <- tmpt %>%
      mutate(fit.m = predict(fitfit$mod[[modi]], re.form = NA),
             fit.c = predict(fitfit$mod[[modi]], re.form = NULL))
    
    # print(plot_model(fitfit$mod[[modi]], type = 'diag'))
    
    print(
      tmpt %>%
        ggplot(aes(x = speed_cond_num, y = .data[[eeg_measures[eegi]]], group = subj_char, col=group_char)) +
        geom_point(pch=16, size=2, alpha=0.5) +
        geom_line(aes(x= speed_cond_num, y=fit.c, group = subj_char),color="grey", size = .1) +
        geom_line(aes(x= speed_cond_num, y=fit.m, col = group_char), size = 2)+
        facet_wrap(vars(group_char))+
        ggtitle(eeg_measures[eegi])+ 
        guides(group="none")
    )
  }
  
  # t_out <- as_gt(tbl) %>%
  #   gt::tab_header(title=c("Cluster: ",ci)) %>%
  #   gt::tab_options(table.layout = "fixed") %>%
  #   gt::as_raw_html()
  # print(t_out)
  
  # t_out <- as_kable_extra(tbl, format = "latex") %>%
  #   add_header_above(c("Cluster: ",ci)) %>%
  #   kable_styling(latex_options="scale_down")
  # 
  # cat(knitr::knit_print(t_out));
  # if (ci%%2 == 0){
  #   cat('\\clearpage');
  # }
}
```
