function [str] = logo()
str = sprintf(['CAT CODE\n',...
' _._     _,-''""`-._     \n',...
'(,-.`._,''(       |\\`-/| \n',...
'    `-.-'' \\ )-`( , o o) \n',...
'          `-    \\`_`"''- \n',...
'Code Designer: Chang Liu, Jacob Salminen\n',...
'Code Date: 02/21/2024, MATLAB 2020a\n',...
'Copyright (C) Jacob Salminen, jsalminen@ufl.edu\n',...
'Copyright (C) Chang Liu, liu.chang1@ufl.edu\n']);
disp(str);
end

