%   Project Title: MIM YOUNGER AND OLDER ADULTS KINEMATICS-EEG ANALYSIS
%
%   Code Designer: Jacob salminen
%## SBATCH (SLURM KICKOFF SCRIPT)
% sbatch /blue/dferris/jsalminen/GitHub/par_EEGProcessing/src/2_STUDY/mim_yaoa_speed_kin/.sh

%{
%## RESTORE MATLAB
% WARNING: restores default pathing to matlab 
restoredefaultpath;
clc;
close all;
clearvars
%}
%% SET WORKSPACE ======================================================= %%
% opengl('dsave', 'software') % might be needed to plot dipole plots?
%## TIME
tic
global ADD_CLEANING_SUBMODS STUDY_DIR SCRIPT_DIR %#ok<GVMIS>
ADD_CLEANING_SUBMODS = false;
%## Determine Working Directories
if ~ispc
    try
        SCRIPT_DIR = matlab.desktop.editor.getActiveFilename;
        SCRIPT_DIR = fileparts(SCRIPT_DIR);
        STUDY_DIR = SCRIPT_DIR; % change this if in sub folder
        SRC_DIR = fileparts(fileparts(STUDY_DIR));
    catch e
        fprintf('ERROR. PWD_DIR couldn''t be set...\n%s',getReport(e))
        STUDY_DIR = getenv('STUDY_DIR');
        SCRIPT_DIR = getenv('SCRIPT_DIR');
        SRC_DIR = getenv('SRC_DIR');
    end
else
    try
        SCRIPT_DIR = matlab.desktop.editor.getActiveFilename;
        SCRIPT_DIR = fileparts(SCRIPT_DIR);
    catch e
        fprintf('ERROR. PWD_DIR couldn''t be set...\n%s',getReport(e))
        SCRIPT_DIR = dir(['.' filesep]);
        SCRIPT_DIR = SCRIPT_DIR(1).folder;
    end
    STUDY_DIR = fileparts(SCRIPT_DIR); % change this if in sub folder
    SRC_DIR = fileparts(fileparts(STUDY_DIR));
end
%## Add Study, Src, & Script Paths
addpath(SRC_DIR);
addpath(STUDY_DIR);
cd(SRC_DIR);
fprintf(1,'Current folder: %s\n',SRC_DIR);
%## Set PWD_DIR, EEGLAB path, _functions path, and others...
set_workspace
%% (PARAMETERS) ======================================================== %%
%## hard define
%- datset name
DATA_SET = 'MIM_dataset';
%- study name
STUDY_DNAME = '10172024_MIM_YAOAN89_antsnorm_dipfix_iccREMG0p4_powpow0p3_skull0p01_15mmrej_speed';
STUDY_FNAME = 'kin_eeg_epoch_study';
ANALYSIS_DNAME = 'kin_eeg_step_to_step';
%- statistics & conditions
speed_trials = {'0p25','0p5','0p75','1p0'};
terrain_trials = {'flat','low','med','high'};
COND_DESIGNS = {speed_trials,terrain_trials};
%-
cmap_terrain = linspecer(4);
custom_yellow = [254,223,0]/255;
cmap_terrain = [cmap_terrain(3,:);custom_yellow;cmap_terrain(4,:);cmap_terrain(2,:)];
cmap_speed = linspecer(4*3);
cmap_speed = [cmap_speed(1,:);cmap_speed(2,:);cmap_speed(3,:);cmap_speed(4,:)];
%## (PATHS)
studies_fpath = [PATHS.src_dir filesep '_data' filesep DATA_SET filesep '_studies'];
%- load cluster
CLUSTER_K = 11;
CLUSTER_STUDY_NAME = 'temp_study_rejics5';
cluster_fpath = [studies_fpath filesep sprintf('%s',STUDY_DNAME) filesep '__iclabel_cluster_kmeansalt_rb10'];
% cluster_fpath = [studies_fpath filesep sprintf('%s',STUDY_DNAME) filesep '__iclabel_cluster_kmeansalt_rb3'];
cluster_study_fpath = [cluster_fpath filesep 'icrej_5'];
cluster_k_dir = [cluster_study_fpath filesep sprintf('%i',CLUSTER_K)];
%-
save_dir = [cluster_k_dir filesep ANALYSIS_DNAME];
if ~exist(save_dir,'dir')
    mkdir(save_dir);
end
%% ===================================================================== %%
% if ~ispc
%     [STUDY,ALLEEG] = pop_loadstudy('filename',[STUDY_FNAME '_UNIX.study'],'filepath',save_dir);
% else
%     [STUDY,ALLEEG] = pop_loadstudy('filename',[STUDY_FNAME '.study'],'filepath',save_dir);
% end
%## LOAD STUDY
if ~ispc
    tmp = load('-mat',[studies_fpath filesep sprintf('%s',STUDY_DNAME) filesep sprintf('%s_UNIX.study',STUDY_FNAME)]);
    STUDY = tmp.STUDY;
else
    tmp = load('-mat',[studies_fpath filesep sprintf('%s',STUDY_DNAME) filesep sprintf('%s.study',STUDY_FNAME)]);
    STUDY = tmp.STUDY;
end
%-
cl_struct = par_load(cluster_k_dir,sprintf('cl_inf_%i.mat',CLUSTER_K));
STUDY.cluster = cl_struct;
[comps_out,main_cl_inds,outlier_cl_inds] = eeglab_get_cluster_comps(STUDY);
CLUSTER_PICS = main_cl_inds;
%-
save_dir = [cluster_k_dir filesep ANALYSIS_DNAME];
if ~exist(save_dir,'dir')
    mkdir(save_dir);
end
%% LOAD STUDY
%{
if ~ispc
    [STUDY,ALLEEG] = pop_loadstudy('filename',[CLUSTER_STUDY_NAME '_UNIX.study'],'filepath',cluster_study_fpath);
else
    [STUDY,ALLEEG] = pop_loadstudy('filename',[CLUSTER_STUDY_NAME '.study'],'filepath',cluster_study_fpath);
end
%}
if ~ispc
    tmp = load('-mat',[cluster_study_fpath filesep sprintf('%s_UNIX.study',CLUSTER_STUDY_NAME)]);
    STUDY = tmp.STUDY;
else
    tmp = load('-mat',[cluster_study_fpath filesep sprintf('%s.study',CLUSTER_STUDY_NAME)]);
    STUDY = tmp.STUDY;
end
%## CLUSTER INFO
cl_struct = par_load(cluster_k_dir,sprintf('cl_inf_%i.mat',CLUSTER_K));
STUDY.cluster = cl_struct;
[comps_out,main_cl_inds,outlier_cl_inds] = eeglab_get_cluster_comps(STUDY);
CLUSTER_PICS = main_cl_inds;

%% (LOAD KINEMATICS TABLE) ============================================= %%
KIN_TABLE = par_load(save_dir,'step_by_step_eeg_psd_pertrialpos_table.mat');
% KIN_TABLE = par_load(save_dir,'step_by_step_eeg_table_invdfooof.mat');
for i = 1:length(KINNAMES)
    KIN_TABLE = KIN_TABLE(KIN_TABLE.(KINNAMES{i}) >= 0.010,:);
end
%- 
r_stats_dir = [PATHS.src_dir filesep '2_STUDY' filesep 'mim_yaoa_speed_kin' filesep 'r_scripts' filesep 'sbs_lme_mods'];
RSTATS_IMPORT = readtable([r_stats_dir filesep 'moderation_eeg_psd_kin_speed_intact_nonorm_sepgroup.xlsx'], ...
    "FileType","spreadsheet","UseExcel",true);
%% (STATS STRUCT) ====================================================== %%
DEF_STATS_TRACK_STRUCT = struct('stat_test_mod',{''},...
    'measure_tag',categorical({''}),...
    'design_tag',categorical({''}),...
    'group_tag',categorical({''}),...
    'cluster_tag',categorical({''}),...
    'mod_resp_terms',{''},...
    'rnd_terms',{''},...
    'anova_preds_terms',{{''}},...
    'anova_preds_p',{[]},...
    'anova_preds_stat',{[]},...
    'anova_preds_df1',{[]},...
    'anova_preds_df2',{[]},...
    'mod_preds_terms',{{''}},...
    'mod_preds_p',[],...
    'mod_preds_stat',[],...
    'mod_preds_coeff',[],...
    'mod_r2',[],...
    'multi_comp_terms',{''},...
    'multi_comp_t1_t2',[],...
    'multi_comp_p',[],...
    'multi_comp_coeff',[],...
    'multi_comp_lci_uci',[],...
    'norm_test_p',[],...
    'norm_test_h',[],...
    'effect_size',[],...
    'effect_size_calc',{''});
stats_struct = DEF_STATS_TRACK_STRUCT;
DEF_STATS_TRACK_XLSX = struct('stat_test_mod',{''},...
    'measure_tag',categorical({''}),...
    'design_tag',categorical({''}),...
    'group_tag',categorical({''}),...
    'cluster_tag',categorical({''}),...
    'mod_resp_terms',{''},...
    'rnd_terms',{''},...
    'anova_preds_terms',{{''}},...
    'anova_preds_p',{''},...
    'anova_preds_stat',{''},...
    'anova_preds_df1',{''},...
    'anova_preds_df2',{''},...
    'mod_preds_terms',{''},...
    'mod_preds_p',{''},...
    'mod_preds_stat',{''},...
    'mod_preds_coeff',{''},...
    'mod_r2',[],...
    'multi_comp_terms',{''},...
    'multi_comp_t1_t2',{''},...
    'multi_comp_p',{''},...
    'multi_comp_coeff',{''},...
    'multi_comp_lci_uci',{''},...
    'norm_test_p',[],...
    'norm_test_h',[],...
    'effect_size',[],...
    'effect_size_calc',{''});
stats_xlsx = DEF_STATS_TRACK_XLSX;
cnts = 1;
DESIGN_TABLE_VAR = 'mean_design_id';
GROUP_TABLE_VAR = 'mean_group_id';
%## PLOT ============================================================ %%
%## VISUAL
%- colors
COLOR_MAPS_TERRAIN = linspecer(4);
YELLOW = [254,223,0]/255;
COLOR_MAPS_TERRAIN = [COLOR_MAPS_TERRAIN(3,:);YELLOW;COLOR_MAPS_TERRAIN(4,:);COLOR_MAPS_TERRAIN(2,:)];
COLOR_MAPS_SPEED = linspecer(4*3);
COLOR_MAPS_SPEED = [COLOR_MAPS_SPEED(1,:);COLOR_MAPS_SPEED(2,:);COLOR_MAPS_SPEED(3,:);COLOR_MAPS_SPEED(4,:)];
%-
IM_RESIZE = 1.1;
AX_H  = 0.2;
AX_W = 0.275;
AX_HORIZ_SHIFT = 0.1;
AX_INIT_HORIZ = 0.08;
AX_INIT_VERT = 0.6;
AX_VERT_SHIFT = 0.125;
%-
GROUP_LAB_FONTSIZE = 10;
XLAB_FONTSIZE = 10;
YLAB_FONTSIZE = 10;
XTICK_FONTSIZE = 7;
TITLE_FONTSIZE = 10;
FONT_SIZE_VIO = 10;
FONT_SIZE_VIO_REG = 7;
%-
FONT_NAME = 'Arial';
GROUP_LAB_FONTWEIGHT = 'bold ';
XLAB_FONTWEIGHT = 'bold';
YLAB_FONTWEIGHT = 'bold';
TITLE_FONTWEIGHT = 'bold';
%-
LAB_A_YOFFSET = -0.1;
LAB_A_XOFFSET = -0.125;
LAB_B_YOFFSET = 0.12;
LAB_B_XOFFSET = -0.12;
LAB_C_YOFFSET = 0.12;
LAB_C_XOFFSET = -0.12;
LAB_D_YOFFSET = 0.12;
LAB_D_XOFFSET = -0.12;
XLABEL_OFFSET = -.05;
FIGURE_POSITION =[0,0,6.5,9];
VIOLIN_PARAMS = {'width',0.1,...
    'ShowWhiskers',false,'ShowNotches',false,'ShowBox',true,...
    'ShowMedian',true,'Bandwidth',0.15,'QuartileStyle','shadow',...
    'HalfViolin','full','DataStyle','scatter','MarkerSize',8,...
    'EdgeColor',[0.5,0.5,0.5],'ViolinAlpha',{0.2 0.3}};
VIO_PLOT_STRUCT = struct('color_map',[],...
            'cond_labels',{{'0.25','0.50','0.75','1.0'}},...
            'cond_offsets',[-0.35,-0.1,0.15,0.40],...
            'group_labels',{{'YA','OHMA','OLMA'}},...
            'group_offsets',[0.125,0.475,0.812],...
            'group_lab_yoffset',-0.275,...
            'group_lab_fontweight','normal',...
            'group_lab_fontsize',10,...
            'y_label','unit',...
            'y_label_fontsize',10,...
            'y_label_fontweight','bold',...
            'ylim',[],...
            'x_label','Speed (m/s)',...
            'x_label_fontsize',10,...
            'x_label_fontweight','bold',...
            'x_label_yoffset',-.05,...
            'xlim',[],...
            'title','',...
            'title_fontsize',10,...
            'title_fontweight','bold',...
            'font_size',10,...
            'font_name','Arial',...
            'do_combine_groups',false,...
            'regresslab_txt_size',6,...
            'ax_position',[0,0,1,1],...
            'ax_line_width',1);
BRACKET_STRUCT = struct('sig_sign','+',...
    'line_specs',{{'LineStyle','-','LineWidth',1,'Color','k'}},...
    'text_specs',{{'FontSize',10,'FontName','Arial','FontWeight','bold'}},...
    'bracket_conn',[],...
    'conn_offset_y_upper',[],...
    'bracket_offset_y_upper',0,...
    'bracket_offset_y_lower',0,...
    'sig_levels',[0.05,0.01,0.001],...
    'sig_offset_x',0,...
    'sig_offset_y',[]);
SIGLINE_STRUCT = struct('sig_sign','*',...
    'line_specs',{{'LineStyle','-','LineWidth',2,'Color','k'}},...
    'text_specs',{{'FontSize',10,'FontName','Arial','FontWeight','bold'}},...
    'conn_y',[],...
    'conn_offset_y',[],...
    'sig_levels',[0.05,0.01,0.001],...
    'sig_offset_x',0,...
    'sig_offset_y',0); 
AXES_DEFAULT_PROPS = {'box','off','xtick',[],'ytick',[],...
    'ztick',[],'xcolor',[1,1,1],'ycolor',[1,1,1]};
%## FACTORS
meas_names = {'mean_APexc_COV','mean_MLexc_COV','mean_StepDur_cov','mean_og_mean_ms'};
meas_ylabel = {'COV (%)','COV (%)','COV (%)','Walking Speed (m/s)'};
meas_titles = {{'Anteroposterior Excursion';'Coefficient of Variation'},...
    {'Mediolateral Excursion';'Coefficient of Variation'},...
    {'Step Duration';'Coefficient of Variation'},...
    {'Overground Walking';'Speeds'}};
xtick_label_g = {'0.25','0.50','0.75','1.0'};
YLIM = {[0,65],[0,45],[0,22.5],[0,2.35]};
speed_xvals = (0:5)*0.25;
%## TEMPS
horiz_shift = 0;
vert_shift = 0;
% cnts = 1;
%% FIGURE INIT
fig = figure('color','white','renderer','Painters');
% annotation('textbox',[TITLE_XSHIFT-(TITLE_BOX_SZ(1)/2/2),TITLE_YSHIFT-(TITLE_BOX_SZ(2)/2),TITLE_BOX_SZ(1),TITLE_BOX_SZ(2)],...
%     'String',atlas_name,'HorizontalAlignment','center',...
%     'VerticalAlignment','middle','LineStyle','none','FontName',FONT_NAME,...
%     'FontSize',14,'FontWeight','Bold','Units','normalized');
set(fig,'Units','inches','Position',FIGURE_POSITION)
set(fig,'PaperUnits','inches','PaperSize',[1 1],'PaperPosition',[0 0 1 1])
set(gca,AXES_DEFAULT_PROPS{:});
%% (SPEED) OG SPEEDS - MAIN EFFECTS ================================ %%
meas_i = 4;
des_i = 1;
conds_keep = {1};
%-
tmp = (cellfun(@(x) table_new_ls.trial_tag_in == categorical(x),conds_keep,'UniformOutput',false));
tmp = any(cat(2,tmp{:}),2);
inds = table_new_ls.(DESIGN_TABLE_VAR) == des_i & tmp;
tmp_table = table_new_ls(inds,:);
tmp_table = table(categorical(string(tmp_table.trial_char)),categorical(double(tmp_table.trial_tag_in)),...
    categorical(string(tmp_table.subj_char)),...
    categorical(string(tmp_table.(GROUP_TABLE_VAR))),tmp_table.(meas_names{meas_i}),...
    'VariableNames',{'trial_char','trial_tag_in','subj_char',GROUP_TABLE_VAR,meas_names{meas_i}});
tmp_table(tmp_table.(meas_names{meas_i}) == 0,:) = [];
tmp_table(isnan(tmp_table.(meas_names{meas_i})),:) = [];
tmp_table(isinf(tmp_table.(meas_names{meas_i})),:) = [];
%##
% inds = tmp_table.(GROUP_TABLE_VAR) == categorical(1);
% avg_ya = mean(tmp_table.(meas_names{meas_i})(inds));
% range_ya = range(tmp_table.(meas_names{meas_i})(inds));
% std_ya = std(tmp_table.(meas_names{meas_i})(inds));
% %-
% inds = tmp_table.(GROUP_TABLE_VAR) == categorical(2);
% avg_ohma = mean(tmp_table.(meas_names{meas_i})(inds));
% range_ohma = range(tmp_table.(meas_names{meas_i})(inds));
% std_ohma = std(tmp_table.(meas_names{meas_i})(inds));
% %-
% inds = tmp_table.(GROUP_TABLE_VAR) == categorical(3);
% avg_olma = mean(tmp_table.(meas_names{meas_i})(inds));
% range_olma = range(tmp_table.(meas_names{meas_i})(inds));
% std_olma = std(tmp_table.(meas_names{meas_i})(inds));
%## PLOT =============================================================== %%
ga = 1.447e-05;
gF = 12.874;
%- fdr corrected
multi_comp_pairs = [1,2;1,3;2,3];
adj_p = [0.1853,0.00001,0.0014];
% anova_p = t{2,7};
anova_p = 1.447e-5;
chkl = find((anova_p <= [0.05,0.01,0.001]),1,'last');
if ~isempty(chkl)
    ast = repmat('*',[1,chkl]);
end
str = {sprintf('%s F=%0.2g',ast,gF),...
    '',...
    ''};
STATS_STRUCT = struct('anova',{{anova_p,anova_p,anova_p}},...
    'anova_grp',{{anova_p,anova_p,anova_p}},...
    'pvals',{{}},...
    'pvals_pairs',{{}},...
    'pvals_grp',{num2cell(adj_p)},...
    'pvals_grp_pairs',{num2cell(multi_comp_pairs,2)},...
    'regress_pval',{{}},...
    'regress_line',{{}},...
    'regress_xvals',[],...
    'subject_char',[],... % this option when filled prints removal of nan() info
    'group_order',categorical({''}),...
    'display_stats_char',true,...
    'stats_char',{str});
%-
VIO_PLOT_STRUCT.color_map = COLOR_MAPS_TERRAIN;
VIO_PLOT_STRUCT.cond_labels = {''};
VIO_PLOT_STRUCT.title = meas_titles{meas_i}; %title_plot{meas_i};
VIO_PLOT_STRUCT.y_label = meas_ylabel{meas_i};
VIO_PLOT_STRUCT.x_label = '';
VIO_PLOT_STRUCT.group_offsets = [-0.5,-0.5*2,-0.5*3];
VIO_PLOT_STRUCT.cond_offsets = 0;
VIO_PLOT_STRUCT.xlim = [0.2,1.8];
VIO_PLOT_STRUCT.ylim = YLIM{meas_i};
VIO_PLOT_STRUCT.group_lab_yoffset = -.1;
VIO_PLOT_STRUCT.ax_position = [AX_INIT_HORIZ+horiz_shift,AX_INIT_VERT+vert_shift,AX_W*IM_RESIZE,AX_H*IM_RESIZE];  %[left bottom width height]
%##
BRACKET_STRUCT.conn_offset_y_upper = [0,0.2,0.2];
ax = axes();
ax = group_violin(tmp_table,meas_names{meas_i},'trial_tag_in',GROUP_TABLE_VAR,...
    ax,...
    'VIOLIN_PARAMS',VIOLIN_PARAMS,...
    'PLOT_STRUCT',VIO_PLOT_STRUCT,...
    'STATS_STRUCT',STATS_STRUCT,...
    'SIGLINE_STRUCT',SIGLINE_STRUCT,...
    'BRACKET_STRUCT',BRACKET_STRUCT);
annotation('textbox',[AX_INIT_HORIZ+LAB_D_XOFFSET+(0.1/2)+horiz_shift,AX_INIT_VERT+vert_shift+LAB_B_YOFFSET+(0.1/2),.1,.1],...
    'String','A)','HorizontalAlignment','left',...
    'VerticalAlignment','top','LineStyle','none','FontName',FONT_NAME,...
    'FontSize',14,'FontWeight','Bold','Units','normalized');
%## SHIFT
horiz_shift = horiz_shift + AX_W*IM_RESIZE + AX_HORIZ_SHIFT*IM_RESIZE;
%% (SPEED) AP COV - MAIN EFFECTS ======================================= %%
meas_i = 1;
des_i = 2;
%-
inds = table_new_imu.(DESIGN_TABLE_VAR) == des_i;
tmp_table = table_new_imu(inds,:);
tmp_table = table(double(string(tmp_table.trial_char)),categorical(string(tmp_table.subj_char)),...
    categorical(string(tmp_table.(GROUP_TABLE_VAR))),tmp_table.(meas_names{meas_i}),...
    'VariableNames',{'trial_char','subj_char',GROUP_TABLE_VAR,meas_names{meas_i}});
%## PLOT =============================================================== %%
R2m = 0.3541443;
R2c = 0.6198097;
f2m = 0.5483335;
f2c = 0.1111;
%*
R2 = R2c;
%-
ta = 8.381e-08;
ga = 2.2e-16;
ta = {ta,ta,ta};
ga = {ga,ga,ga};
anova_p = ta{1};
%-
int = 18.706;
tm = -4.345;
gint1 = 6.214;
gint2 = 9.197;
%- fdr corrected
multi_comp_pairs = [1,2;1,3;2,3];
adj_p = [0.00001,0.00001,0.0079];
%## MAIN EFFECTS
coeffs = {[int,tm],...
        [int+gint1,tm],...
        [int+gint2,tm]};
chkl = find((anova_p <= [0.05,0.01,0.001]),1,'last');
if ~isempty(chkl)
    ast = repmat('*',[1,chkl]);
end
% str = {sprintf('%s R^2=%0.2g\nm=%0.2g',ast,R2,tm),...
%     '',...
%     ''};
str = {sprintf('%s R^2=%0.2g\nm=%0.2g',ast,R2,tm),...
    sprintf('b_{YA}=%0.2g  b_{OHMA}=%0.2g  b_{OLMA}=%0.2g\n',int,int+gint1,int+gint2),...
    ''};
%## INTERACTION
STATS_STRUCT = struct('anova',{ta},...
    'anova_grp',{ga},...
    'pvals',{{}},...
    'pvals_pairs',{{}},...
    'pvals_grp',{num2cell(adj_p)},...
    'pvals_grp_pairs',{num2cell(multi_comp_pairs,2)},...
    'regress_pval',{{ta,ta,ta}},...
    'regress_line',{coeffs},...
    'regress_xvals',speed_xvals,...
    'subject_char',[],... % this option when filled prints removal of nan() info
    'group_order',categorical({''}),...
    'display_stats_char',true,...
    'stats_char',{str});
%##
VIO_PLOT_STRUCT.color_map = COLOR_MAPS_SPEED;
VIO_PLOT_STRUCT.cond_labels = xtick_label_g;
VIO_PLOT_STRUCT.title = meas_titles{meas_i}; %title_plot{meas_i};
VIO_PLOT_STRUCT.y_label = meas_ylabel{meas_i};
VIO_PLOT_STRUCT.x_label = 'Speed (m/s)';
VIO_PLOT_STRUCT.x_label_yoffset = -0.13;
VIO_PLOT_STRUCT.group_offsets = [0.125,0.475,0.812];
VIO_PLOT_STRUCT.cond_offsets = [-0.35,-0.1,0.15,0.40];
VIO_PLOT_STRUCT.xlim = [];
VIO_PLOT_STRUCT.ylim = YLIM{meas_i};
VIO_PLOT_STRUCT.group_lab_yoffset = -.22;
VIO_PLOT_STRUCT.regresslab_txt_size = 7;
VIO_PLOT_STRUCT.ax_position = [AX_INIT_HORIZ+horiz_shift,AX_INIT_VERT+vert_shift,AX_W*IM_RESIZE,AX_H*IM_RESIZE];  %[left bottom width height]
%##
BRACKET_STRUCT.conn_offset_y_upper = [1.5,5.5,1.5];
%##
ax = axes();
ax = group_violin(tmp_table,meas_names{meas_i},'trial_char',GROUP_TABLE_VAR,...
    ax,...
    'VIOLIN_PARAMS',VIOLIN_PARAMS,...
    'PLOT_STRUCT',VIO_PLOT_STRUCT,...
    'STATS_STRUCT',STATS_STRUCT,...
    'SIGLINE_STRUCT',SIGLINE_STRUCT,...
    'BRACKET_STRUCT',BRACKET_STRUCT);
%## LETTER
annotation('textbox',[AX_INIT_HORIZ+LAB_A_XOFFSET+(0.1/2)+horiz_shift,AX_INIT_VERT+LAB_A_YOFFSET+AX_H*IM_RESIZE+(0.1/2),.1,.1],...
    'String','B)','HorizontalAlignment','left',...
    'VerticalAlignment','top','LineStyle','none','FontName',FONT_NAME,...
    'FontSize',14,'FontWeight','Bold','Units','normalized');
%## SHIFT
horiz_shift = 0;
vert_shift = vert_shift - AX_H*IM_RESIZE - AX_VERT_SHIFT*IM_RESIZE;
%% (SPEED) ML COV - MAIN EFFECTS ======================================= %%
meas_i = 2;
des_i = 2;
%-
inds = table_new_imu.(DESIGN_TABLE_VAR) == des_i;
tmp_table = table_new_imu(inds,:);
tmp_table = table(double(string(tmp_table.trial_char)),categorical(string(tmp_table.subj_char)),...
    categorical(string(tmp_table.(GROUP_TABLE_VAR))),tmp_table.(meas_names{meas_i}),...
    'VariableNames',{'trial_char','subj_char',GROUP_TABLE_VAR,meas_names{meas_i}});
%## PLOT =============================================================== %%
R2m = 0.1582295;
R2c = 0.4973;
f2m = 0.188;
f2c = 0.4201;
%*
R2 = R2c;
%-
% ga = 0.017280;
% ta = 1.115e-06;
gta =  0.003275;
ta = {gta,gta,gta};
ga = {gta,gta,gta};
anova_p = ta{1};
%-
rs = 1.115e-06;
int = 11.12634;
tm = 5.53992;
gint1 = -3.39468;
gint2 = 0.09723;
gm1 = 4.52826;
gm2 = -0.78165;
%## INTERACTION
coeffs = {[int,tm],...
        [int+gint1,tm+gm1],...
        [int+gint2,tm+gm2]};
chkl = find((anova_p <= [0.05,0.01,0.001]),1,'last');
if ~isempty(chkl)
    ast = repmat('*',[1,chkl]);
end
str = {sprintf('%s %0.2gx+%0.2g',ast,tm,int),...
    sprintf('%s %0.2gx+%0.2g',ast,tm+gm1,int+gint1),...
    sprintf('%s %0.2gx+%0.2g',ast,tm+gm2,int+gint2)};
% str = {sprintf('%s R^2=%0.2g\nm=%0.2g',ast,R2,tm),...
%     '',...
%     ''};
STATS_STRUCT = struct('anova',{ta},...
    'anova_grp',{ga},...
    'pvals',{{}},...
    'pvals_pairs',{{}},...
    'pvals_grp',{{}},...
    'pvals_grp_pairs',{{}},...
    'regress_pval',{ta},...
    'regress_line',{coeffs},...
    'regress_xvals',speed_xvals,...
    'subject_char',[],... % this option when filled prints removal of nan() info
    'group_order',categorical({''}),...
    'display_stats_char',true,...
    'stats_char',{str}); %zeros(length(unique(tmp_table.(GROUP_TABLE_VAR)))));
%##
VIO_PLOT_STRUCT.color_map = COLOR_MAPS_SPEED;
VIO_PLOT_STRUCT.cond_labels = xtick_label_g;
VIO_PLOT_STRUCT.title = meas_titles{meas_i}; %title_plot{meas_i};
VIO_PLOT_STRUCT.y_label = meas_ylabel{meas_i};
VIO_PLOT_STRUCT.x_label = 'Speed (m/s)';
VIO_PLOT_STRUCT.x_label_yoffset = -0.13;
VIO_PLOT_STRUCT.group_offsets = [0.125,0.475,0.812];
VIO_PLOT_STRUCT.cond_offsets = [-0.35,-0.1,0.15,0.40];
VIO_PLOT_STRUCT.xlim = [];
VIO_PLOT_STRUCT.ylim = YLIM{meas_i};
VIO_PLOT_STRUCT.group_lab_yoffset = -.22;
VIO_PLOT_STRUCT.regresslab_txt_size = 7;
VIO_PLOT_STRUCT.ax_position = [AX_INIT_HORIZ+horiz_shift,AX_INIT_VERT+vert_shift,AX_W*IM_RESIZE,AX_H*IM_RESIZE];  %[left bottom width height]
%##
BRACKET_STRUCT.conn_offset_y_upper = [1.5,5,0];
%##
ax = axes();
ax = group_violin(tmp_table,meas_names{meas_i},'trial_char',GROUP_TABLE_VAR,...
    ax,...
    'VIOLIN_PARAMS',VIOLIN_PARAMS,...
    'PLOT_STRUCT',VIO_PLOT_STRUCT,...
    'STATS_STRUCT',STATS_STRUCT,...
    'SIGLINE_STRUCT',SIGLINE_STRUCT,...
    'BRACKET_STRUCT',BRACKET_STRUCT);
%- 
annotation('textbox',[AX_INIT_HORIZ+LAB_C_XOFFSET+(0.1/2)+horiz_shift,AX_INIT_VERT+vert_shift+LAB_C_YOFFSET+(0.1/2),.1,.1],...
    'String','C)','HorizontalAlignment','left',...
    'VerticalAlignment','top','LineStyle','none','FontName',FONT_NAME,...
    'FontSize',14,'FontWeight','Bold','Units','normalized');
%## SHIFT
% horiz_shift = 0;
% vert_shift = vert_shift - AX_H*IM_RESIZE - AX_VERT_SHIFT*IM_RESIZE;
horiz_shift = horiz_shift + AX_W*IM_RESIZE + AX_HORIZ_SHIFT*IM_RESIZE;
%% (SPEED) STEP DUR. COV - MAIN EFFECTS ================================ %%
meas_i = 3;
des_i = 2;
%-
inds = table_new_ls.(DESIGN_TABLE_VAR) == des_i;
tmp_table = table_new_ls(inds,:);
tmp_table = table(double(string(tmp_table.trial_char)),categorical(string(tmp_table.subj_char)),...
    categorical(string(tmp_table.(GROUP_TABLE_VAR))),tmp_table.(meas_names{meas_i}),...
    'VariableNames',{'trial_char','subj_char',GROUP_TABLE_VAR,meas_names{meas_i}});
%## PLOT =============================================================== %%
%-
r2m = 0.4246003;
r2c = 0.5767898;
f2m = 0.7379;
f2c = 1.3629;
%*
R2 = r2c;
%-
ta =  2e-16;
ta = {ta,ta,ta};
ga =  0.5054;
ga = {ga,ga,ga};
anova_p = ta{1};
%- fdr corrected
multi_comp_pairs = [1,2;1,3;2,3];
adj_p = [0.6513,0.6513,0.753];
%-
int = 8.7317;
tm = -5.7030;
gint1 = 0.2586;
gint2 = 0.3634;
%## MAIN EFFECTS
coeffs = {[int,tm],...
        [int+gint1,tm],...
        [int+gint2,tm]};
chkl = find((anova_p <= [0.05,0.01,0.001]),1,'last');
if ~isempty(chkl)
    ast = repmat('*',[1,chkl]);
end
str = {sprintf('%s R^2=%0.2g\nm=%0.2g',ast,R2,tm),...
    sprintf('b_{YA}=%0.2g  b_{OHMA}=%0.2g  b_{OLMA}=%0.2g\n',int,int+gint1,int+gint2),...
    ''};
STATS_STRUCT = struct('anova',{ta},...
    'anova_grp',{ga},...
    'pvals',{{}},...
    'pvals_pairs',{{}},...
    'pvals_grp',{num2cell(adj_p)},...
    'pvals_grp_pairs',{num2cell(multi_comp_pairs,2)},...
    'regress_pval',{{ta,ta,ta}},...
    'regress_line',{coeffs},...
    'regress_xvals',speed_xvals,...
    'subject_char',[],... % this option when filled prints removal of nan() info
    'group_order',categorical({''}),...
    'display_stats_char',true,...
    'stats_char',{str}); %zeros(length(unique(tmp_table.(GROUP_TABLE_VAR)))));
%##
VIO_PLOT_STRUCT.color_map = COLOR_MAPS_SPEED;
VIO_PLOT_STRUCT.cond_labels = xtick_label_g;
VIO_PLOT_STRUCT.title = meas_titles{meas_i}; %title_plot{meas_i};
VIO_PLOT_STRUCT.y_label = meas_ylabel{meas_i};
VIO_PLOT_STRUCT.x_label = 'Speed (m/s)';
VIO_PLOT_STRUCT.x_label_yoffset = -0.13;
VIO_PLOT_STRUCT.group_offsets = [0.125,0.475,0.812];
VIO_PLOT_STRUCT.cond_offsets = [-0.35,-0.1,0.15,0.40];
VIO_PLOT_STRUCT.xlim = [];
VIO_PLOT_STRUCT.ylim = YLIM{meas_i};
VIO_PLOT_STRUCT.group_lab_yoffset = -.22;
VIO_PLOT_STRUCT.regresslab_txt_size = 7;
VIO_PLOT_STRUCT.ax_position = [AX_INIT_HORIZ+horiz_shift,AX_INIT_VERT+vert_shift,AX_W*IM_RESIZE,AX_H*IM_RESIZE];  %[left bottom width height]
%##
BRACKET_STRUCT.conn_offset_y_upper = [0,0.2,0.2];
%##
ax = axes();
ax = group_violin(tmp_table,meas_names{meas_i},'trial_char',GROUP_TABLE_VAR,...
    ax,...
    'VIOLIN_PARAMS',VIOLIN_PARAMS,...
    'PLOT_STRUCT',VIO_PLOT_STRUCT,...
    'STATS_STRUCT',STATS_STRUCT,...
    'SIGLINE_STRUCT',SIGLINE_STRUCT,...
    'BRACKET_STRUCT',BRACKET_STRUCT);
%## LETTER
annotation('textbox',[AX_INIT_HORIZ+LAB_C_XOFFSET+(0.1/2)+horiz_shift,AX_INIT_VERT+vert_shift+LAB_B_YOFFSET+(0.1/2),.1,.1],...
    'String','D)','HorizontalAlignment','left',...
    'VerticalAlignment','top','LineStyle','none','FontName',FONT_NAME,...
    'FontSize',14,'FontWeight','Bold','Units','normalized');
%## SAVE
exportgraphics(fig,[save_dir filesep 'figure_behavioral_data_paper_anova_rdata.tiff'],'Resolution',1000);
exportgraphics(fig,[save_dir filesep 'figure_behavioral_data_paper_anova_rdata.pdf'],'ContentType','vector',...
    'BackgroundColor','white');
% export_fig([save_dir filesep 'figure_behavioral_data_paper_anova_rdata_exportfig.pdf'],'-pdf','-nocrop','-painters')