function [paramso] = local_psd_plot_valid(ax,psd_dat_in,cond_struct,conds,params)
%LOCAL_PSD_PLOT_VALID Summary of this function goes here
%   Detailed explanation goes here
paramso = struct('leg_store',{cell(4,1)});
%## PSD PLOTS
PLOT_STRUCT = struct('y_label',{'10*log_{10}(PSD)'},...
    'y_label_fontsize',10,...
    'y_label_fontweight','bold',...
    'ylim',[],...
    'x_label',{'Frequency (Hz)'},...
    'x_label_fontsize',10,...
    'x_label_fontweight','bold',...
    'x_label_yoffset',0,...
    'xtick_labs',{{}}, ...
    'xticks',[], ...
    'xlim',[],...
    'title',{{''}},...
    'title_fontsize',12,...
    'title_fontweight','normal',...
    'font_size',10,...
    'font_name','Arial',...
    'ax_position',[0.1,0.1,0.7,0.7],...
    'ax_line_width',1,...
    'xtick_angle',45);
LINE_STRUCT = struct('do_line_avg',false, ...
    'line_width',2, ...
    'line_style','-', ...
    'line_alpha',0.7, ...
    'line_color',[1,1,1], ...
    'line_label',{'label'}, ...
    'line_avg_fcn',@(x) mean(x,2), ...
    'do_err_shading',true, ...
    'err_alpha',0.2, ...
    'err_color',[0.5,0.5,0.5], ...
    'err_edge_color',[], ...
    'err_bnd_vec',[], ...
    'err_line_style',':', ...
    'err_line_width',3);

%## PLOT PER CONDITION
for c_i = 1:length(conds)
    inds_cond = cellfun(@(x) any(strcmp(x,conds{c_i})),{cond_struct.cond});
    psd_in_c = squeeze(psd_dat_in(:,inds_cond));
    %--
    LINE_STRUCT.line_color = params.cmaps(c_i,:);
    LINE_STRUCT.line_label = params.xtick_label{c_i};
    LINE_STRUCT.err_color = params.cmaps(c_i,:);
    %--
    mui = mean(psd_in_c,2);
    stdi = std(psd_in_c,[],2);
    LINE_STRUCT.err_bnd_vec = [mui+stdi/sqrt(size(stdi,2)), ...
        mui-stdi/sqrt(size(stdi,2))];
    %## PLOT PSD
    [~,~,Li] = plot_psd(ax,mui,params.freqs, ...
        'LINE_STRUCT',LINE_STRUCT, ...
        'PLOT_STRUCT',PLOT_STRUCT);
    paramso.leg_store{c_i} = Li;
    %--
    hold on;
end

%## LEGEND
leg_store = [paramso.leg_store{:,1}];
legend(gca,leg_store);
[lg2,~,~,~]  = legend('boxoff');
tmp = get(lg2,'String');
set(lg2,'String',tmp, ...
    'FontName','Arial', ...
    'FontSize',10, ...
    'Orientation','vertical', ...
    'Units','normalized');
lg2.ItemTokenSize(1) = 15;
hold off;

end

